// Generated by scripts/split-css.ts from the audited house sheet. Do not edit.
import { css } from "lit";
export const tagCss = css`
  .tags {
    display: flex;
    flex-wrap: wrap;
    gap: 6px;
  }
  .tag {
    display: inline-flex;
    align-items: center;
    height: 20px;
    padding: 0 8px;
    border-radius: 999px;
    background: var(--comp);
    color: var(--text-2);
    font-family: var(--mono);
    font-size: var(--t-2xs);
    line-height: 16px;
    white-space: nowrap;
  }
`;
