// Generated by scripts/split-css.ts from the audited house sheet. Do not edit.
import { css } from "lit";
export const statusDotCss = css`
.status-dot{display:inline-flex;align-items:center;gap:8px;font-size:14px;line-height:20px}
.status-dot::before{content:"";width:10px;height:10px;border-radius:50%;background:var(--st-queued);flex:none}
.status-dot.ready::before{background:var(--st-ready)}
.status-dot.error::before{background:var(--st-error)}
.status-dot.building::before{background:var(--st-building);animation:pulse 1.4s ease-in-out infinite}
.status-dot.queued::before{background:var(--st-queued);animation:pulse 1.4s ease-in-out infinite}
.status-dot.canceled::before,.status-dot.deleted::before{background:var(--st-queued)}
.status-dot.online::before{background:var(--st-online)}
.status-dot b{font-weight:500}
.status-dot .since{color:var(--text-2);margin-left:2px}
.dot.st-ready{background:var(--st-ready)}
.dot.st-error{background:var(--st-error)}
.dot.st-building{background:var(--st-building)}
.dot.st-queued{background:var(--st-queued)}
.dot.ring{box-shadow:0 0 0 1px var(--surface)}
@keyframes pulse{50%{opacity:.4}}
.dot{width:6px;height:6px;border-radius:50%;background:var(--accent);flex:none}
.dot.warn{background:var(--warn)}
.dot.caution{background:var(--caution-bg)}
.dot.good{background:var(--success)}
.dot.faint{background:var(--border)}
.dot[class*="hue-"],.fill[class*="hue-"],.progress > i[class*="hue-"]{background:currentColor}
.dot.series-1,.dot.series-2,.dot.series-3,.dot.series-4,.dot.series-5{background:currentColor}
`;
