// Generated by the style generator from the reference spec. Do not edit; edit the mapping and regenerate.
import { css } from "lit";
export const comboboxOptionCss = css`
  .option:where(.disabled) {
    pointer-events: none;
    opacity: 0.6;
  }
  .option :where(.start) {
    margin-right: 0.75rem;
    margin-left: -1px;
    display: flex;
    align-items: center;
  }
  .option :where(.end) {
    margin-left: auto;
    display: flex;
    align-items: center;
  }
  .option {
    display: flex;
    cursor: pointer;
    scroll-margin-block: 0.5rem;
    align-items: center;
    border-radius: var(--ds-popover-row-radius);
    padding: var(--ds-popover-row-padding);
    color: var(--ds-gray-1000);
    outline-style: none;
  }
  .option :where(.check) {
    width: var(--ds-control-decoration-size);
    height: var(--ds-control-decoration-size);
  }
  .option:where(:not(.auto)) {
    height: var(--ds-popover-row-height);
  }
  .option :where(.label) {
    text-overflow: ellipsis;
    white-space: nowrap;
    overflow: hidden;
    text-align: left;
  }
  .option:where(:not(.active):not(.chosen)) :where(.end) {
    text-overflow: ellipsis;
    white-space: nowrap;
    overflow: hidden;
    text-align: left;
  }
  .option:where(.active) {
    background-color: var(--ds-gray-alpha-100);
  }
  .option:where(.lg) {
    font-size: 1rem;
    line-height: 1.5;
  }
  .option:where(:not(.lg)) {
    font-size: 0.875rem;
    line-height: calc(1.25 / 0.875);
  }
  @media (forced-colors: active) {
    .option {
      outline-offset: 2px;
      outline: 2px solid #0000;
    }
  }
`;
