// Generated by scripts/split-css.ts from the audited house sheet. Do not edit.
import { css } from "lit";
export const panelCss = css`
  .panel {
    position: relative;
    background: var(--surface);
    border-radius: var(--r-sm);
    box-shadow: var(--ds-shadow-border);
    min-width: 0;
  }
  .panel-h {
    min-height: 56px;
    padding: 12px 12px 12px 16px;
    display: flex;
    align-items: center;
    gap: 8px;
    border-bottom: 1px solid var(--hair);
  }
  .panel-h .title {
    font-size: 14px;
    line-height: 20px;
    letter-spacing: -0.28px;
    font-weight: 500;
    margin: 0;
  }
  .panel-h .sub {
    font-size: var(--t-sm);
    line-height: 18px;
    color: var(--text-2);
    margin: 0;
  }
  .panel-h .when {
    font-size: var(--t-xs);
    color: var(--text-2);
    margin-left: 4px;
  }
  .panel-h .actions {
    margin-left: auto;
    display: flex;
    align-items: center;
    gap: 8px;
    flex: none;
  }
  .panel-h .actions a {
    font-size: var(--t-sm);
    font-weight: 500;
  }
  .panel-b {
    padding: 16px;
  }
  .panel-b.tight {
    padding: 12px;
  }
  .panel-b + .panel-b {
    border-top: 1px solid var(--hair);
  }
  .panel-f {
    padding: 12px 16px;
    border-top: 1px solid var(--hair);
    display: flex;
    align-items: center;
    gap: 8px;
    font-size: 14px;
    color: var(--text-2);
  }
  .panel-f.tinted {
    background: var(--surface-2);
    border-top: 1px solid var(--border);
    border-radius: 0 0 4px 4px;
    padding: 12px 12px 12px 20px;
  }
  .panel.danger,
  .panel.error {
    box-shadow: 0 0 0 1px var(--ds-red-400);
  }
  .panel.danger .panel-f.tinted,
  .panel.error .panel-f.tinted {
    background: var(--ds-red-100);
    border-top-color: var(--ds-red-400);
    color: var(--ds-red-900);
  }
  .panel.warning {
    box-shadow: 0 0 0 1px var(--ds-amber-400);
  }
  .panel.warning .panel-f.tinted {
    background: var(--ds-amber-100);
    border-top-color: var(--ds-amber-400);
    color: var(--ds-amber-900);
  }
  .panel-b.form.disabled {
    color: var(--ds-gray-700);
  }
  .panel-b.form.disabled .title-lg,
  .panel-b.form.disabled .desc {
    color: var(--ds-gray-700);
  }
  .panel .error-text {
    display: block;
    font-size: 16px;
    line-height: 24px;
    color: var(--ds-red-900);
    margin-top: 16px;
    padding-bottom: 20px;
  }
  .panel .warning-text {
    display: block;
    font-size: 16px;
    line-height: 24px;
    color: var(--ds-amber-900);
    margin-top: 16px;
    padding-bottom: 20px;
  }
  .panel-f.tinted .status {
    flex: 1;
    min-width: 0;
  }
  .panel-f.tinted .status a {
    color: var(--ds-blue-900);
  }
  .panel-b.form {
    padding: 20px 20px 0;
  }
  .panel .title-lg {
    font-size: 20px;
    line-height: 26px;
    letter-spacing: -0.4px;
    font-weight: 600;
    margin: 0;
  }
  .panel .desc {
    font-size: 14px;
    line-height: 20px;
    color: var(--text-2);
    padding: 8px 0 20px;
    margin: 0;
  }
  .panel.chart {
    border-radius: 10px;
    padding: 12px 12px 8px;
    box-shadow: var(--ds-shadow-border-small);
  }
  .panel.chart .chart-head {
    padding: 0 0 8px;
  }
  .panel.chart .chart-head .title {
    font-size: 14px;
    line-height: 16px;
  }
  .panel-f .actions {
    margin-left: auto;
    display: flex;
    gap: 8px;
  }
  .panel > .items {
    padding: 0 16px;
  }
  .panel > .table-wrap {
    padding: 0 16px;
  }
  .panel .expand {
    position: absolute;
    left: 50%;
    bottom: -16px;
    transform: translateX(-50%);
    z-index: 2;
    border-radius: 50%;
    background: var(--surface);
    box-shadow: var(--ds-shadow-border-small);
    border: 0;
  }
  .panels {
    display: grid;
    grid-template-columns: repeat(var(--cols, 2), minmax(0, 1fr));
    gap: var(--s-4);
  }
  @media (max-width: 900px) {
    .panels {
      grid-template-columns: minmax(0, 1fr);
    }
  }
  .fold .expand,
  .panel .expand.pill-btn {
    position: absolute;
    left: 50%;
    bottom: -13px;
    transform: translateX(-50%);
    z-index: 2;
    height: 26px;
    padding: 4px 10px;
    border-radius: 999px;
    background: var(--surface);
    border: 1px solid var(--border);
    display: inline-flex;
    align-items: center;
    gap: 6px;
    font-size: 12px;
    color: var(--text-2);
    cursor: pointer;
  }
`;
