// Generated by the style generator from the reference spec. Do not edit; edit the mapping and regenerate.
import { css } from "lit";
export const copyButtonCss = css`
  .stack :where(.check) {
    position: absolute;
    transition-property: all;
    transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1);
    transition-duration: 0.2s;
    animation-duration: 0.2s;
    animation-timing-function: cubic-bezier(0.4, 0, 0.2, 1);
  }
  .stack :where(.copy) {
    position: absolute;
    transition-property: all;
    transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1);
    transition-duration: 0.2s;
    animation-duration: 0.2s;
    animation-timing-function: cubic-bezier(0.4, 0, 0.2, 1);
  }
  .stack {
    position: relative;
    width: 1rem;
    height: 1rem;
  }
  .stack:where(:not(.copied)) :where(.check) {
    scale: 50% 50%;
    opacity: 0;
  }
  .stack:where(.copied) :where(.copy) {
    scale: 50% 50%;
    opacity: 0;
  }
  .stack:where(.copied) :where(.check) {
    scale: 100% 100%;
    opacity: 1;
  }
  .stack:where(:not(.copied)) :where(.copy) {
    scale: 100% 100%;
    opacity: 1;
  }
`;
