// Generated by the style generator from the reference spec. Do not edit; edit the mapping and regenerate.
import { css } from "lit";
export const separatorCss = css`
  .separator:where(.vertical) {
    height: 100%;
    width: 1px;
  }
  .separator:where(:not(.vertical)) {
    height: 1px;
    width: 100%;
  }
  .separator {
    flex-shrink: 0;
    background-color: var(--ds-gray-200);
  }
`;
