// Generated by scripts/split-css.ts from the audited house sheet. Do not edit.
import { css } from "lit";
export const chartCss = css`
  .chart {
    display: flex;
    flex-direction: column;
    gap: 12px;
    min-width: 0;
  }
  .chart .plot {
    position: relative;
    min-height: 180px;
  }
  .chart .plot svg {
    display: block;
    width: 100%;
    height: 100%;
    overflow: visible;
  }
  .chart .grid {
    stroke: var(--ds-gray-100);
    stroke-width: 1;
  }
  .chart .grid.dashed {
    stroke-dasharray: 2 4;
    stroke: var(--border);
  }
  .chart .axis {
    font-family: var(--mono);
    font-size: 10px;
    fill: var(--text-2);
  }
  .chart .series {
    fill: none;
    stroke: currentColor;
    stroke-width: 2;
    stroke-linejoin: round;
    stroke-linecap: round;
    color: var(--accent);
  }
  .chart .series.dashed {
    stroke-dasharray: 4 4;
  }
  .chart .area {
    fill: currentColor;
    opacity: 0.12;
    color: var(--accent);
  }
  .chart .bar {
    fill: currentColor;
    color: var(--accent);
  }
  .chart .bar.muted {
    color: var(--ds-gray-500);
  }
  .chart .marker {
    fill: currentColor;
    color: var(--accent);
    stroke: var(--surface);
    stroke-width: 2;
  }
  .chart .ring {
    fill: none;
    stroke: currentColor;
    stroke-width: 14;
  }
  .chart .ring.track {
    color: var(--comp);
  }
  .chart .tip {
    position: absolute;
    z-index: 5;
    pointer-events: none;
    background: var(--surface);
    border-radius: var(--r);
    box-shadow: var(--ds-shadow-tooltip);
    padding: 8px 12px;
    font-size: var(--t-sm);
    line-height: 18px;
    min-width: 120px;
  }
  .chart .tip .when {
    font-weight: 600;
    color: var(--text);
  }
  .chart .tip .row {
    display: flex;
    justify-content: space-between;
    gap: 12px;
    color: var(--text-2);
  }
  .chart .tip .row b {
    font-family: var(--mono);
    font-weight: 500;
    color: var(--text);
  }
  .chart .cursor {
    stroke: var(--ds-gray-500);
    stroke-width: 1;
  }
  .chart .step {
    fill: none;
    stroke: currentColor;
    stroke-width: 1.5;
    color: var(--accent);
  }
  .chart .step-area {
    fill: currentColor;
    opacity: 0.2;
    color: var(--accent);
  }
  .chart .tip .series {
    display: flex;
    align-items: center;
    gap: 8px;
    justify-content: space-between;
  }
  .chart .tip .series .dot {
    width: 6px;
    height: 6px;
  }
  .chart .tip .muted {
    color: var(--text-2);
    font-size: var(--t-xs);
  }
`;
