// Generated by scripts/split-css.ts from the audited house sheet. Do not edit.
import { css } from "lit";
export const badgeCss = css`
.badge{display:inline-flex;align-items:center;gap:5px;height:24px;padding:2px 12px;border-radius:999px;font-size:12px;line-height:20px;font-weight:500;white-space:nowrap;text-transform:capitalize;
       background:var(--ds-gray-900);color:var(--ds-background-100);border:0}
.badge .ic{width:14px;height:14px}
.badge.subtle{background:var(--ds-gray-100);color:var(--ds-gray-900)}
.badge.blue{background:var(--ds-blue-700);color:#fff}
.badge.blue.subtle{background:var(--ds-blue-100);color:var(--ds-blue-900)}
.badge.purple{background:var(--ds-purple-700);color:#fff}
.badge.purple.subtle{background:var(--ds-purple-100);color:var(--ds-purple-900)}
.badge.amber{background:var(--ds-amber-700);color:var(--ds-gray-1000)}
.badge.amber.subtle{background:var(--ds-amber-100);color:var(--ds-amber-900)}
.badge.red{background:var(--ds-red-700);color:#fff}
.badge.red.subtle{background:var(--ds-red-100);color:var(--ds-red-900)}
.badge.pink{background:var(--ds-pink-700);color:#fff}
.badge.pink.subtle{background:var(--ds-pink-100);color:var(--ds-pink-900)}
.badge.green{background:var(--ds-green-700);color:#fff}
.badge.green.subtle{background:var(--ds-green-100);color:var(--ds-green-900)}
.badge.teal{background:var(--ds-teal-700);color:#fff}
.badge.teal.subtle{background:var(--ds-teal-100);color:var(--ds-teal-900)}
.badge.inverted{background:var(--text);color:var(--on-contrast)}
.badge.outline{background:transparent;border:1px solid var(--ds-gray-500);color:var(--text)}
.badge.blue.outline{border-color:var(--ds-blue-600);color:var(--ds-blue-900)}
.badge.purple.outline{border-color:var(--ds-purple-600);color:var(--ds-purple-900)}
.badge.amber.outline{border-color:var(--ds-amber-700);color:var(--ds-amber-900)}
.badge.red.outline{border-color:var(--ds-red-600);color:var(--ds-red-900)}
.badge.pink.outline{border-color:var(--ds-pink-600);color:var(--ds-pink-900)}
.badge.green.outline{border-color:var(--ds-green-600);color:var(--ds-green-900)}
.badge.teal.outline{border-color:var(--ds-teal-600);color:var(--ds-teal-900)}
.badge.sm{height:20px;padding:2px 8px;gap:4px;font-size:11px;line-height:16px;letter-spacing:.2px}
.badge.sm .ic{width:12px;height:12px}
.badge.lg{height:32px;padding:2px 12px;gap:6px;font-size:14px;line-height:20px}
.badge.lg .ic{width:16px;height:16px}
.badge.mono{font-family:var(--mono)}
.badge.good{background:var(--ds-green-100);color:var(--ds-green-900)}
.badge.accent{background:var(--ds-blue-100);color:var(--ds-blue-900)}
.badge.caution{background:var(--ds-amber-100);color:var(--ds-amber-900)}
.badge.warn{background:var(--ds-red-100);color:var(--ds-red-900)}
`;
