// Generated by the style generator from the reference spec. Do not edit; edit the mapping and regenerate.
import { css } from "lit";
export const menuButtonCss = css`
  .btn :where(.label) :where(.inner) :where(.chev) {
    position: absolute;
    top: 50%;
    right: -1px;
    box-sizing: border-box;
    display: inline-flex;
    height: 30px;
    width: 2.5rem;
    translate: 0 calc(calc(1 / 2 * 100%) * -1);
    cursor: pointer;
    align-items: center;
    justify-content: center;
    border-style: solid;
    border-width: 0;
    background-image: none;
    font-size: 1rem;
    line-height: 1.5;
    color: var(--accents-3);
    text-decoration-line: none;
    outline-style: none;
    transition-property: color, background-color, border-color, outline-color, text-decoration-color, fill, stroke, --acme-gradient-from, --acme-gradient-via, --acme-gradient-to;
    transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1);
    transition-duration: 0.15s;
    -webkit-user-select: none;
    user-select: none;
    tap-highlight-color: transparent;
    animation-duration: 0.15s;
  }
  .btn:where(:not(.chevron)) :where(.label) {
    display: flex;
    align-items: center;
    justify-content: center;
  }
  .btn :where(.label) :where(.inner) {
    display: flex;
    width: 100%;
    flex-wrap: nowrap;
    align-items: center;
    justify-content: space-between;
    gap: 0.25rem;
  }
  .btn:where(.chevron) :where(.label) {
    display: inline-block;
    flex-grow: 1;
  }
  .btn :where(.label) :where(.inner) :where(.chev) :where(svg) {
    width: var(--ds-control-decoration-size);
    height: var(--ds-control-decoration-size);
  }
  .btn:where(.icon-only) :where(.label) {
    flex-shrink: 0;
  }
  .btn:where(:not(.open)) :where(.label) :where(.inner) :where(.chev) :where(svg) {
    rotate: 0deg;
    transition-property: transform, translate, scale, rotate;
    transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1);
    transition-duration: 0.15s;
    animation-duration: 0.15s;
  }
  .btn:where(.open) :where(.label) :where(.inner) :where(.chev) :where(svg) {
    rotate: 180deg;
    transition-property: none;
  }
  .btn :where(.label) {
    text-overflow: ellipsis;
    white-space: nowrap;
    overflow: hidden;
    padding-inline: 0.375rem;
  }
  .btn:where(.open.icon-only:not(.unstyled)) {
    background-color: var(--ds-gray-400);
  }
  .btn:where(.chevron) {
    padding-right: 2.5rem !important;
  }
  @media (forced-colors: active) {
    .btn :where(.label) :where(.inner) :where(.chev) {
      outline-offset: 2px;
      outline: 2px solid #0000;
    }
  }
  .btn:where(:not(.unstyled)) svg {
    flex-shrink: 0;
  }
  .btn:where(.unstyled) > span {
    padding-inline: 0 !important;
  }
  .btn:where(.secondary)[data-hover="true"] :where(.label) :where(.inner) :where(.chev) {
    color: var(--ds-gray-1000);
  }
  .btn:where(.secondary)[data-hover] {
    background-color: var(--ds-background-100) !important;
    box-shadow: 0 0 0 1px var(--ds-gray-alpha-500);
  }
`;
