// Generated by scripts/split-css.ts from the audited house sheet. Do not edit.
import { css } from "lit";
export const menuCss = css`
.menu{position:absolute;z-index:20;min-width:200px;padding:6px;background:var(--surface);border-radius:12px;box-shadow:var(--ds-shadow-menu);display:none}
.menu.static{position:static;display:block}
.menu .user{padding:8px 8px 10px}
.menu .user .name{font-size:14px;line-height:20px;font-weight:500}
.menu .user .mail{font-size:13px;line-height:18px;color:var(--text-2)}
.menu .row{display:flex;align-items:center;justify-content:space-between;height:36px;padding:0 8px;font-size:14px}
.menu .foot{margin:6px -6px -6px;padding:12px 14px;background:var(--surface-2);border-radius:0 0 12px 12px;font-size:14px;line-height:20px;color:var(--accent);display:flex;align-items:center;justify-content:space-between}
.menu .foot .dot{width:10px;height:10px}
.menu.show{display:block}
.menu button,.menu a{display:flex;align-items:center;gap:8px;width:100%;text-align:left;background:transparent;border:0;height:36px;padding:0 8px;
                     border-radius:var(--r-sm);font-size:14px;color:var(--text);text-decoration:none}
.menu button:hover,.menu a:hover{background:var(--comp)}
.menu button.danger{color:var(--warn)}
.menu button.danger:hover{background:var(--warn-weak)}
.menu button[disabled]{color:var(--ds-gray-700);cursor:not-allowed}
.menu hr{border:0;border-top:1px solid var(--border);margin:4px 0}
.menu .kbd{margin-left:auto}
.menu .head{padding:8px 8px 4px;font-size:14px;line-height:20px;color:var(--text-2)}
.menu .kv-row{display:flex;align-items:center;justify-content:space-between;gap:12px;height:36px;padding:0 8px;font-size:14px;color:var(--text)}
.menu .kv-row .v{font-family:var(--mono);font-variant-numeric:tabular-nums;color:var(--text)}
.menu .kv-row.muted{color:var(--text-2)}
.menu .kv-row.muted .v{color:var(--text-2)}
.menu.wide{min-width:300px}
.menu button .ic.end{margin-left:auto}
@media (pointer:coarse){
  .menu button,.menu a{height:44px}
}
`;
