const fixture = window as typeof window & { pager: AcmePagination; requests: unknown[] };
import {AcmePagination} from '../pagination';customElements.define('acme-pagination',AcmePagination);
import {AcmePaginationPrevious} from '../../pagination-previous/pagination-previous';customElements.define('acme-pagination-previous',AcmePaginationPrevious);
import {AcmePaginationNext} from '../../pagination-next/pagination-next';customElements.define('acme-pagination-next',AcmePaginationNext);
import {AcmePaginationItem} from '../../pagination-item/pagination-item';customElements.define('acme-pagination-item',AcmePaginationItem);
import {AcmePaginationPosition} from '../../pagination-position/pagination-position';customElements.define('acme-pagination-position',AcmePaginationPosition);
import {AcmePaginationPageSize} from '../../pagination-page-size/pagination-page-size';customElements.define('acme-pagination-page-size',AcmePaginationPageSize);
import {AcmePaginationEllipsis} from '../../pagination-ellipsis/pagination-ellipsis';customElements.define('acme-pagination-ellipsis',AcmePaginationEllipsis);
import {AcmeSelect} from '../../select/select';customElements.define('acme-select',AcmeSelect);
import {AcmeOption} from '../../option/option';customElements.define('acme-option',AcmeOption);
import {AcmeField} from '../../field/field';customElements.define('acme-field',AcmeField);
import {AcmeButton} from '../../button/button';customElements.define('acme-button',AcmeButton);
import {AcmeIconButton} from '../../icon-button/icon-button';customElements.define('acme-icon-button',AcmeIconButton);
import {AcmeSpinner} from '../../spinner/spinner';customElements.define('acme-spinner',AcmeSpinner);
import {AcmeGroup} from '../../group/group';customElements.define('acme-group',AcmeGroup);
import {AcmeTheme} from '../../theme/theme';customElements.define('acme-theme',AcmeTheme);
import {AcmeOverlayTheme} from '../../../internal/overlay-theme/overlay-theme';customElements.define('acme-overlay-theme',AcmeOverlayTheme);
import {AcmeExpandMoreIcon} from '../../../generated/icons/classes/expand-more-icon';customElements.define('acme-expand-more-icon',AcmeExpandMoreIcon);
import {AcmeCheckIcon} from '../../../generated/icons/classes/check-icon';customElements.define('acme-check-icon',AcmeCheckIcon);
import {AcmeCloseIcon} from '../../../generated/icons/classes/close-icon';customElements.define('acme-close-icon',AcmeCloseIcon);
document.body.innerHTML='<button id="before">Before</button><acme-pagination id="pager" count="100"></acme-pagination><button id="after">After</button>';Object.assign(fixture,{pager:document.querySelector<AcmePagination>('#pager')!,requests:[]});fixture.pager.addEventListener('acme-request',e=>fixture.requests.push((e as CustomEvent<unknown>).detail));