// Generated by scripts/split-css.ts from the audited house sheet. Do not edit.
import { css } from "lit";
export const gridCss = css`
.gs{--cols:3;position:relative;display:grid;grid-template-columns:repeat(var(--cols),minmax(0,1fr));border-top:1px solid var(--gs-line,var(--border));border-bottom:1px solid var(--gs-line,var(--border))}
.gs.dashed{--gs-style:dashed}
.gs > .gs-cell{position:relative;min-height:120px;padding:48px;font-size:16px;line-height:24px;color:var(--text);border-right:1px var(--gs-style,solid) var(--gs-line,var(--border));border-bottom:1px var(--gs-style,solid) var(--gs-line,var(--border))}
.gs > .gs-cell:nth-child(var(--cols)n){border-right:0}
.gs > .gs-cell.solid{background:var(--surface);z-index:1}
.gs > .gs-cell.span-2{grid-column:span 2}
.gs > .gs-cell.span-3{grid-column:span 3}
.gs > .gs-cell.span-all{grid-column:1/-1}
.gs.hide-rows > .gs-cell{border-bottom:0}
.gs.hide-cols > .gs-cell{border-right:0}
.gs-cross{position:absolute;width:21px;height:21px;z-index:2;pointer-events:none;transform:translate(-50%,-50%)}
.gs-cross::before,.gs-cross::after{content:"";position:absolute;background:var(--ds-gray-alpha-600)}
.gs-cross::before{left:10px;top:0;width:1px;height:21px}
.gs-cross::after{top:10px;left:0;height:1px;width:21px}
.gs-page{background:var(--surface-2);padding:0 0 90px;border-radius:var(--r)}
.gs.debug{--gs-line:var(--ds-amber-400)}
`;
