// Generated by the style generator from the reference spec. Do not edit; edit the mapping and regenerate.
import { css } from "lit";
export const tabsCss = css`
  .tabs {
    margin-bottom: 0.75rem;
    scrollbar-width: none;
    -webkit-overflow-scrolling: touch;
    display: flex;
    flex-wrap: nowrap;
    align-items: center;
    overflow-x: auto;
    padding-bottom: 1px;
  }
  .tabs:where(:not(.secondary)) {
    gap: 1.5rem;
    box-shadow: 0 -1px 0 var(--accents-2) inset;
  }
  .tabs:where(.secondary) {
    box-shadow: none !important;
  }
  .tabs::-webkit-scrollbar {
    display: none;
  }
  .tabs[data-focus-within] {
    overflow: visible;
  }
`;
