// Writes src/generated/theme.css: Geist's design-token declarations verbatim, in cascade
// order, with every tier they ship (sRGB, `@supports (color: lab())`, P3 `oklch` under a
// color-gamut media query), and the theme selectors mapped to ours: `:root`/`:host` stay the
// root; `.dark`/`.dark-theme` become `:root:where([data-theme="dark"])` (same specificity as :root, as in the source) plus the prefers-color-scheme
// guard; `.light-theme` becomes `:root:where([data-theme="light"])`; `.invert-theme` is dropped. The
// type families are overridden to the house fonts. tokens.css appends this file.
import fs from "node:fs";
import path from "node:path";
import { allRules, sheetOrder } from "./tw";

const ROOT = path.resolve(import.meta.dir, "../..");
const OUT = path.join(ROOT, "src/generated");
fs.mkdirSync(OUT, { recursive: true });

/** Token namespaces the elements reference. Tailwind theme constants are inlined by the generator and need no variable. */
// `--color-*`: the reference's theme layer names the few palette entries its base reset reads (`border-color: var(--color-gray-200, currentcolor)`).
const KEEP = /^--(ds-|geist-|font-geist-|font-sans|font-mono|themed-|font-sans-fallback|font-mono-fallback|accents-|button-|shadow-|color-)/;

type Out = { at: string; sel: string; decls: string[] };
const blocks: Out[] = [];
const push = (at: string, sel: string, decls: string[]) => {
  const last = blocks[blocks.length - 1];
  if (last && last.at === at && last.sel === sel) last.decls.push(...decls);
  else blocks.push({ at, sel, decls: [...decls] });
};

for (const r of allRules()) {
  if (/@media \(prefers-color-scheme/.test(r.at)) continue; // Geist themes by class; the guard is ours below
  const s = r.sel.trim();
  const targets: string[] = [];
  if (/^(:root|html|:host)$/.test(s)) targets.push(":root");
  else if (/^(:root|html)?\.(dark|dark-theme)$/.test(s)) targets.push(':root:where([data-theme="dark"])', "@dark");
  else if (/^(:root|html)?\.light-theme$/.test(s)) targets.push(':root:where([data-theme="light"])');
  else continue;
  const decls = r.decl
    .split(/;(?![^(]*\))/)
    .map((d) => d.trim())
    .filter((d) => KEEP.test(d.slice(0, d.indexOf(":")).trim()));
  if (!decls.length) continue;
  for (const t of targets) push(r.at.replace(/@layer [a-z]+\s*/g, "").trim(), t, decls);
}

const wrap = (at: string, body: string) => {
  const parts = at.split(/\s(?=@)/).filter(Boolean);
  return parts.reduceRight((inner, a) => `${a} {\n${inner}\n}`, body);
};
const render = (b: Out) => {
  const body = `  ${b.decls.join(";\n  ")};`;
  if (b.sel === "@dark") return wrap(`${b.at} @media (prefers-color-scheme: dark)`.trim(), `:root:where(:not([data-theme="light"])) {\n${body}\n}`);
  return wrap(b.at, `${b.sel} {\n${body}\n}`);
};

const cssText = sheetOrder()
  .map((f) => fs.readFileSync(path.join(import.meta.dir, "corpus/css", f), "utf8"))
  .join("\n");
const props = Array.from(new Set(cssText.match(/@property --tw-[a-z0-9-]+\{[^}]*\}/g) ?? [])).join("\n");

const fonts = `:root {
  --font-geist-sans: "Google Sans Flex", var(--font-sans-fallback);
  --font-geist-mono: "GoogleSansCode Nerd Font Mono", "Google Sans Code", var(--font-mono-fallback);
  --font-sans: var(--font-geist-sans);
  --font-mono: var(--font-geist-mono);
}`;

const out = `/* Generated by the token generator from the reference spec (${new Date().toISOString().slice(0, 10)}). Do not edit. */
${blocks.map(render).join("\n")}
${fonts}
${props}
`;
fs.writeFileSync(path.join(OUT, "theme.css"), out.replace(/--font-geist-/g, "--acme-font-").replace(/--geist-/g, "--acme-"));
const count = (sel: string) => blocks.filter((b) => b.sel === sel).reduce((n, b) => n + b.decls.length, 0);
console.log(`theme.css: ${blocks.length} blocks, ${count(":root")} root decls, ${count(':root:where([data-theme="dark"])')} dark decls, ${(props.match(/@property/g) ?? []).length} @property`);
