import fs from 'node:fs';import path from 'node:path';
const root=new URL('../../../../',import.meta.url).pathname,out=path.join(root,'.artifacts/m26-bundle/reduction');fs.mkdirSync(out,{recursive:true});
const cases=[];
for(const sideEffects of ['absent','define-only','all'] as const)for(const reexport of ['star','named','direct'] as const)for(const shape of ['plain','derived','decorated'] as const){
 const id=[sideEffects,reexport,shape].join('-'),dir=path.join(out,id);fs.mkdirSync(path.join(dir,'define'),{recursive:true});
 await Bun.write(path.join(dir,'package.json'),JSON.stringify({name:id,type:'module',...(sideEffects==='absent'?{}:{sideEffects:sideEffects==='all'?true:['./define/*.js']})}));
 await Bun.write(path.join(dir,'base.js'),'export class Base extends HTMLElement {}');
 await Bun.write(path.join(dir,'example.js'),(shape==='derived'?'import {Base} from "./base.js";':'')+'export class Example extends '+(shape==='derived'?'Base':'HTMLElement')+' {}'+(shape==='decorated'?'\nObject.defineProperty(Example.prototype,"property",{value:42});':''));
 await Bun.write(path.join(dir,'index.js'),reexport==='star'?'export * from "./example.js";':'export {Example} from "./example.js";');
 await Bun.write(path.join(dir,'define/example.js'),'import "../example.js";import {Example} from "../example.js";customElements.define("acme-probe",Example);');
 await Bun.write(path.join(dir,'probe.js'),'import * as library from "./'+(reexport==='direct'?'example':'index')+'.js";const before=typeof library.Example;await import("./define/example.js");window.__result={before,after:typeof library.Example,same:customElements.get("acme-probe")===library.Example};');
 const build=await Bun.build({entrypoints:[path.join(dir,'probe.js')],outdir:path.join(dir,'bundle'),target:'browser',format:'esm',splitting:false});if(!build.success)throw new AggregateError(build.logs,'Reduction build failed');cases.push({id,sideEffects,reexport,shape});
}
const server=Bun.serve({port:0,async fetch(req){const url=new URL(req.url);if(url.pathname.endsWith('/page')){const id=url.pathname.split('/')[1];return new Response('<script type="module" src="/'+id+'/bundle/probe.js"></script>',{headers:{'Content-Type':'text/html'}});}const file=Bun.file(path.join(out,url.pathname));return await file.exists()?new Response(file):new Response('Missing',{status:404});}});
const runtime=process.env.ACME_BROWSER_RUNTIME;if(!runtime)throw Error('Set ACME_BROWSER_RUNTIME');process.env.PLAYWRIGHT_BROWSERS_PATH=path.join(runtime,'browsers');const {chromium}=await import(path.join(runtime,'node_modules/playwright/index.mjs'));const browser=await chromium.launch({headless:true,...(process.env.ACME_CHROMIUM_PATH?{executablePath:process.env.ACME_CHROMIUM_PATH}:{})});const reports=[];
try{for(const entry of cases){const page=await browser.newPage();await page.goto(server.url.origin+'/'+entry.id+'/page');await page.waitForFunction(()=>Object.hasOwn(window,'__result'));const result=await page.evaluate(()=>Reflect.get(window,'__result'));reports.push({...entry,...result,pass:result.before==='function'&&result.after==='function'&&result.same});await page.close();}await Bun.write(path.join(out,'results.json'),JSON.stringify({bun:Bun.version,reports},null,2));console.log(JSON.stringify(reports.filter(r=>!r.pass),null,2));console.log('cases',reports.length);}finally{await browser.close();server.stop(true);}
