import fs from 'node:fs';import path from 'node:path';import ts from 'typescript';import assert from 'node:assert/strict';
const consumer=process.env.ACME_BUNDLE_CONSUMER;if(!consumer)throw Error('Set ACME_BUNDLE_CONSUMER');assert.equal(JSON.parse(fs.readFileSync(path.join(consumer,'package.json'),'utf8')).name,'bundle-consumer');
const root=new URL('../../../../',import.meta.url).pathname,directory=path.join(consumer,'node_modules/@acmelabs/design-system/dist');
const original=await Bun.file(new URL('./archived-index-original.js',import.meta.url)).text(),ast=ts.createSourceFile('index.js',original,ts.ScriptTarget.Latest,true,ts.ScriptKind.JS),scan=new Bun.Transpiler({loader:'js'});
const bindings=new Map<string,{module:string;name:string}>();
for(const statement of ast.statements){if(!ts.isExportDeclaration(statement)||!statement.moduleSpecifier||!ts.isStringLiteral(statement.moduleSpecifier))continue;const module=statement.moduleSpecifier.text;if(statement.exportClause&&ts.isNamedExports(statement.exportClause))for(const name of statement.exportClause.elements)bindings.set(name.name.text,{module,name:(name.propertyName??name.name).text});}
for(const statement of ast.statements){if(!ts.isExportDeclaration(statement)||statement.exportClause||!statement.moduleSpecifier||!ts.isStringLiteral(statement.moduleSpecifier))continue;const module=statement.moduleSpecifier.text,base=path.resolve(directory,module),file=fs.existsSync(base)?base:base+'.js';for(const name of scan.scan(fs.readFileSync(file,'utf8')).exports)if(name!=='default'&&!bindings.has(name))bindings.set(name,{module,name});}
const modules=[...new Set([...bindings.values()].map(binding=>binding.module))];
const imports=modules.map((module,index)=>'import * as origin'+index+' from '+JSON.stringify(path.resolve(directory,module))+ ';').join('\n');
const expected=[...bindings].map(([name,binding])=>JSON.stringify(name)+':origin'+modules.indexOf(binding.module)+'['+JSON.stringify(binding.name)+']').join(',');
await Bun.write(path.join(consumer,'symbols.ts'),'import * as library from "@acmelabs/design-system";\n'+imports+'\nconst expected={'+expected+'};const mismatches=Object.keys(expected).filter(name=>library[name]!==expected[name]);const names=Object.keys(library).sort();await import("@acmelabs/design-system/define/heading");window.__symbols={names,expected:Object.keys(expected).sort(),mismatches,identity:customElements.get("acme-heading")===library.AcmeHeading};');
const runtime=process.env.ACME_BROWSER_RUNTIME;if(!runtime)throw Error('Set ACME_BROWSER_RUNTIME');process.env.PLAYWRIGHT_BROWSERS_PATH=path.join(runtime,'browsers');const pw=await import(path.join(runtime,'node_modules/playwright/index.mjs'));const reports=[];
for(const splitting of [false,true]){
 const output=path.join(consumer,'symbols-'+splitting);const build=await Bun.build({entrypoints:[path.join(consumer,'symbols.ts')],outdir:output,target:'browser',format:'esm',splitting});if(!build.success)throw new AggregateError(build.logs,'Symbol probe build failed');
 const server=Bun.serve({hostname:'127.0.0.1',port:0,async fetch(request){const url=new URL(request.url);if(url.pathname==='/')return new Response('<script type="module" src="/symbols.js"></script>',{headers:{'Content-Type':'text/html'}});const file=Bun.file(path.join(output,url.pathname));return await file.exists()?new Response(file):new Response('Missing',{status:404});}});
 try{for(const engine of ['chromium','firefox','webkit']){const browser=await pw[engine].launch({headless:true,...(engine==='chromium'&&process.env.ACME_CHROMIUM_PATH?{executablePath:process.env.ACME_CHROMIUM_PATH}:{})});try{const page=await browser.newPage();await page.goto(server.url.href);await page.waitForFunction(()=>Object.hasOwn(window,'__symbols'));const result=await page.evaluate(()=>Reflect.get(window,'__symbols'));assert.deepEqual(result.names,result.expected);assert.deepEqual(result.mismatches,[]);assert.equal(result.identity,true);reports.push({engine,splitting,count:result.names.length,allNamesMatch:true,allValueOriginsMatch:true,definitionClassIdentity:true});console.log(engine,splitting?'split':'single',result.names.length,'symbol identities PASS');}finally{await browser.close();}}}finally{server.stop(true);}
}
await Bun.write(path.join(root,'.artifacts/m26-bundle/runtime-identity.json'),JSON.stringify({bun:Bun.version,reports},null,2)+'\n');
