// Generated by the style generator from the reference spec. Do not edit; edit the mapping and regenerate.
import { css } from "lit";
export const fieldsetCss = css`
  .fieldset {
    position: relative;
    overflow: hidden;
    background-color: var(--ds-background-100);
    box-shadow: var(--ds-shadow-border);
    border-radius: 6px;
    --acme-fieldset-title-color: var(--ds-gray-1000);
  }
  .fieldset :where(.content) {
    position: relative;
    border-top-left-radius: var(--acme-radius);
    border-top-right-radius: var(--acme-radius);
    background-color: var(--ds-background-100);
    padding: 1.25rem;
  }
  .fieldset :where(.footer) :where(.actions) :where(.action) {
    margin-inline: 0.5rem;
  }
  .fieldset :where(.content) :where(.row) {
    margin-top: 1rem;
  }
  .fieldset :where(.footer) :where(.actions) {
    margin-left: auto;
    display: flex;
    align-items: center;
    justify-content: flex-end;
  }
  .fieldset :where(.footer) :where(.status) {
    display: flex;
    max-width: 100%;
    align-items: center;
  }
  .fieldset :where(.content) :where(.title) {
    display: inline-flex;
    scroll-margin-top: 1.5rem;
    align-items: center;
    font-family: var(--acme-font-sans);
    font-size: 20px;
    line-height: 26px;
    font-weight: 600;
    letter-spacing: -0.4px;
    word-break: break-word;
    color: var(--acme-fieldset-title-color, var(--ds-gray-1000));
  }
  .fieldset:where(:is(.error, .warning)) {
    border-style: solid;
    border-width: 1px;
    box-shadow: none;
  }
  .fieldset:where(.warning) {
    border-color: var(--ds-amber-400);
  }
  .fieldset:where(.error) {
    border-color: var(--ds-red-400);
  }
  .fieldset:where(.highlight) :where(.footer) {
    background-color: var(--bg, #f5f5f5);
  }
  .fieldset :where(.footer) {
    position: relative;
    box-sizing: border-box;
    display: flex;
    min-height: 3.5rem;
    align-items: center;
    border-bottom-right-radius: 0.25rem;
    border-bottom-left-radius: 0.25rem;
    border-top-style: solid;
    border-top-width: 1px;
    border-color: var(--ds-gray-400);
    background-color: var(--ds-background-200);
    padding-top: 0.75rem;
    padding-right: 0.75rem;
    padding-bottom: 0.75rem;
    padding-left: 1.25rem;
    font-family: var(--acme-font-sans);
    font-size: 14px;
    line-height: 20px;
    font-weight: 400;
    color: var(--ds-gray-900);
  }
  .fieldset :where(.content) :where(.subtitle) {
    padding-top: 0.5rem;
    padding-bottom: 1.25rem;
    font-family: var(--acme-font-sans);
    font-size: 14px;
    line-height: 20px;
    font-weight: 400;
    color: var(--ds-gray-900);
  }
  .fieldset :where(.content) :where(.row) :where(.warning) {
    color: var(--ds-amber-900);
  }
  .fieldset:where(.disabled) :where(.content) {
    color: var(--ds-gray-700);
    --acme-foreground: var(--ds-gray-900);
    --ds-gray-1000: var(--ds-gray-900);
    --accents-8: var(--accents-5);
    --accents-7: var(--accents-5);
    --accents-6: var(--accents-4);
    --accents-5: var(--accents-4);
    --accents-4: var(--accents-3);
    --acme-link-color: var(--acme-foreground);
    --acme-success: var(--acme-foreground);
    --acme-success-dark: var(--acme-foreground);
    --acme-error: var(--acme-foreground);
    --acme-error-dark: var(--acme-foreground);
    --acme-warning: var(--acme-foreground);
    --acme-warning-dark: var(--acme-foreground);
    --acme-cyan: var(--acme-foreground);
    --acme-cyan-dark: var(--acme-foreground);
    --acme-violet: var(--acme-foreground);
    --acme-violet-dark: var(--acme-foreground);
    --acme-secondary: var(--acme-foreground);
    --acme-secondary-dark: var(--acme-foreground);
    --acme-code: var(--acme-foreground);
  }
  .fieldset :where(.content) :where(.row) :where(.error) {
    color: var(--ds-red-900);
  }
  @media (min-width: 401px) {
    .fieldset :where(.footer) :where(.actions) :where(.action) {
      width: 100%;
      text-align: center;
    }
    .fieldset :where(.footer) :where(.actions) {
      justify-content: space-between;
    }
  }
  .fieldset :where(.content) :where(.title) > slot::slotted(strong),
  .fieldset :where(.content) :where(.title) > slot > strong {
    font-weight: 500 !important;
    color: var(--ds-gray-900) !important;
  }
  .fieldset :where(.content) :where(.subtitle) > slot::slotted(strong),
  .fieldset :where(.content) :where(.subtitle) > slot > strong {
    color: var(--ds-gray-1000) !important;
    font-weight: 550 !important;
  }
  .fieldset :where(.footer) > slot::slotted(strong),
  .fieldset :where(.footer) > slot > strong {
    color: var(--ds-gray-1000) !important;
    font-weight: 550 !important;
  }
  .fieldset.error :where(.footer) {
    border-top-color: var(--ds-red-400);
    background-color: var(--ds-red-100);
    color: var(--ds-red-900);
  }
  .fieldset.warning :where(.footer) {
    border-top-color: var(--ds-amber-400);
    background-color: var(--ds-amber-100);
    color: var(--ds-amber-900);
  }
  .fieldset :where(.footer) :where(.actions) :where(.action):first-child {
    margin-left: 0;
  }
  .fieldset :where(.content):first-child {
    border-top-left-radius: 6px;
    border-top-right-radius: 6px;
  }
  .fieldset :where(.content) :where(.subtitle):first-child {
    padding-top: 0;
  }
  .fieldset :where(.footer) :where(.actions) :where(.action):last-child {
    margin-right: 0;
  }
  .fieldset :where(.content):last-child {
    border-bottom-right-radius: 6px;
    border-bottom-left-radius: 6px;
  }
  .fieldset :where(.content):has(> .subtitle:last-child) {
    padding-bottom: 0;
  }
  .fieldset:where(.disabled) :where(.content) slot::slotted(svg),
  .fieldset:where(.disabled) :where(.content) slot > svg {
    filter: grayscale() !important;
  }
  .fieldset:where(.disabled) :where(.content) slot::slotted(img),
  .fieldset:where(.disabled) :where(.content) slot > img {
    filter: grayscale() !important;
  }
  .fieldset:where(.disabled) :where(.content) :where(.title) {
    --acme-success: #0070f3;
    --acme-success-dark: #0761d1;
    --acme-error: #e00;
    --acme-error-dark: #c50000;
    --acme-warning: #f5a623;
    --acme-warning-dark: #ab570a;
    --acme-violet: #7928ca;
    --acme-violet-dark: #4c2889;
    --acme-violet-background: #fff;
    --acme-violet-background-secondary: #291c3a;
    --acme-violet-background-tertiary: #eae5f4;
    --acme-background: #fff;
    --acme-foreground: #000;
    --acme-console-header: #efe7ed;
    --acme-console-purple: #7928ca;
    --acme-console-text-color-default: var(--acme-foreground);
    --acme-console-text-color-blue: #0070f3;
    --acme-console-text-color-pink: #eb367f;
    --acme-console-text-color-purple: #7928ca;
    --acme-cyan: #50e3c2;
    --acme-cyan-dark: #29bc9b;
    --acme-highlight-purple: #f81ce5;
    --acme-highlight-magenta: #eb367f;
    --acme-highlight-pink: #ff0080;
    --acme-highlight-yellow: #fff500;
    --acme-selection: var(--ds-gray-1000);
    --acme-selection-text-color: var(--ds-gray-100);
    --accents-1: #fafafa;
    --accents-2: #eaeaea;
    --accents-3: #999;
    --accents-4: #888;
    --accents-5: #666;
    --accents-6: #444;
    --accents-7: #333;
    --accents-8: #111;
    --acme-link-color: var(--ds-blue-700);
    --acme-marketing-gray: #fafbfc;
    --acme-code: var(--acme-foreground);
    --acme-secondary: var(--accents-5);
    --acme-secondary-dark: var(--accents-7);
    --dropdown-box-shadow: 0 4px 4px 0 #00000005;
    --dropdown-triangle-stroke: #fff;
    --scroller-start: #fff;
    --scroller-end: #fff0;
    --shadow-smallest: 0px 2px 4px #0000001a;
    --shadow-extra-small: 0px 4px 8px #0000001f;
    --shadow-small: 0 5px 10px #0000001f;
    --shadow-medium: 0 8px 30px #0000001f;
    --shadow-large: 0 30px 60px #0000001f;
    --shadow-hover: 0 30px 60px #0000001f;
    --shadow-sticky: 0 12px 10px -10px #0000001f;
    --wv-green: #0cce6b;
    --wv-orange: #ffa400;
    --wv-red: #ff4e42;
    --develop-start-gradient: #007cf0;
    --develop-end-gradient: #00dfd8;
    --develop-line-end: #019ae9;
    --develop-text: #0a72ef;
    --preview-start-gradient: #7928ca;
    --preview-end-gradient: #ff0080;
    --preview-line-end: #9a1fb8;
    --preview-text: #de1d8d;
    --ship-start-gradient: #ff4d4d;
    --ship-end-gradient: #f9cb28;
    --ship-line-end: #f9cb28;
    --ship-text: #ff5b4f;
    --next-icon-border: #000;
    z-index: 2;
    position: relative;
  }
  @media (color-gamut: p3) {
    @supports (color: oklch(0% 0 0)) {
      .fieldset:where(.disabled) :where(.content) :where(.title) {
        --develop-start-gradient: oklch(59.59% 0.24 255.092);
        --develop-end-gradient: oklch(81.58% 0.189 190.74);
        --develop-line-end: oklch(65.84% 0.203 242.532);
        --develop-text: oklch(57.49% 0.249 257.84);
        --preview-start-gradient: oklch(49.07% 0.272 300.45);
        --preview-end-gradient: oklch(64.53% 0.292 2.47);
        --preview-line-end: oklch(51.39% 0.267 318.36);
        --preview-text: oklch(59.93% 0.274 352.55);
        --ship-start-gradient: oklch(67.3% 0.266 25.0397);
        --ship-end-gradient: oklch(85.82% 0.201 91.19);
        --ship-line-end: oklch(85.82% 0.201 91.19);
        --ship-text: oklch(68.79% 0.25 27.76);
      }
    }
  }
  .fieldset:where(.disabled) :where(.content) slot::slotted(acme-button),
  .fieldset:where(.disabled) :where(.content) slot > acme-button {
    --themed-border: var(--ds-gray-400) !important;
    --themed-bg: var(--ds-gray-100) !important;
    --themed-fg: var(--ds-gray-700) !important;
  }
  :where(:host([data-dark])) .fieldset:where(.disabled) :where(.content) :where(.title) {
    --acme-foreground: #fff;
    --acme-background: #000;
    --accents-8: #fafafa;
    --accents-7: #eaeaea;
    --accents-6: #999;
    --accents-5: #888;
    --accents-4: #666;
    --accents-3: #444;
    --accents-2: #333;
    --accents-1: #111;
    --acme-selection: var(--ds-gray-1000);
    --acme-selection-text-color: var(--ds-gray-100);
    --acme-secondary: var(--accents-5);
    --acme-secondary-dark: var(--accents-7);
    --acme-link-color: var(--ds-blue-900);
    --acme-marketing-gray: var(--accents-1);
    --acme-code: var(--acme-foreground);
    --acme-error: red;
    --acme-error-dark: #e60000;
    --acme-text-gradient: linear-gradient(180deg, #fff 0%, #ffffffbf 100%);
    --dropdown-box-shadow: 0 0 0 1px var(--accents-2);
    --dropdown-triangle-stroke: #333;
    --scroller-start: #000;
    --scroller-end: #0000;
    --header-border-bottom: 0 1px 0 0 #ffffff1a;
    --header-import-flow-background: #111c;
    --shadow-smallest: 0 0 0 1px var(--accents-2);
    --shadow-extra-small: 0 0 0 1px var(--accents-2);
    --shadow-small: 0 0 0 1px var(--accents-2);
    --shadow-medium: 0 0 0 1px var(--accents-2);
    --shadow-large: 0 0 0 1px var(--accents-2);
    --shadow-sticky: 0 0 0 1px var(--accents-2);
    --shadow-hover: 0 0 0 1px var(--acme-foreground);
    --acme-violet-background: #291d3a;
    --acme-violet-background-secondary: #211830;
    --acme-violet-background-tertiary: #211830;
    --acme-background-rgb: 0, 0, 0;
    --acme-foreground-rgb: 255, 255, 255;
    --acme-console-header: #0f0310;
    --acme-console-purple: #8a63d2;
    --acme-console-text-color-default: var(--acme-foreground);
    --acme-console-text-color-blue: #3291ff;
    --acme-console-text-color-pink: #eb367f;
    --next-icon-border: #fff;
    --ds-shadow-background-border: 0 0 0 1px var(--ds-background-200);
    --ds-shadow-border: var(--ds-shadow-border-base), var(--ds-shadow-background-border);
    --ds-shadow-2xs: 0px 1px 1px #00000029;
    --ds-shadow-xs: 0px 1px 2px #00000029;
    --ds-shadow-small: 0px 1px 2px #00000029;
    --ds-shadow-border-small: var(--ds-shadow-border-base), var(--ds-shadow-small), var(--ds-shadow-background-border);
    --ds-shadow-medium: 0px 2px 2px #00000052, 0px 8px 8px -8px #00000029;
    --ds-shadow-border-medium: var(--ds-shadow-border-base), var(--ds-shadow-medium), var(--ds-shadow-background-border);
    --ds-shadow-large: 0px 2px 2px #0000000a, 0px 8px 16px -4px #0000000a;
    --ds-shadow-border-large: var(--ds-shadow-border-base), var(--ds-shadow-large), var(--ds-shadow-background-border);
    --ds-shadow-xl: 0px 1px 1px #00000005, 0px 4px 8px -4px #0000000a, 0px 16px 24px -8px #0000000f;
    --ds-shadow-2xl: 0px 1px 1px #00000005, 0px 8px 16px -4px #0000000a, 0px 24px 32px -8px #0000000f;
    --ds-shadow-tooltip: var(--ds-shadow-border-base), 0px 1px 1px #00000005, 0px 4px 8px #0000000a, var(--ds-shadow-background-border);
    --ds-shadow-menu: var(--ds-shadow-border-base), 0px 1px 1px #00000005, 0px 4px 8px -4px #0000000a, 0px 16px 24px -8px #0000000f, var(--ds-shadow-background-border);
    --ds-shadow-modal: var(--ds-shadow-border-base), 0px 1px 1px #00000005, 0px 8px 16px -4px #0000000a, 0px 24px 32px -8px #0000000f, var(--ds-shadow-background-border);
    --ds-shadow-modal-elevated: 0 0 0 1px var(--ds-gray-alpha-400), 0px 32px 72px -12px #0000000f, 0px 8px 32px -12px #00000014, 0px 8px 24px -12px #0000001f;
    --ds-shadow-fullscreen: var(--ds-shadow-border-base), 0px 1px 1px #00000005, 0px 8px 16px -4px #0000000a, 0px 24px 32px -8px #0000000f, var(--ds-shadow-background-border);
    --ds-focus-ring: 0 0 0 2px var(--ds-background-100), 0 0 0 4px var(--ds-focus-color);
    --ds-overlay-backdrop-color: var(--ds-background-200);
  }
`;
