// Generated by scripts/split-css.ts from the audited house sheet. Do not edit.
import { css } from "lit";
export const tileCss = css`
  .tiles {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(104px, 1fr));
    gap: 8px;
  }
  .tile {
    background: var(--surface-2);
    border: 1px solid var(--hair);
    border-radius: var(--r);
    padding: 10px 12px;
    min-width: 0;
  }
  .tile .label {
    display: block;
    font-family: var(--mono);
    font-size: var(--t-3xs);
    text-transform: uppercase;
    letter-spacing: 0.09em;
    color: var(--text-2);
    line-height: 14px;
    margin-bottom: 4px;
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
  }
  .tile .value {
    display: block;
    font-family: var(--mono);
    font-size: var(--t-md);
    font-weight: 600;
    line-height: 20px;
    color: var(--text);
    font-variant-numeric: tabular-nums;
  }
  .tile.lg .value {
    font-size: var(--t-xl);
    line-height: 26px;
  }
  .tile.plain .label {
    font-family: var(--sans);
    font-size: 14px;
    line-height: 20px;
    text-transform: none;
    letter-spacing: 0;
    display: flex;
    align-items: center;
    gap: 8px;
    margin-bottom: 2px;
    overflow: visible;
    white-space: nowrap;
  }
  .tile.plain .label .q {
    flex: none;
  }
  .tiles:has(.tile.plain) {
    grid-template-columns: repeat(auto-fit, minmax(140px, 1fr));
  }
  .tile.plain .label .q {
    margin-left: auto;
    font-size: var(--t-xs);
    color: var(--text-2);
  }
  .tile.plain .value {
    font-size: 14px;
    line-height: 20px;
    font-weight: 500;
  }
  .tile.plain {
    background: var(--surface);
    box-shadow: var(--ds-shadow-border);
    border: 0;
  }
`;
