// Generated by scripts/split-css.ts from the audited house sheet. Do not edit.
import { css } from "lit";
export const calendarCss = css`
  .calendar {
    width: 280px;
    background: var(--surface);
    border-radius: var(--r-lg);
    box-shadow: var(--ds-shadow-menu);
    padding: 12px;
    display: flex;
    flex-direction: column;
    gap: 12px;
    color: var(--text);
  }
  .calendar[popover] {
    position: fixed;
    inset: auto;
    margin: 0;
    border: 0;
    overflow: visible;
    z-index: 30;
  }
  .calendar.sm {
    width: 252px;
    padding: 10px;
    gap: 10px;
  }
  .calendar.horizontal {
    width: auto;
    flex-direction: row;
    align-items: stretch;
  }
  .calendar.horizontal .cal-form {
    width: 220px;
    flex: none;
    padding: 0 12px 0 0;
    border-bottom: 0;
    border-right: 1px solid var(--border);
  }
  .calendar.horizontal .cal-main {
    width: 256px;
  }
  .calendar .cal-main {
    display: flex;
    flex-direction: column;
    gap: 12px;
    min-width: 0;
  }
  .calendar .cal-form {
    display: flex;
    flex-direction: column;
    gap: 8px;
    padding-bottom: 12px;
    border-bottom: 1px solid var(--border);
  }
  .calendar .cal-form .form-label {
    margin: 0;
  }
  .calendar .cal-form .field {
    margin: 0;
    display: flex;
    gap: 8px;
  }
  .calendar .cal-form .field input {
    height: var(--form-sm);
    flex: 1;
    min-width: 0;
  }
  .calendar .cal-form .field input.time {
    flex: 0 0 89px;
  }
  .calendar .cal-form .btn {
    height: var(--form-sm);
    width: 100%;
    gap: 8px;
  }
  .calendar .cal-form select,
  .calendar .cal-form .cal-tz {
    height: var(--form-sm);
    width: 100%;
    padding: 0 12px;
    border: 1px solid var(--border);
    border-radius: var(--r-sm);
    background: var(--surface);
    font-size: 13px;
    line-height: 20px;
    color: var(--text);
  }
  .calendar .cal-form .cal-tz {
    display: flex;
    align-items: center;
    background: var(--comp);
    color: var(--text-2);
    cursor: default;
  }
  .calendar .cal-form select {
    appearance: none;
    -webkit-appearance: none;
    padding-right: 32px;
    background-image: linear-gradient(45deg, transparent 50%, var(--text-2) 50%), linear-gradient(135deg, var(--text-2) 50%, transparent 50%);
    background-position:
      calc(100% - 16px) 50%,
      calc(100% - 12px) 50%;
    background-size: 4px 4px;
    background-repeat: no-repeat;
  }
  .cal-head {
    display: flex;
    align-items: center;
    gap: 4px;
  }
  .cal-head .month {
    flex: 1;
    font-size: 14px;
    line-height: 21px;
    font-weight: 500;
  }
  .cal-head .iconbtn {
    width: 30px;
    height: 30px;
    border: 0;
    background: transparent;
    border-radius: 50%;
  }
  .cal-head .iconbtn.next {
    width: 32px;
    height: 32px;
  }
  .cal-join {
    display: inline-flex;
    align-items: stretch;
    border: 1px solid var(--border);
    border-radius: var(--r-sm);
    background: var(--surface);
    vertical-align: middle;
  }
  .cal-join > .btn,
  .cal-join > .cal-period {
    border: 0;
    border-radius: 0;
    box-shadow: none;
    height: calc(var(--form) - 2px);
  }
  .cal-join.sm > .btn,
  .cal-join.sm > .cal-period {
    height: calc(var(--form-sm) - 2px);
  }
  .cal-join > :first-child {
    border-radius: 5px 0 0 5px;
  }
  .cal-join > :last-child {
    border-radius: 0 5px 5px 0;
  }
  .cal-join > * + * {
    border-left: 1px solid var(--border);
  }
  .cal-join.stacked {
    flex-direction: column;
    width: 280px;
  }
  .cal-join.stacked > .btn,
  .cal-join.stacked > .cal-period {
    width: 100%;
    justify-content: flex-start;
  }
  .cal-join.stacked > :first-child {
    border-radius: 5px 5px 0 0;
  }
  .cal-join.stacked > :last-child {
    border-radius: 0 0 5px 5px;
  }
  .cal-join.stacked > * + * {
    border-left: 0;
    border-top: 1px solid var(--border);
  }
  .cal-period {
    appearance: none;
    -webkit-appearance: none;
    height: var(--form);
    padding: 0 32px 0 12px;
    font-size: 14px;
    line-height: 20px;
    font-weight: 500;
    color: var(--text);
    background: var(--surface);
    cursor: pointer;
    background-image: linear-gradient(45deg, transparent 50%, var(--text-2) 50%), linear-gradient(135deg, var(--text-2) 50%, transparent 50%);
    background-position:
      calc(100% - 16px) 50%,
      calc(100% - 12px) 50%;
    background-size: 4px 4px;
    background-repeat: no-repeat;
  }
  .cal-period:hover {
    background-color: var(--comp);
  }
  .cal-clear {
    padding: 0 8px;
    color: var(--text-2);
  }
  .cal-clear:hover {
    color: var(--text);
  }
  .cal-trigger .ic {
    color: var(--text-2);
  }
  .cal-grid {
    width: 100%;
    border-collapse: collapse;
    table-layout: fixed;
  }
  .cal-grid th {
    height: 18px;
    font-size: 12px;
    line-height: 18px;
    font-weight: 400;
    text-transform: uppercase;
    color: var(--text-2);
    padding: 0 0 6px;
  }
  .cal-grid td {
    padding: 0;
    text-align: center;
  }
  .cal-grid td span {
    display: inline-grid;
    place-items: center;
    width: 32px;
    height: 32px;
    border-radius: 4px;
    font-size: 14px;
    line-height: 30px;
    color: var(--text);
    cursor: pointer;
    border: 1px solid transparent;
  }
  .cal-grid td span:hover {
    background: var(--comp);
  }
  .cal-grid td.out span {
    color: var(--text-2);
  }
  .cal-grid td.far span {
    color: var(--ds-gray-700);
  }
  .cal-grid td.range span {
    background: var(--ds-blue-100);
    color: var(--ds-blue-900);
    border-radius: 0;
  }
  .cal-grid td.start span,
  .cal-grid td.end span,
  .cal-grid td.selected span {
    background: var(--accent-ink);
    color: var(--ds-background-100);
    border-radius: 4px;
  }
  .cal-grid td.today span {
    border-color: var(--border-active);
  }
  .cal-grid td[aria-disabled="true"] span {
    color: var(--ds-gray-500);
    cursor: not-allowed;
  }
  .cal-grid td span:focus-visible {
    box-shadow: var(--ring);
    outline: none;
  }
  .calendar.sm .cal-grid td span {
    width: 28px;
    height: 28px;
    font-size: 13px;
    line-height: 26px;
  }
  .cal-presets {
    display: flex;
    flex-wrap: wrap;
    gap: 8px;
  }
  .cal-presets .btn {
    height: var(--form-sm);
    padding: 0 10px;
    font-size: 13px;
  }
  .cal-presets .btn[aria-pressed="true"] {
    background: var(--comp);
    border-color: var(--border-hover);
  }
`;
