// Generated by scripts/split-css.ts from the audited house sheet. Do not edit.
import { css } from "lit";
export const planCss = css`
  .plan-head {
    display: flex;
    align-items: center;
    gap: 12px;
    flex-wrap: wrap;
    margin-bottom: 16px;
  }
  .plan-head .title {
    font-size: 24px;
    line-height: 32px;
    letter-spacing: -0.96px;
    font-weight: 600;
  }
  .plan-head .range {
    margin-left: auto;
    font-size: 14px;
    color: var(--text-2);
  }
  .plan-head .actions {
    display: flex;
    gap: 8px;
  }
  .icon-rows {
    border-radius: var(--r-sm);
    border: 1px solid var(--border);
    overflow: hidden;
  }
  .icon-row {
    display: flex;
    align-items: center;
    gap: 16px;
    padding: 16px 20px;
    border-bottom: 1px solid var(--border);
    background: var(--surface);
  }
  .icon-row:last-child {
    border-bottom: 0;
  }
  .icon-row.tinted {
    background: var(--surface-2);
  }
  .icon-row .ricon {
    width: 40px;
    height: 40px;
    background: var(--surface);
    border: 1px solid var(--border);
    color: var(--text-2);
  }
  .icon-row .ricon.hue-blue {
    color: var(--ds-blue-700);
    background: var(--surface);
    border-color: var(--ds-blue-400);
  }
  .icon-row .label {
    font-size: 14px;
    line-height: 20px;
    color: var(--text-2);
  }
  .icon-row .value {
    font-size: 16px;
    line-height: 24px;
    font-weight: 500;
    font-variant-numeric: tabular-nums;
  }
  .icon-row .end {
    margin-left: auto;
    display: flex;
    align-items: center;
    gap: 8px;
    flex-wrap: wrap;
    justify-content: flex-end;
    color: var(--text-2);
    font-size: 14px;
  }
  .icon-row .bar {
    flex: 1 1 100%;
    height: 10px;
    border-radius: 999px;
    background: var(--ds-gray-200);
    overflow: hidden;
    margin-top: -4px;
  }
  .icon-row .bar i {
    display: block;
    height: 100%;
    background: var(--ds-blue-700);
    border-radius: 999px;
  }
  .icon-row.wrap {
    flex-wrap: wrap;
  }
  .section-title {
    font-size: 16px;
    line-height: 24px;
    letter-spacing: -0.32px;
    font-weight: 600;
    margin: 24px 0 8px;
  }
  .section-title + .desc {
    font-size: 14px;
    line-height: 20px;
    color: var(--text-2);
    margin: 0 0 12px;
  }
  .section-title + .desc a {
    color: var(--accent-ink);
  }
`;
