// Generated by scripts/split-css.ts from the audited house sheet. Do not edit.
import { css } from "lit";
export const railCss = css`
.with-rail{display:grid;grid-template-columns:minmax(0,1fr) 300px;gap:var(--s-4);align-items:start}
.rail{display:flex;flex-direction:column;gap:var(--s-4);position:sticky;top:calc(var(--bar-h) + 16px)}
@media (max-width:900px){
  .with-rail{grid-template-columns:minmax(0,1fr)}
  .rail{position:static}
}
`;
