import { numericTokenKeys, numericTokenProperty, type NumericTokenCategory, type NumericTokenKey } from "./numeric-tokens";

export const themeTokenCategories = Object.freeze(["colors", "fonts", "fontSizes", "fontWeights", "lineHeights", "spacing", "sizes", "radii", "shadows", "motion"] as const);
export type ThemeTokenCategory = (typeof themeTokenCategories)[number];
export type ThemeTokenSyntax =
  | "color"
  | "font-family"
  | "font-size"
  | "font-weight"
  | "line-height"
  | "padding"
  | "margin"
  | "width"
  | "border-radius"
  | "box-shadow"
  | "transition-duration"
  | "transition-timing-function"
  | "scale-factor"
  | "gap"
  | "padding-block"
  | "padding-inline";

function named<const Category extends ThemeTokenCategory, const Keys extends readonly string[]>(category: Category, keys: Keys, syntax: ThemeTokenSyntax, role: string) {
  return Object.freeze(keys.map((key) => Object.freeze({ category, key: key as Keys[number], cssProperty: ("--" + key) as `--${Keys[number]}`, syntax, role })));
}
function numeric<const Category extends NumericTokenCategory>(category: Category) {
  return Object.freeze(
    numericTokenKeys.map((key) =>
      Object.freeze({
        category,
        key: String(key) as `${NumericTokenKey}`,
        cssProperty: numericTokenProperty(category, key),
        syntax: (category === "spacing" ? "padding" : "width") as ThemeTokenSyntax,
        role: category === "spacing" ? "numeric spacing" : "numeric dimension",
      }),
    ),
  );
}

// These defaults correspond to the numeric weights used by the authored and mapped styles.
export const fontWeightTokenDefinitions = Object.freeze(
  ([400, 450, 500, 550, 600, 700] as const).map((weight) =>
    Object.freeze({
      category: "fontWeights" as const,
      key: `acme-font-weight-${weight}` as const,
      cssProperty: `--acme-font-weight-${weight}` as const,
      syntax: "font-weight" as const,
      role: "numeric typography weight",
      defaultValue: String(weight),
    }),
  ),
);
export const densityTokenDefinitions = Object.freeze(
  (
    [
      {
        category: "spacing",
        key: "acme-layout-gap-2",
        cssProperty: "--acme-layout-gap-2",
        syntax: "gap",
        role: "compact eligible layout gap at spacing step 2",
        defaultValue: "0.5rem",
        compactValue: "0.375rem",
      },
      {
        category: "spacing",
        key: "acme-layout-gap-4",
        cssProperty: "--acme-layout-gap-4",
        syntax: "gap",
        role: "compact eligible layout gap at spacing step 4",
        defaultValue: "1rem",
        compactValue: "0.75rem",
      },
      {
        category: "spacing",
        key: "acme-table-padding-block",
        cssProperty: "--acme-table-padding-block",
        syntax: "padding-block",
        role: "table cell block padding",
        defaultValue: "0.625rem",
        compactValue: "0.3125rem",
      },
      {
        category: "spacing",
        key: "acme-table-padding-inline",
        cssProperty: "--acme-table-padding-inline",
        syntax: "padding-inline",
        role: "table cell inline padding",
        defaultValue: "0.5rem",
        compactValue: "0.5rem",
      },
    ] as const
  ).map((token) => Object.freeze(token)),
);

export const themeTokenDefinitions = Object.freeze([
  ...named(
    "colors",
    [
      "accent",
      "accent-border",
      "accent-hover",
      "accent-ink",
      "accent-weak",
      "accents-1",
      "accents-2",
      "accents-3",
      "accents-4",
      "accents-5",
      "accents-6",
      "accents-7",
      "accents-8",
      "acme-background",
      "acme-code",
      "acme-console-header",
      "acme-console-purple",
      "acme-console-text-color-blue",
      "acme-console-text-color-default",
      "acme-console-text-color-pink",
      "acme-console-text-color-purple",
      "acme-cyan",
      "acme-cyan-dark",
      "acme-cyan-light",
      "acme-cyan-lighter",
      "acme-error",
      "acme-error-dark",
      "acme-error-light",
      "acme-error-lighter",
      "acme-foreground",
      "acme-highlight-magenta",
      "acme-highlight-pink",
      "acme-highlight-purple",
      "acme-highlight-yellow",
      "acme-link-color",
      "acme-marketing-gray",
      "acme-secondary",
      "acme-secondary-dark",
      "acme-secondary-light",
      "acme-secondary-lighter",
      "acme-selection",
      "acme-selection-text-color",
      "acme-success",
      "acme-success-dark",
      "acme-success-light",
      "acme-success-lighter",
      "acme-violet",
      "acme-violet-background",
      "acme-violet-background-secondary",
      "acme-violet-background-tertiary",
      "acme-violet-dark",
      "acme-violet-light",
      "acme-violet-lighter",
      "acme-warning",
      "acme-warning-dark",
      "acme-warning-light",
      "acme-warning-lighter",
      "bg",
      "border",
      "border-active",
      "border-hover",
      "caution",
      "caution-bg",
      "caution-border",
      "caution-solid",
      "caution-weak",
      "color-gray-200",
      "color-gray-950",
      "color-indigo-600",
      "comp",
      "comp-active",
      "comp-hover",
      "contrast",
      "contrast-hover",
      "contrast-strong",
      "contrast-strong-hover",
      "ds-contrast-fg",
      "ds-focus-color",
      "ds-overlay-backdrop-color",
      "faint",
      "hair",
      "highlight",
      "muted",
      "on-contrast",
      "on-warn",
      "scrim",
      "scrim-dark",
      "seg-active",
      "seg-track",
      "success",
      "success-border",
      "success-ink",
      "success-weak",
      "surface",
      "surface-2",
      "surface-3",
      "switch-active",
      "switch-track",
      "text",
      "text-2",
      "track",
      "warn",
      "warn-border",
      "warn-hover",
      "warn-ink",
      "warn-solid",
      "warn-solid-hover",
      "warn-weak",
    ] as const,
    "color",
    "semantic or reference color role",
  ),
  ...named("fonts", ["acme-font-mono", "acme-font-sans", "font-mono-fallback", "font-sans-fallback"] as const, "font-family", "font family or fallback stack"),
  ...named("fontSizes", ["acme-form-font", "acme-form-large-font", "acme-form-small-font", "acme-form-tiny-font"] as const, "font-size", "control text size"),
  ...named(
    "sizes",
    [
      "acme-form-height",
      "acme-form-large-height",
      "acme-form-small-height",
      "acme-form-tiny-height",
      "acme-space-large",
      "acme-space-medium",
      "acme-space-small",
      "ds-control-decoration-size",
      "ds-size-large",
      "ds-size-medium",
      "ds-size-small",
      "form",
      "form-lg",
      "form-sm",
    ] as const,
    "width",
    "named control dimension",
  ),
  ...named("lineHeights", ["acme-form-large-line-height", "acme-form-line-height", "acme-form-small-line-height", "acme-form-tiny-line-height"] as const, "line-height", "control line height"),
  ...named(
    "spacing",
    ["acme-gap", "acme-gap-double", "acme-gap-half", "acme-gap-quarter", "acme-gap-section", "acme-page-margin", "acme-space-gap", "acme-space-gap-half", "acme-space-gap-quarter", "gap"] as const,
    "padding",
    "role gap or offset",
  ),
  ...named(
    "spacing",
    [
      "acme-gap-double-negative",
      "acme-gap-half-negative",
      "acme-gap-negative",
      "acme-gap-quarter-negative",
      "acme-space-gap-half-negative",
      "acme-space-gap-negative",
      "acme-space-gap-quarter-negative",
      "acme-space-large-negative",
      "acme-space-medium-negative",
      "acme-space-small-negative",
    ] as const,
    "margin",
    "signed role offset",
  ),
  ...named("radii", ["acme-marketing-radius", "acme-radius", "r", "r-lg", "r-sm"] as const, "border-radius", "surface or control corner"),
  ...named(
    "sizes",
    ["acme-page-width", "acme-page-width-with-margin", "bar-h", "ds-page-width", "ds-page-width-with-margin", "ds-popover-row-height", "page-width", "sidebar-w", "topbar-h"] as const,
    "width",
    "layout or surface dimension",
  ),
  ...named("colors", ["chart-1", "chart-2", "chart-3", "chart-4", "chart-5"] as const, "color", "chart series color"),
  ...named(
    "colors",
    [
      "ds-amber-100",
      "ds-amber-1000",
      "ds-amber-200",
      "ds-amber-300",
      "ds-amber-400",
      "ds-amber-500",
      "ds-amber-600",
      "ds-amber-700",
      "ds-amber-800",
      "ds-amber-900",
      "ds-background-100",
      "ds-background-200",
      "ds-black",
      "ds-blue-100",
      "ds-blue-1000",
      "ds-blue-200",
      "ds-blue-300",
      "ds-blue-400",
      "ds-blue-500",
      "ds-blue-600",
      "ds-blue-700",
      "ds-blue-800",
      "ds-blue-900",
      "ds-gray-100",
      "ds-gray-1000",
      "ds-gray-200",
      "ds-gray-300",
      "ds-gray-400",
      "ds-gray-500",
      "ds-gray-600",
      "ds-gray-700",
      "ds-gray-800",
      "ds-gray-900",
      "ds-gray-alpha-100",
      "ds-gray-alpha-1000",
      "ds-gray-alpha-200",
      "ds-gray-alpha-300",
      "ds-gray-alpha-400",
      "ds-gray-alpha-500",
      "ds-gray-alpha-600",
      "ds-gray-alpha-700",
      "ds-gray-alpha-800",
      "ds-gray-alpha-900",
      "ds-green-100",
      "ds-green-1000",
      "ds-green-200",
      "ds-green-300",
      "ds-green-400",
      "ds-green-500",
      "ds-green-600",
      "ds-green-700",
      "ds-green-800",
      "ds-green-900",
      "ds-pink-100",
      "ds-pink-1000",
      "ds-pink-200",
      "ds-pink-300",
      "ds-pink-400",
      "ds-pink-500",
      "ds-pink-600",
      "ds-pink-700",
      "ds-pink-800",
      "ds-pink-900",
      "ds-purple-100",
      "ds-purple-1000",
      "ds-purple-200",
      "ds-purple-300",
      "ds-purple-400",
      "ds-purple-500",
      "ds-purple-600",
      "ds-purple-700",
      "ds-purple-800",
      "ds-purple-900",
      "ds-red-100",
      "ds-red-1000",
      "ds-red-200",
      "ds-red-300",
      "ds-red-400",
      "ds-red-500",
      "ds-red-600",
      "ds-red-700",
      "ds-red-800",
      "ds-red-900",
      "ds-teal-100",
      "ds-teal-1000",
      "ds-teal-200",
      "ds-teal-300",
      "ds-teal-400",
      "ds-teal-500",
      "ds-teal-600",
      "ds-teal-700",
      "ds-teal-800",
      "ds-teal-900",
      "ds-white",
    ] as const,
    "color",
    "palette entry",
  ),
  ...named("shadows", ["ds-focus-border", "ds-focus-ring", "ring"] as const, "box-shadow", "focus treatment"),
  ...named("motion", ["ds-motion-overlay-duration", "ds-motion-popover-duration", "dur"] as const, "transition-duration", "transition duration"),
  ...named("motion", ["ds-motion-overlay-scale"] as const, "scale-factor", "overlay entry scale"),
  ...named("motion", ["ds-motion-overlay-timing", "ds-motion-popover-timing", "ds-motion-timing-swift", "ease"] as const, "transition-timing-function", "transition easing"),
  ...named(
    "spacing",
    ["ds-popover-padding", "ds-popover-row-padding", "pad-card", "pad-cell", "pad-cell-x", "pad-cell-y", "pad-modal", "pad-modal-body", "pad-row"] as const,
    "padding",
    "role padding",
  ),
  ...named("radii", ["ds-popover-row-radius"] as const, "border-radius", "menu row corner"),
  ...named(
    "shadows",
    [
      "ds-shadow-2xl",
      "ds-shadow-2xs",
      "ds-shadow-background-border",
      "ds-shadow-border",
      "ds-shadow-border-base",
      "ds-shadow-border-inset",
      "ds-shadow-border-large",
      "ds-shadow-border-medium",
      "ds-shadow-border-small",
      "ds-shadow-fullscreen",
      "ds-shadow-large",
      "ds-shadow-medium",
      "ds-shadow-menu",
      "ds-shadow-modal",
      "ds-shadow-modal-elevated",
      "ds-shadow-small",
      "ds-shadow-tooltip",
      "ds-shadow-xl",
      "ds-shadow-xs",
      "shadow",
      "shadow-extra-small",
      "shadow-hover",
      "shadow-large",
      "shadow-lg",
      "shadow-medium",
      "shadow-small",
      "shadow-smallest",
      "shadow-sticky",
    ] as const,
    "box-shadow",
    "surface elevation or border shadow",
  ),
  ...named("colors", ["mac-amber", "mac-green", "mac-red", "st-building", "st-error", "st-online", "st-queued", "st-ready"] as const, "color", "named status or chrome color"),
  ...named("fontSizes", ["t-2xl", "t-2xs", "t-3xl", "t-3xs", "t-lg", "t-md", "t-sm", "t-xl", "t-xs"] as const, "font-size", "house text size"),
  ...numeric("spacing"),
  ...numeric("sizes"),
  ...fontWeightTokenDefinitions,
  ...densityTokenDefinitions,
]);
export type ThemeTokenDefinition = (typeof themeTokenDefinitions)[number];
export type ThemeTokenKey<Category extends ThemeTokenCategory> = Extract<ThemeTokenDefinition, { category: Category }>["key"];
export type ThemeDefinition = { readonly [Category in ThemeTokenCategory]?: Readonly<Partial<Record<ThemeTokenKey<Category>, string>>> };

/** Validated override declarations belong in an owned stylesheet, below ordinary author CSS. */
export const themeOverrideSelector = ":host";
