// Generated by scripts/split-css.ts from the audited house sheet. Do not edit.
import { css } from "lit";
export const collapseCss = css`
details.collapse{border-top:1px solid var(--border);border-bottom:1px solid var(--border)}
details.collapse + details.collapse{border-top:0}
details.collapse summary{list-style:none;cursor:pointer;display:flex;align-items:center;gap:8px;padding:12px 0;font-size:16px;line-height:24px;font-weight:500}
details.collapse.lg summary{padding:24px 0;font-size:24px;line-height:36px;font-weight:600;letter-spacing:-.96px}
details.collapse.lg .collapse-b{font-size:16px;line-height:24px;color:var(--text);padding-bottom:24px}
details.collapse summary::-webkit-details-marker{display:none}
details.collapse summary::after{content:"";width:8px;height:8px;border-right:1.5px solid var(--text-2);border-bottom:1.5px solid var(--text-2);transform:rotate(45deg);margin-left:auto;transition:transform var(--dur) var(--ease)}
details.collapse[open] summary::after{transform:rotate(-135deg)}
details.collapse .collapse-b{padding:0 0 12px;color:var(--text);font-size:14px;line-height:20px}
`;
