// Generated by the style generator from the reference spec. Do not edit; edit the mapping and regenerate.
import { css } from "lit";
export const modalCss = css`
  .modal:where(.sheet) {
    pointer-events: auto;
    max-height: 90dvh;
    width: 100%;
    translate: 0 var(--drawer-swipe-movement-y, 0px);
    border-top-left-radius: 0.75rem;
    border-top-right-radius: 0.75rem;
    border-top-style: solid;
    border-top-width: 1px;
    border-color: var(--ds-gray-alpha-400);
    background-color: var(--ds-background-100);
    transition-property: transform, translate, scale, rotate;
    transition-timing-function: cubic-bezier(0.32, 0.72, 0, 1);
    transition-duration: 0.4s;
    outline-style: none;
    animation-duration: 0.4s;
    animation-timing-function: cubic-bezier(0.32, 0.72, 0, 1);
  }
  .modal :where(.body) :where(.probe-top) {
    pointer-events: none;
    position: absolute;
    top: 0;
    height: 1px;
    width: 100%;
  }
  .modal :where(.body) :where(.probe-bottom) {
    pointer-events: none;
    height: 1px;
    width: 100%;
  }
  .modal:where(:not(.sticky)) :where(.fade-wrap) :where(.fade) {
    pointer-events: none;
    position: absolute;
    top: 0;
    left: 0;
    height: 1.5rem;
    width: 100%;
    border-top-left-radius: 0.75rem;
    border-top-right-radius: 0.75rem;
    background-image: linear-gradient(180deg, var(--ds-background-100) 25%, #fff0 100%);
  }
  .modal :where(.body) {
    position: relative;
    overflow-x: hidden;
    border-top-left-radius: var(--modal-radius);
    border-top-right-radius: var(--modal-radius);
    padding: 0;
    font-family: var(--acme-font-sans);
    font-size: 14px;
    line-height: 20px;
    font-weight: 400;
    color: var(--ds-gray-900);
  }
  .modal:where(.sticky) {
    position: sticky;
  }
  .modal :where(.actions) {
    position: sticky;
    bottom: 0;
    display: flex;
    flex-shrink: 0;
    justify-content: space-between;
    padding: 0.75rem;
  }
  .modal :where(.body) :where(.content) :where(.header) {
    z-index: 10;
    margin-bottom: 1.25rem;
    color: var(--ds-gray-1000);
  }
  .modal :where(.body) :where(.content) :where(.header) :where(.subtitle) {
    margin-top: 0.5rem;
    margin-bottom: 0.25rem;
    font-family: var(--acme-font-sans);
    font-size: 14px;
    line-height: 20px;
    font-weight: 400;
    color: var(--ds-gray-900);
  }
  .modal:where(:not(.sheet)) {
    display: flex;
    max-height: min(800px, 80vh);
    max-width: 100%;
    flex-direction: column;
    border-radius: 0.75rem;
    background-color: var(--ds-background-100);
    color: var(--ds-gray-1000);
    box-shadow: var(--ds-shadow-modal-elevated);
    transition-property: opacity, transform;
    transition-timing-function: var(--ds-motion-overlay-timing);
    transition-duration: var(--ds-motion-overlay-duration);
    --modal-padding: 24px;
    animation-duration: var(--ds-motion-overlay-duration);
    animation-timing-function: var(--ds-motion-overlay-timing);
  }
  .modal:where(.sticky) :where(.fade-wrap) :where(.fade) {
    display: none;
  }
  .modal:where(.noscroll) {
    overflow: hidden;
  }
  .modal:where(.overflow) {
    overflow: visible;
  }
  .modal:where(:not(.noscroll)) {
    overflow-y: auto;
  }
  .modal:where(:not(.unpadded)) :where(.body) {
    padding: var(--modal-padding);
    padding-top: 1.25rem;
    --modal-padding: 20px;
  }
  .modal:where(.center) :where(.body) :where(.content) :where(.header) :where(.title) {
    text-align: center;
  }
  .modal:where(:not(.center)) :where(.body) :where(.content) :where(.header) :where(.title) {
    text-align: left;
  }
  .modal :where(.body) :where(.content) :where(.header) :where(.title) {
    font-family: var(--acme-font-sans);
    font-size: 20px;
    line-height: 26px;
    font-weight: 600;
    letter-spacing: -0.4px;
    color: var(--ds-gray-1000);
  }
  @media not all and (min-width: 540px) {
    .modal:where(:not(.sheet)) {
      max-width: calc(100vw - 20px);
    }
  }
  @media (min-width: 401px) {
    .modal:where(:not(.sheet)) {
      overflow: hidden;
    }
    .modal :where(.body) {
      overflow-y: auto;
    }
  }
  :where(:host([data-dark])) .modal:where(:not(.unpadded)) :where(.body) {
    background-color: var(--ds-background-200);
  }
  .modal :where(.body) :where(.content) :where(.header) :where(.title) > strong {
    font-weight: 500;
    color: var(--ds-gray-900);
  }
  .modal :where(.body) > strong {
    color: var(--ds-gray-1000);
    font-weight: 550;
  }
  .modal :where(.body) :where(.content) :where(.header) :where(.subtitle) > strong {
    color: var(--ds-gray-1000);
    font-weight: 550;
  }
  .modal :where(.actions) > slot::slotted(div),
  .modal :where(.actions) > slot > div {
    display: flex !important;
    gap: 1rem !important;
  }
  .modal:where(:not(.sheet)) > form {
    overflow-x: hidden;
    overflow-y: auto;
    border-radius: 0.75rem;
  }
  .modal :where(.actions):before {
    content: "";
    position: absolute;
    bottom: 100%;
    left: 0;
    z-index: calc(10 * -1);
    height: 0.75rem;
    width: 100%;
    translate: 0 275%;
    background-color: var(--ds-black);
    filter: blur(3px);
    transition-property: transform, translate, scale, rotate;
    transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1);
    transition-duration: 0.2s;
    animation-duration: 0.2s;
  }
  @supports (color: color-mix(in lab, red, red)) {
    .modal :where(.actions):before {
      background-color: color-mix(in oklab, var(--ds-black) 7.5%, transparent);
    }
  }
  .modal[data-bottom-hidden] :where(.actions):before {
    content: "";
    translate: 0 75%;
  }
  .modal :where(.actions):after {
    content: "";
    position: absolute;
    inset: 0;
    z-index: calc(10 * -1);
    border-radius: 0;
    background-color: var(--ds-background-200);
    box-shadow: 0 -1px 0 0 var(--ds-gray-alpha-400);
  }
  .modal :where(.body) :where(.content) :where(.header)[data-last] {
    margin-bottom: 0;
  }
  .modal:where(.sheet)[data-ending-style] {
    translate: 0 100%;
  }
  .modal:where(.sheet)[data-starting-style] {
    translate: 0 100%;
  }
  @media (min-width: 401px) {
    .modal :where(.actions):after {
      border-bottom-right-radius: 0.75rem;
      border-bottom-left-radius: 0.75rem;
    }
  }
  :where(:host([data-dark])) .modal :where(.actions):before {
    content: "";
    background-color: var(--ds-white);
  }
  @supports (color: color-mix(in lab, red, red)) {
    :where(:host([data-dark])) .modal :where(.actions):before {
      background-color: color-mix(in oklab, var(--ds-white) 10%, transparent);
    }
  }
  .modal:where(.sticky) :where(.body) :where(.content) :where(.header) {
    position: sticky;
    top: 0;
    margin-right: calc(calc(var(--modal-padding)) * -1);
    margin-left: calc(calc(var(--modal-padding)) * -1);
    display: flex;
    align-items: center;
    justify-content: flex-start;
    gap: 0.625rem;
    padding-inline: 1.5rem;
    padding-block: 1rem;
  }
  .modal:where(.sticky) :where(.body) :where(.content) :where(.header) :where(.title) {
    display: block;
    padding-bottom: 0;
    font-size: 1rem;
    line-height: 1.5rem;
  }
  @media not all and (min-width: 401px) {
    .modal:where(.sticky) :where(.body) :where(.content) :where(.header) {
      font-size: 1rem;
      line-height: 1.5;
    }
  }
  @media (min-width: 401px) {
    .modal:where(.sticky) :where(.body) :where(.content) :where(.header) {
      padding-inline: var(--modal-padding);
      padding-block: 1.25rem;
    }
    .modal:where(.sticky) :where(.body) {
      padding-top: 0 !important;
    }
    .modal:where(.sticky) :where(.body) :where(.content) :where(.header) :where(.title) {
      font-size: 1.25rem !important;
      line-height: 1.5rem !important;
    }
  }
  .modal:where(.sticky) :where(.body) :where(.content) :where(.header):before {
    content: "";
    position: absolute;
    top: 100%;
    left: 0;
    z-index: calc(10 * -1);
    height: 0.75rem;
    width: 100%;
    translate: 0 calc(calc(3 / 4 * 100%) * -1);
    background-color: var(--ds-black);
    opacity: 0;
    filter: blur(3px);
    transition-property: opacity;
    transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1);
    transition-duration: 0.2s;
    animation-duration: 0.2s;
  }
  @supports (color: color-mix(in lab, red, red)) {
    .modal:where(.sticky) :where(.body) :where(.content) :where(.header):before {
      background-color: color-mix(in oklab, var(--ds-black) 7.5%, transparent);
    }
  }
  .modal:where(.sticky)[data-top-hidden] :where(.body) :where(.content) :where(.header):before {
    content: "";
    opacity: 1;
  }
  .modal:where(.sticky) :where(.body) :where(.content) :where(.header):after {
    content: "";
    position: absolute;
    inset: 0;
    z-index: calc(1 * -1);
    background-color: var(--ds-background-200);
    box-shadow: 0 0 0 1px var(--ds-gray-alpha-400);
  }
  :where(:host([data-dark])) .modal:where(.sticky) :where(.body) :where(.content) :where(.header):before {
    content: "";
    background-color: var(--ds-white);
  }
  @supports (color: color-mix(in lab, red, red)) {
    :where(:host([data-dark])) .modal:where(.sticky) :where(.body) :where(.content) :where(.header):before {
      background-color: color-mix(in oklab, var(--ds-white) 10%, transparent);
    }
  }
  :where(:host([data-dark])) .modal:where(.sticky) :where(.body) :where(.content) :where(.header):after {
    content: "";
    background-color: var(--ds-background-100);
  }
`;
