import assert from 'node:assert/strict';
const dir='/tmp/acme-m20-flow',root='/Users/peterkloss/Dev/ACMElabs/design-system';
const build=await Bun.build({entrypoints:[dir+'/candidate.ts'],outdir:dir+'/component-bundle',target:'browser',format:'esm',splitting:true});if(!build.success)throw new AggregateError(build.logs);
const server=Bun.serve({port:0,fetch(req){const path=new URL(req.url).pathname;const file=path==='/elk-worker.js'?root+'/node_modules/elkjs/lib/elk-worker.min.js':path==='/tokens.css'?root+'/src/generated/css/document/tokens.css':path.endsWith('.js')?dir+'/component-bundle'+path:undefined;if(path==='/missing-worker.js')return new Response('Missing',{status:404});return file?new Response(Bun.file(file),{headers:{'Content-Type':path.endsWith('.css')?'text/css':'text/javascript'}}):new Response('<!doctype html><link rel="stylesheet" href="/tokens.css"><script type="module" src="/candidate.js"></script>',{headers:{'Content-Type':'text/html'}})}});
process.env.PLAYWRIGHT_BROWSERS_PATH='/Users/peterkloss/Library/Caches/acme-design-system/browser-checks/browsers';const pw=await import('/Users/peterkloss/Library/Caches/acme-design-system/browser-checks/node_modules/playwright/index.mjs');const reports=[];
try{for(const engine of ['firefox']){const browser=await pw[engine].launch(engine==='chromium'?{executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true}:{headless:true});const page=await browser.newPage({reducedMotion:'reduce',viewport:{width:1280,height:900}});page.setDefaultTimeout(8000);const errors=[],checks=[];page.on('pageerror',e=>errors.push(String(e)));const check=async(name,run)=>{try{await page.goto(server.url.href+'?case='+checks.length);await page.waitForFunction(()=>document.querySelector('#flow')?.shadowRoot.querySelectorAll('[part=edge]').length===6);await run();checks.push({name,pass:true});console.log(engine,'PASS',name)}catch(error){checks.push({name,pass:false,error:String(error),state:await page.evaluate(()=>({failures:window.failures,body:document.body.textContent,shadow:window.flow?.shadowRoot?.textContent?.slice(-500)})).catch(error=>String(error))});console.log(engine,'FAIL',name,String(error))}};
await check('real worker renders measured custom nodes and routed edges',async()=>{assert.equal(await page.evaluate(()=>window.workers),1);assert.equal(await page.locator('[data-arrow]').count(),6);assert.equal(await page.locator('[data-flow-fallback]').count(),5);await page.screenshot({path:dir+'/'+engine+'-flow.png'});assert.equal(await page.locator('acme-flow-node').isVisible(),true)});
await check('custom controls retain DOM, focus and values after layout',async()=>{await page.locator('#draft').fill('Preserved');await page.locator('#draft').focus();await page.evaluate(async()=>{window.saved=document.querySelector('#draft');window.flow.direction='down';await window.flow.layout()});assert.equal(await page.evaluate(()=>window.saved===document.querySelector('#draft')),true);assert.equal(await page.locator('#draft').inputValue(),'Preserved');assert.equal(await page.locator('#draft').evaluate(el=>el===document.activeElement),true);await page.evaluate(()=>window.flow.fit());await page.getByRole('button',{name:'Inside action',exact:true}).click();assert.equal(await page.evaluate(()=>window.inside),1);assert.equal(await page.evaluate(()=>window.requests.length),0)});
await check('node activation and keyboard viewport controls have distinct events',async()=>{await page.getByRole('button',{name:'Step 0',exact:true}).click();assert.deepEqual(await page.evaluate(()=>window.requests[0]),{action:'node',id:'n0'});const before=await page.evaluate(()=>window.flow.zoom);await page.getByRole('button',{name:'Zoom in',exact:true}).click();assert.ok(await page.evaluate(()=>window.flow.zoom)>before);assert.equal(await page.evaluate(()=>window.changes.length),1);await page.locator('[part=background]').focus();await page.keyboard.press('ArrowRight');assert.equal(await page.evaluate(()=>window.changes.length),2);await page.getByRole('button',{name:'View relationships',exact:true}).click();assert.ok((await page.locator('acme-collapsible-content').textContent()).includes('Refine and return'))});
await check('content resize relayout keeps author content mounted',async()=>{const before=await page.locator('acme-flow-node').boundingBox();await page.evaluate(()=>{const extra=document.createElement('div');extra.textContent='More information';extra.style.height='150px';document.querySelector('acme-flow-node').append(extra)});await page.waitForFunction(()=>window.flow.scene?.nodes.get('n1').height>200);const after=await page.locator('acme-flow-node').boundingBox();assert.ok(after.height>before.height);assert.equal(await page.evaluate(()=>window.workers),1)});
await check('invalid references fail clearly and valid data recovers',async()=>{await page.evaluate(()=>window.flow.edges=[{id:'bad',source:'missing',target:'n0'}]);await page.waitForFunction(()=>window.failures.length>0);await page.evaluate(async()=>{window.flow.edges=[];await window.flow.layout()});assert.equal(await page.locator('[part=edge]').count(),0);assert.equal(await page.getByRole('button',{name:'Step 0',exact:true}).isVisible(),true)});
await check('empty, disconnect and reconnect release worker resources',async()=>{await page.evaluate(()=>window.flow.remove());assert.equal(await page.evaluate(()=>window.live),0);await page.evaluate(()=>document.body.append(window.flow));await page.waitForFunction(()=>window.live===1);await page.evaluate(async()=>{document.querySelector('acme-flow-node').remove();window.flow.nodes=[];window.flow.edges=[];await window.flow.layout()});await page.getByText('No nodes',{exact:true}).waitFor();assert.equal(await page.locator('[part=edge]').count(),0)});

await check('background pointer pan never captures nested control gestures',async()=>{const box=await page.locator('[part=background]').boundingBox();await page.mouse.move(box.x+30,box.y+30);await page.mouse.down();await page.mouse.move(box.x+100,box.y+60);await page.mouse.up();assert.ok(await page.evaluate(()=>window.changes.length)>0);const count=await page.evaluate(()=>window.changes.length);await page.locator('#draft').click();await page.keyboard.press('ArrowLeft');assert.equal(await page.evaluate(()=>window.changes.length),count)});
reports.push({engine,version:browser.version(),checks,errors});await browser.close()}}finally{server.stop(true)}await Bun.write(dir+'/firefox-sequence-results.json',JSON.stringify(reports,null,2));if(reports.some(r=>r.errors.length||r.checks.some(c=>!c.pass)))process.exitCode=1;
