import {AcmeCheckIcon} from "../../../generated/icons/classes/check-icon";
import {AcmeContentCopyIcon} from "../../../generated/icons/classes/content-copy-icon";
import {AcmeSpinner} from "../../../components/spinner/spinner";
import {AcmeCopyButton} from "../../../components/copy-button/copy-button";
import {AcmeDescriptionIcon} from "../../../generated/icons/classes/description-icon";
import {AcmeScrollCorner} from "../../../components/scroll-corner/scroll-corner";
import {AcmeScrollThumb} from "../../../components/scroll-thumb/scroll-thumb";
import {AcmeScrollbar} from "../../../components/scrollbar/scrollbar";
import {AcmeScrollArea} from "../../../components/scroll-area/scroll-area";
import {AcmeScrollViewport} from "../../../components/scroll-viewport/scroll-viewport";
import {AcmeCodeBlock} from "../../../components/code-block/code-block";
customElements.define('acme-check-icon',AcmeCheckIcon);
customElements.define('acme-content-copy-icon',AcmeContentCopyIcon);
customElements.define('acme-spinner',AcmeSpinner);
customElements.define('acme-copy-button',AcmeCopyButton);
customElements.define('acme-description-icon',AcmeDescriptionIcon);
customElements.define('acme-scroll-corner',AcmeScrollCorner);
customElements.define('acme-scroll-thumb',AcmeScrollThumb);
customElements.define('acme-scrollbar',AcmeScrollbar);
customElements.define('acme-scroll-area',AcmeScrollArea);
customElements.define('acme-scroll-viewport',AcmeScrollViewport);
customElements.define('acme-code-block',AcmeCodeBlock);
import {highlighter} from '../../../shared/highlight';
document.body.innerHTML='<acme-code-block id="code" filename="sample.ts" language="ts"></acme-code-block>';window.code=document.querySelector('#code');window.code.code='\nconst first = 1;  \nconst second = 2;\n';window.requests=[];window.errors=[];window.writes=[];window.highlighter=highlighter;window.code.addEventListener('acme-request',event=>window.requests.push(event.detail));window.code.addEventListener('acme-error',event=>window.errors.push(event.detail));Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async value=>window.writes.push(value)}});