// Generated by scripts/entries.ts. Do not edit.
import { Acme19mpIcon } from "../generated/icons/classes/19mp-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-19mp-icon", Acme19mpIcon);
}
