// Generated by scripts/entries.ts. Do not edit.
import { Acme1kIcon } from "../generated/icons/classes/1k-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-1k-icon", Acme1kIcon);
}
