// Generated by scripts/entries.ts. Do not edit.
import { Acme21mpIcon } from "../generated/icons/classes/21mp-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-21mp-icon", Acme21mpIcon);
}
