// Generated by scripts/entries.ts. Do not edit.
import { Acme3dIcon } from "../generated/icons/classes/3d-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-3d-icon", Acme3dIcon);
}
