// Generated by scripts/entries.ts. Do not edit.
import { Acme4gMobiledataIcon } from "../generated/icons/classes/4g-mobiledata-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-4g-mobiledata-icon", Acme4gMobiledataIcon);
}
