// Generated by scripts/entries.ts. Do not edit.
import { Acme4gPlusMobiledataIcon } from "../generated/icons/classes/4g-plus-mobiledata-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-4g-plus-mobiledata-icon", Acme4gPlusMobiledataIcon);
}
