// Generated by scripts/entries.ts. Do not edit.
import { Acme5kIcon } from "../generated/icons/classes/5k-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-5k-icon", Acme5kIcon);
}
