// Generated by scripts/entries.ts. Do not edit.
import { Acme5kPlusIcon } from "../generated/icons/classes/5k-plus-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-5k-plus-icon", Acme5kPlusIcon);
}
