// Generated by scripts/entries.ts. Do not edit.
import { Acme7kPlusIcon } from "../generated/icons/classes/7k-plus-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-7k-plus-icon", Acme7kPlusIcon);
}
