// Generated by scripts/entries.ts. Do not edit.
import { AcmeAccountChildIcon } from "../generated/icons/classes/account-child-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-account-child-icon", AcmeAccountChildIcon);
}
