// Generated by scripts/entries.ts. Do not edit.
import { AcmeActivityZoneIcon } from "../generated/icons/classes/activity-zone-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-activity-zone-icon", AcmeActivityZoneIcon);
}
