// Generated by scripts/entries.ts. Do not edit.
import { AcmeAdbIcon } from "../generated/icons/classes/adb-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-adb-icon", AcmeAdbIcon);
}
