// Generated by scripts/entries.ts. Do not edit.
import { AcmeAddRoadIcon } from "../generated/icons/classes/add-road-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-add-road-icon", AcmeAddRoadIcon);
}
