// Generated by scripts/entries.ts. Do not edit.
import { AcmeAddDiamondIcon } from "../generated/icons/classes/add-diamond-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-add-diamond-icon", AcmeAddDiamondIcon);
}
