// Generated by scripts/entries.ts. Do not edit.
import { AcmeAddCardIcon } from "../generated/icons/classes/add-card-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-add-card-icon", AcmeAddCardIcon);
}
