// Generated by scripts/entries.ts. Do not edit.
import { AcmeAddCircleIcon } from "../generated/icons/classes/add-circle-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-add-circle-icon", AcmeAddCircleIcon);
}
