// Generated by scripts/entries.ts. Do not edit.
import { AcmeAddToHomeScreenIcon } from "../generated/icons/classes/add-to-home-screen-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-add-to-home-screen-icon", AcmeAddToHomeScreenIcon);
}
