// Generated by scripts/entries.ts. Do not edit.
import { AcmeAddTaskIcon } from "../generated/icons/classes/add-task-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-add-task-icon", AcmeAddTaskIcon);
}
