// Generated by scripts/entries.ts. Do not edit.
import { AcmeAdminMedsIcon } from "../generated/icons/classes/admin-meds-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-admin-meds-icon", AcmeAdminMedsIcon);
}
