// Generated by scripts/entries.ts. Do not edit.
import { AcmeAirlinesIcon } from "../generated/icons/classes/airlines-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-airlines-icon", AcmeAirlinesIcon);
}
