// Generated by scripts/entries.ts. Do not edit.
import { AcmeAirlineSeatLegroomNormalIcon } from "../generated/icons/classes/airline-seat-legroom-normal-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-airline-seat-legroom-normal-icon", AcmeAirlineSeatLegroomNormalIcon);
}
