// Generated by scripts/entries.ts. Do not edit.
import { AcmeAlarmIcon } from "../generated/icons/classes/alarm-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-alarm-icon", AcmeAlarmIcon);
}
