// Generated by scripts/entries.ts. Do not edit.
import { AcmeAlignJustifyFlexEndIcon } from "../generated/icons/classes/align-justify-flex-end-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-align-justify-flex-end-icon", AcmeAlignJustifyFlexEndIcon);
}
