// Generated by scripts/entries.ts. Do not edit.
import { AcmeAlignHorizontalCenterIcon } from "../generated/icons/classes/align-horizontal-center-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-align-horizontal-center-icon", AcmeAlignHorizontalCenterIcon);
}
