// Generated by scripts/entries.ts. Do not edit.
import { AcmeAlignFlexCenterIcon } from "../generated/icons/classes/align-flex-center-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-align-flex-center-icon", AcmeAlignFlexCenterIcon);
}
