// Generated by scripts/entries.ts. Do not edit.
import { AcmeAllMatchIcon } from "../generated/icons/classes/all-match-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-all-match-icon", AcmeAllMatchIcon);
}
