// Generated by scripts/entries.ts. Do not edit.
import { AcmeAllOutIcon } from "../generated/icons/classes/all-out-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-all-out-icon", AcmeAllOutIcon);
}
