// Generated by scripts/entries.ts. Do not edit.
import { AcmeAmbulanceIcon } from "../generated/icons/classes/ambulance-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-ambulance-icon", AcmeAmbulanceIcon);
}
