// Generated by scripts/entries.ts. Do not edit.
import { AcmeAndroidCellDual4BarIcon } from "../generated/icons/classes/android-cell-dual-4-bar-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-android-cell-dual-4-bar-icon", AcmeAndroidCellDual4BarIcon);
}
