// Generated by scripts/entries.ts. Do not edit.
import { AcmeAndroidCell5BarAlertIcon } from "../generated/icons/classes/android-cell-5-bar-alert-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-android-cell-5-bar-alert-icon", AcmeAndroidCell5BarAlertIcon);
}
