// Generated by scripts/entries.ts. Do not edit.
import { AcmeAodIcon } from "../generated/icons/classes/aod-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-aod-icon", AcmeAodIcon);
}
