// Generated by scripts/entries.ts. Do not edit.
import { AcmeApkDocumentIcon } from "../generated/icons/classes/apk-document-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-apk-document-icon", AcmeApkDocumentIcon);
}
