// Generated by scripts/entries.ts. Do not edit.
import { AcmeAppBarStart } from "../components/app-bar-start/app-bar-start";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-app-bar-start", AcmeAppBarStart);
}
