// Generated by scripts/entries.ts. Do not edit.
import { AcmeApprovalDelegationIcon } from "../generated/icons/classes/approval-delegation-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-approval-delegation-icon", AcmeApprovalDelegationIcon);
}
