// Generated by scripts/entries.ts. Do not edit.
import { AcmeApprovalDelegationOffIcon } from "../generated/icons/classes/approval-delegation-off-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-approval-delegation-off-icon", AcmeApprovalDelegationOffIcon);
}
