// Generated by scripts/entries.ts. Do not edit.
import { AcmeArStickersIcon } from "../generated/icons/classes/ar-stickers-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-ar-stickers-icon", AcmeArStickersIcon);
}
