// Generated by scripts/entries.ts. Do not edit.
import { AcmeArrowLeftAltIcon } from "../generated/icons/classes/arrow-left-alt-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-arrow-left-alt-icon", AcmeArrowLeftAltIcon);
}
