// Generated by scripts/entries.ts. Do not edit.
import { AcmeArrowCircleRightIcon } from "../generated/icons/classes/arrow-circle-right-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-arrow-circle-right-icon", AcmeArrowCircleRightIcon);
}
