// Generated by scripts/entries.ts. Do not edit.
import { AcmeArrowBackIosNewIcon } from "../generated/icons/classes/arrow-back-ios-new-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-arrow-back-ios-new-icon", AcmeArrowBackIosNewIcon);
}
