// Generated by scripts/entries.ts. Do not edit.
import { AcmeArrowCircleUpIcon } from "../generated/icons/classes/arrow-circle-up-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-arrow-circle-up-icon", AcmeArrowCircleUpIcon);
}
