// Generated by scripts/entries.ts. Do not edit.
import { AcmeArrowInsertIcon } from "../generated/icons/classes/arrow-insert-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-arrow-insert-icon", AcmeArrowInsertIcon);
}
