// Generated by scripts/entries.ts. Do not edit.
import { AcmeAssignmentIcon } from "../generated/icons/classes/assignment-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-assignment-icon", AcmeAssignmentIcon);
}
