// Generated by scripts/entries.ts. Do not edit.
import { AcmeAssuredWorkloadIcon } from "../generated/icons/classes/assured-workload-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-assured-workload-icon", AcmeAssuredWorkloadIcon);
}
