// Generated by scripts/entries.ts. Do not edit.
import { AcmeAttributionIcon } from "../generated/icons/classes/attribution-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-attribution-icon", AcmeAttributionIcon);
}
