// Generated by scripts/entries.ts. Do not edit.
import { AcmeAudioVideoReceiverIcon } from "../generated/icons/classes/audio-video-receiver-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-audio-video-receiver-icon", AcmeAudioVideoReceiverIcon);
}
