// Generated by scripts/entries.ts. Do not edit.
import { AcmeAutoModeIcon } from "../generated/icons/classes/auto-mode-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-auto-mode-icon", AcmeAutoModeIcon);
}
