// Generated by scripts/entries.ts. Do not edit.
import { AcmeAutostopIcon } from "../generated/icons/classes/autostop-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-autostop-icon", AcmeAutostopIcon);
}
