// Generated by scripts/entries.ts. Do not edit.
import { AcmeAutoAwesomeMosaicIcon } from "../generated/icons/classes/auto-awesome-mosaic-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-auto-awesome-mosaic-icon", AcmeAutoAwesomeMosaicIcon);
}
