// Generated by scripts/entries.ts. Do not edit.
import { AcmeAutoStoriesOffIcon } from "../generated/icons/classes/auto-stories-off-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-auto-stories-off-icon", AcmeAutoStoriesOffIcon);
}
