// Generated by scripts/entries.ts. Do not edit.
import { AcmeAutoReadPlayIcon } from "../generated/icons/classes/auto-read-play-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-auto-read-play-icon", AcmeAutoReadPlayIcon);
}
