// Generated by scripts/entries.ts. Do not edit.
import { AcmeBadgeCriticalBatteryIcon } from "../generated/icons/classes/badge-critical-battery-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-badge-critical-battery-icon", AcmeBadgeCriticalBatteryIcon);
}
