// Generated by scripts/entries.ts. Do not edit.
import { AcmeBarChart4BarsIcon } from "../generated/icons/classes/bar-chart-4-bars-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-bar-chart-4-bars-icon", AcmeBarChart4BarsIcon);
}
