// Generated by scripts/entries.ts. Do not edit.
import { AcmeBattery60Icon } from "../generated/icons/classes/battery-60-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-battery-60-icon", AcmeBattery60Icon);
}
