// Generated by scripts/entries.ts. Do not edit.
import { AcmeBatteryAndroidFrame6Icon } from "../generated/icons/classes/battery-android-frame-6-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-battery-android-frame-6-icon", AcmeBatteryAndroidFrame6Icon);
}
