// Generated by scripts/entries.ts. Do not edit.
import { AcmeBatteryAndroidFramePlusIcon } from "../generated/icons/classes/battery-android-frame-plus-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-battery-android-frame-plus-icon", AcmeBatteryAndroidFramePlusIcon);
}
