// Generated by scripts/entries.ts. Do not edit.
import { AcmeBatteryFullIcon } from "../generated/icons/classes/battery-full-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-battery-full-icon", AcmeBatteryFullIcon);
}
