// Generated by scripts/entries.ts. Do not edit.
import { AcmeBattery5BarIcon } from "../generated/icons/classes/battery-5-bar-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-battery-5-bar-icon", AcmeBattery5BarIcon);
}
