// Generated by scripts/entries.ts. Do not edit.
import { AcmeBatteryAndroidFrameAlertIcon } from "../generated/icons/classes/battery-android-frame-alert-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-battery-android-frame-alert-icon", AcmeBatteryAndroidFrameAlertIcon);
}
