// Generated by scripts/entries.ts. Do not edit.
import { AcmeBatteryCharging502Icon } from "../generated/icons/classes/battery-charging-50-2-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-battery-charging-50-2-icon", AcmeBatteryCharging502Icon);
}
