// Generated by scripts/entries.ts. Do not edit.
import { AcmeBatteryCharging602Icon } from "../generated/icons/classes/battery-charging-60-2-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-battery-charging-60-2-icon", AcmeBatteryCharging602Icon);
}
