// Generated by scripts/entries.ts. Do not edit.
import { AcmeBatteryAndroid4Icon } from "../generated/icons/classes/battery-android-4-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-battery-android-4-icon", AcmeBatteryAndroid4Icon);
}
