// Generated by scripts/entries.ts. Do not edit.
import { AcmeBeachAccessIcon } from "../generated/icons/classes/beach-access-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-beach-access-icon", AcmeBeachAccessIcon);
}
