// Generated by scripts/entries.ts. Do not edit.
import { AcmeBedroomParentIcon } from "../generated/icons/classes/bedroom-parent-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-bedroom-parent-icon", AcmeBedroomParentIcon);
}
