// Generated by scripts/entries.ts. Do not edit.
import { AcmeBedroomChildIcon } from "../generated/icons/classes/bedroom-child-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-bedroom-child-icon", AcmeBedroomChildIcon);
}
