// Generated by scripts/entries.ts. Do not edit.
import { AcmeBiaIcon } from "../generated/icons/classes/bia-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-bia-icon", AcmeBiaIcon);
}
