// Generated by scripts/entries.ts. Do not edit.
import { AcmeBigtopUpdatesIcon } from "../generated/icons/classes/bigtop-updates-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-bigtop-updates-icon", AcmeBigtopUpdatesIcon);
}
