// Generated by scripts/entries.ts. Do not edit.
import { AcmeBluetoothIcon } from "../generated/icons/classes/bluetooth-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-bluetooth-icon", AcmeBluetoothIcon);
}
