// Generated by scripts/entries.ts. Do not edit.
import { AcmeBlurOnIcon } from "../generated/icons/classes/blur-on-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-blur-on-icon", AcmeBlurOnIcon);
}
