// Generated by scripts/entries.ts. Do not edit.
import { AcmeBoatBusIcon } from "../generated/icons/classes/boat-bus-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-boat-bus-icon", AcmeBoatBusIcon);
}
