// Generated by scripts/entries.ts. Do not edit.
import { AcmeBook4Icon } from "../generated/icons/classes/book-4-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-book-4-icon", AcmeBook4Icon);
}
