// Generated by scripts/entries.ts. Do not edit.
import { AcmeBook2Icon } from "../generated/icons/classes/book-2-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-book-2-icon", AcmeBook2Icon);
}
