// Generated by scripts/entries.ts. Do not edit.
import { AcmeBook6Icon } from "../generated/icons/classes/book-6-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-book-6-icon", AcmeBook6Icon);
}
