// Generated by scripts/entries.ts. Do not edit.
import { AcmeBookmarkStacksIcon } from "../generated/icons/classes/bookmark-stacks-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-bookmark-stacks-icon", AcmeBookmarkStacksIcon);
}
