// Generated by scripts/entries.ts. Do not edit.
import { AcmeBorderRightIcon } from "../generated/icons/classes/border-right-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-border-right-icon", AcmeBorderRightIcon);
}
