// Generated by scripts/entries.ts. Do not edit.
import { AcmeBorderAllIcon } from "../generated/icons/classes/border-all-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-border-all-icon", AcmeBorderAllIcon);
}
