// Generated by scripts/entries.ts. Do not edit.
import { AcmeBottomNavigationIcon } from "../generated/icons/classes/bottom-navigation-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-bottom-navigation-icon", AcmeBottomNavigationIcon);
}
