// Generated by scripts/entries.ts. Do not edit.
import { AcmeBox } from "../components/box/box";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-box", AcmeBox);
}
