// Generated by scripts/entries.ts. Do not edit.
import { AcmeBoyIcon } from "../generated/icons/classes/boy-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-boy-icon", AcmeBoyIcon);
}
