// Generated by scripts/entries.ts. Do not edit.
import { AcmeBrickIcon } from "../generated/icons/classes/brick-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-brick-icon", AcmeBrickIcon);
}
