// Generated by scripts/entries.ts. Do not edit.
import { AcmeBrightness6Icon } from "../generated/icons/classes/brightness-6-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-brightness-6-icon", AcmeBrightness6Icon);
}
