// Generated by scripts/entries.ts. Do not edit.
import { AcmeBrightness1Icon } from "../generated/icons/classes/brightness-1-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-brightness-1-icon", AcmeBrightness1Icon);
}
