// Generated by scripts/entries.ts. Do not edit.
import { AcmeBrokenImageIcon } from "../generated/icons/classes/broken-image-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-broken-image-icon", AcmeBrokenImageIcon);
}
