// Generated by scripts/entries.ts. Do not edit.
import { AcmeBrowseIcon } from "../generated/icons/classes/browse-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-browse-icon", AcmeBrowseIcon);
}
