// Generated by scripts/entries.ts. Do not edit.
import { AcmeBrunchDiningIcon } from "../generated/icons/classes/brunch-dining-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-brunch-dining-icon", AcmeBrunchDiningIcon);
}
