// Generated by scripts/entries.ts. Do not edit.
import { AcmeBusMapPin2Icon } from "../generated/icons/classes/bus-map-pin-2-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-bus-map-pin-2-icon", AcmeBusMapPin2Icon);
}
