// Generated by scripts/entries.ts. Do not edit.
import { AcmeCableIcon } from "../generated/icons/classes/cable-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-cable-icon", AcmeCableIcon);
}
