// Generated by scripts/entries.ts. Do not edit.
import { AcmeCalendarMonthIcon } from "../generated/icons/classes/calendar-month-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-calendar-month-icon", AcmeCalendarMonthIcon);
}
