// Generated by scripts/entries.ts. Do not edit.
import { AcmeCalendarClockIcon } from "../generated/icons/classes/calendar-clock-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-calendar-clock-icon", AcmeCalendarClockIcon);
}
