// Generated by scripts/entries.ts. Do not edit.
import { AcmeCallMissedOutgoingIcon } from "../generated/icons/classes/call-missed-outgoing-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-call-missed-outgoing-icon", AcmeCallMissedOutgoingIcon);
}
