// Generated by scripts/entries.ts. Do not edit.
import { AcmeCallEndIcon } from "../generated/icons/classes/call-end-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-call-end-icon", AcmeCallEndIcon);
}
