// Generated by scripts/entries.ts. Do not edit.
import { AcmeCameraswitchIcon } from "../generated/icons/classes/cameraswitch-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-cameraswitch-icon", AcmeCameraswitchIcon);
}
