// Generated by scripts/entries.ts. Do not edit.
import { AcmeCameraIndoorIcon } from "../generated/icons/classes/camera-indoor-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-camera-indoor-icon", AcmeCameraIndoorIcon);
}
