// Generated by scripts/entries.ts. Do not edit.
import { AcmeCandleIcon } from "../generated/icons/classes/candle-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-candle-icon", AcmeCandleIcon);
}
