// Generated by scripts/entries.ts. Do not edit.
import { AcmeCarFanLowMidLeftIcon } from "../generated/icons/classes/car-fan-low-mid-left-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-car-fan-low-mid-left-icon", AcmeCarFanLowMidLeftIcon);
}
