// Generated by scripts/entries.ts. Do not edit.
import { AcmeCarCrashIcon } from "../generated/icons/classes/car-crash-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-car-crash-icon", AcmeCarCrashIcon);
}
