// Generated by scripts/entries.ts. Do not edit.
import { AcmeCarFanLowRightIcon } from "../generated/icons/classes/car-fan-low-right-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-car-fan-low-right-icon", AcmeCarFanLowRightIcon);
}
