// Generated by scripts/entries.ts. Do not edit.
import { AcmeCardsIcon } from "../generated/icons/classes/cards-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-cards-icon", AcmeCardsIcon);
}
