// Generated by scripts/entries.ts. Do not edit.
import { AcmeCardiologyIcon } from "../generated/icons/classes/cardiology-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-cardiology-icon", AcmeCardiologyIcon);
}
