// Generated by scripts/entries.ts. Do not edit.
import { AcmeCardBody } from "../components/card-body/card-body";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-card-body", AcmeCardBody);
}
