// Generated by scripts/entries.ts. Do not edit.
import { AcmeCarryOnBagInactiveIcon } from "../generated/icons/classes/carry-on-bag-inactive-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-carry-on-bag-inactive-icon", AcmeCarryOnBagInactiveIcon);
}
