// Generated by scripts/entries.ts. Do not edit.
import { AcmeCastPauseIcon } from "../generated/icons/classes/cast-pause-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-cast-pause-icon", AcmeCastPauseIcon);
}
