// Generated by scripts/entries.ts. Do not edit.
import { AcmeCellTowerIcon } from "../generated/icons/classes/cell-tower-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-cell-tower-icon", AcmeCellTowerIcon);
}
