// Generated by scripts/entries.ts. Do not edit.
import { AcmeChairCounterIcon } from "../generated/icons/classes/chair-counter-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-chair-counter-icon", AcmeChairCounterIcon);
}
