// Generated by scripts/entries.ts. Do not edit.
import { AcmeChairFireplaceIcon } from "../generated/icons/classes/chair-fireplace-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-chair-fireplace-icon", AcmeChairFireplaceIcon);
}
