// Generated by scripts/entries.ts. Do not edit.
import { AcmeChargingStationIcon } from "../generated/icons/classes/charging-station-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-charging-station-icon", AcmeChargingStationIcon);
}
