// Generated by scripts/entries.ts. Do not edit.
import { AcmeChatBubbleOffIcon } from "../generated/icons/classes/chat-bubble-off-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-chat-bubble-off-icon", AcmeChatBubbleOffIcon);
}
