// Generated by scripts/entries.ts. Do not edit.
import { AcmeChatIcon } from "../generated/icons/classes/chat-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-chat-icon", AcmeChatIcon);
}
