// Generated by scripts/entries.ts. Do not edit.
import { AcmeChatPasteGo2Icon } from "../generated/icons/classes/chat-paste-go-2-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-chat-paste-go-2-icon", AcmeChatPasteGo2Icon);
}
