// Generated by scripts/entries.ts. Do not edit.
import { AcmeCheckedBagIcon } from "../generated/icons/classes/checked-bag-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-checked-bag-icon", AcmeCheckedBagIcon);
}
