// Generated by scripts/entries.ts. Do not edit.
import { AcmeCheckbookIcon } from "../generated/icons/classes/checkbook-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-checkbook-icon", AcmeCheckbookIcon);
}
