// Generated by scripts/entries.ts. Do not edit.
import { AcmeCheckroomIcon } from "../generated/icons/classes/checkroom-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-checkroom-icon", AcmeCheckroomIcon);
}
