// Generated by scripts/entries.ts. Do not edit.
import { AcmeChessKnightIcon } from "../generated/icons/classes/chess-knight-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-chess-knight-icon", AcmeChessKnightIcon);
}
