// Generated by scripts/entries.ts. Do not edit.
import { AcmeChessQueenIcon } from "../generated/icons/classes/chess-queen-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-chess-queen-icon", AcmeChessQueenIcon);
}
