// Generated by scripts/entries.ts. Do not edit.
import { AcmeChevronLineUpIcon } from "../generated/icons/classes/chevron-line-up-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-chevron-line-up-icon", AcmeChevronLineUpIcon);
}
