// Generated by scripts/entries.ts. Do not edit.
import { AcmeCinematicBlurIcon } from "../generated/icons/classes/cinematic-blur-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-cinematic-blur-icon", AcmeCinematicBlurIcon);
}
