// Generated by scripts/entries.ts. Do not edit.
import { AcmeCloseIcon } from "../generated/icons/classes/close-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-close-icon", AcmeCloseIcon);
}
