// Generated by scripts/entries.ts. Do not edit.
import { AcmeClosedCaptionAddIcon } from "../generated/icons/classes/closed-caption-add-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-closed-caption-add-icon", AcmeClosedCaptionAddIcon);
}
