// Generated by scripts/entries.ts. Do not edit.
import { AcmeCloudyFilledIcon } from "../generated/icons/classes/cloudy-filled-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-cloudy-filled-icon", AcmeCloudyFilledIcon);
}
