// Generated by scripts/entries.ts. Do not edit.
import { AcmeColorsIcon } from "../generated/icons/classes/colors-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-colors-icon", AcmeColorsIcon);
}
