// Generated by scripts/entries.ts. Do not edit.
import { AcmeCommuteIcon } from "../generated/icons/classes/commute-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-commute-icon", AcmeCommuteIcon);
}
