// Generated by scripts/entries.ts. Do not edit.
import { AcmeCompareArrowsIcon } from "../generated/icons/classes/compare-arrows-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-compare-arrows-icon", AcmeCompareArrowsIcon);
}
