// Generated by scripts/entries.ts. Do not edit.
import { AcmeContextMenu } from "../components/context-menu/context-menu";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-context-menu", AcmeContextMenu);
}
