// Generated by scripts/entries.ts. Do not edit.
import { AcmeContactPageIcon } from "../generated/icons/classes/contact-page-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-contact-page-icon", AcmeContactPageIcon);
}
