// Generated by scripts/entries.ts. Do not edit.
import { AcmeContentPasteGoIcon } from "../generated/icons/classes/content-paste-go-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-content-paste-go-icon", AcmeContentPasteGoIcon);
}
