// Generated by scripts/entries.ts. Do not edit.
import { AcmeContentPasteOffIcon } from "../generated/icons/classes/content-paste-off-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-content-paste-off-icon", AcmeContentPasteOffIcon);
}
