// Generated by scripts/entries.ts. Do not edit.
import { AcmeContentPasteIcon } from "../generated/icons/classes/content-paste-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-content-paste-icon", AcmeContentPasteIcon);
}
