// Generated by scripts/entries.ts. Do not edit.
import { AcmeCookieOffIcon } from "../generated/icons/classes/cookie-off-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-cookie-off-icon", AcmeCookieOffIcon);
}
