// Generated by scripts/entries.ts. Do not edit.
import { AcmeCounter3Icon } from "../generated/icons/classes/counter-3-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-counter-3-icon", AcmeCounter3Icon);
}
