// Generated by scripts/entries.ts. Do not edit.
import { AcmeCounter6Icon } from "../generated/icons/classes/counter-6-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-counter-6-icon", AcmeCounter6Icon);
}
