// Generated by scripts/entries.ts. Do not edit.
import { AcmeCropIcon } from "../generated/icons/classes/crop-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-crop-icon", AcmeCropIcon);
}
