// Generated by scripts/entries.ts. Do not edit.
import { AcmeCropPortraitIcon } from "../generated/icons/classes/crop-portrait-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-crop-portrait-icon", AcmeCropPortraitIcon);
}
