// Generated by scripts/entries.ts. Do not edit.
import { AcmeCurrencyLiraIcon } from "../generated/icons/classes/currency-lira-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-currency-lira-icon", AcmeCurrencyLiraIcon);
}
