// Generated by scripts/entries.ts. Do not edit.
import { AcmeCutIcon } from "../generated/icons/classes/cut-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-cut-icon", AcmeCutIcon);
}
