// Generated by scripts/entries.ts. Do not edit.
import { AcmeDataAlertIcon } from "../generated/icons/classes/data-alert-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-data-alert-icon", AcmeDataAlertIcon);
}
