// Generated by scripts/entries.ts. Do not edit.
import { AcmeDateRangeIcon } from "../generated/icons/classes/date-range-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-date-range-icon", AcmeDateRangeIcon);
}
