// Generated by scripts/entries.ts. Do not edit.
import { AcmeDecimalIncreaseIcon } from "../generated/icons/classes/decimal-increase-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-decimal-increase-icon", AcmeDecimalIncreaseIcon);
}
