// Generated by scripts/entries.ts. Do not edit.
import { AcmeDeckIcon } from "../generated/icons/classes/deck-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-deck-icon", AcmeDeckIcon);
}
