// Generated by scripts/entries.ts. Do not edit.
import { AcmeDeleteSweepIcon } from "../generated/icons/classes/delete-sweep-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-delete-sweep-icon", AcmeDeleteSweepIcon);
}
