// Generated by scripts/entries.ts. Do not edit.
import { AcmeDepartureBoardIcon } from "../generated/icons/classes/departure-board-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-departure-board-icon", AcmeDepartureBoardIcon);
}
