// Generated by scripts/entries.ts. Do not edit.
import { AcmeDeselectIcon } from "../generated/icons/classes/deselect-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-deselect-icon", AcmeDeselectIcon);
}
