// Generated by scripts/entries.ts. Do not edit.
import { AcmeDeskIcon } from "../generated/icons/classes/desk-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-desk-icon", AcmeDeskIcon);
}
