// Generated by scripts/entries.ts. Do not edit.
import { AcmeDetectionAndZoneOffIcon } from "../generated/icons/classes/detection-and-zone-off-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-detection-and-zone-off-icon", AcmeDetectionAndZoneOffIcon);
}
