// Generated by scripts/entries.ts. Do not edit.
import { AcmeDetectorCoIcon } from "../generated/icons/classes/detector-co-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-detector-co-icon", AcmeDetectorCoIcon);
}
