// Generated by scripts/entries.ts. Do not edit.
import { AcmeDetectorIcon } from "../generated/icons/classes/detector-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-detector-icon", AcmeDetectorIcon);
}
