// Generated by scripts/entries.ts. Do not edit.
import { AcmeDetectorOfflineIcon } from "../generated/icons/classes/detector-offline-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-detector-offline-icon", AcmeDetectorOfflineIcon);
}
