// Generated by scripts/entries.ts. Do not edit.
import { AcmeDeveloperModeIcon } from "../generated/icons/classes/developer-mode-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-developer-mode-icon", AcmeDeveloperModeIcon);
}
