// Generated by scripts/entries.ts. Do not edit.
import { AcmeDeviceSwooshStarIcon } from "../generated/icons/classes/device-swoosh-star-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-device-swoosh-star-icon", AcmeDeviceSwooshStarIcon);
}
