// Generated by scripts/entries.ts. Do not edit.
import { AcmeDevicesFoldIcon } from "../generated/icons/classes/devices-fold-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-devices-fold-icon", AcmeDevicesFoldIcon);
}
