// Generated by scripts/entries.ts. Do not edit.
import { AcmeDevicesIcon } from "../generated/icons/classes/devices-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-devices-icon", AcmeDevicesIcon);
}
