// Generated by scripts/entries.ts. Do not edit.
import { register as register0 } from "../internal/register/overlay-theme";
import { AcmeDialog } from "../components/dialog/dialog";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  register0(registry);
  registerElement(registry, "acme-dialog", AcmeDialog);
}
