// Generated by scripts/entries.ts. Do not edit.
import { AcmeDirectionsWalkIcon } from "../generated/icons/classes/directions-walk-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-directions-walk-icon", AcmeDirectionsWalkIcon);
}
