// Generated by scripts/entries.ts. Do not edit.
import { AcmeDirectionsBusIcon } from "../generated/icons/classes/directions-bus-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-directions-bus-icon", AcmeDirectionsBusIcon);
}
