// Generated by scripts/entries.ts. Do not edit.
import { AcmeDishwasherGenIcon } from "../generated/icons/classes/dishwasher-gen-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-dishwasher-gen-icon", AcmeDishwasherGenIcon);
}
