// Generated by scripts/entries.ts. Do not edit.
import { AcmeDomainVerificationOffIcon } from "../generated/icons/classes/domain-verification-off-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-domain-verification-off-icon", AcmeDomainVerificationOffIcon);
}
