// Generated by scripts/entries.ts. Do not edit.
import { AcmeDomainDisabledCheckIcon } from "../generated/icons/classes/domain-disabled-check-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-domain-disabled-check-icon", AcmeDomainDisabledCheckIcon);
}
