// Generated by scripts/entries.ts. Do not edit.
import { AcmeDoneIcon } from "../generated/icons/classes/done-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-done-icon", AcmeDoneIcon);
}
