// Generated by scripts/entries.ts. Do not edit.
import { AcmeDoorBackIcon } from "../generated/icons/classes/door-back-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-door-back-icon", AcmeDoorBackIcon);
}
