// Generated by scripts/entries.ts. Do not edit.
import { AcmeDoorbellIcon } from "../generated/icons/classes/doorbell-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-doorbell-icon", AcmeDoorbellIcon);
}
