// Generated by scripts/entries.ts. Do not edit.
import { AcmeDownloadingIcon } from "../generated/icons/classes/downloading-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-downloading-icon", AcmeDownloadingIcon);
}
