// Generated by scripts/entries.ts. Do not edit.
import { AcmeDrawAbstractIcon } from "../generated/icons/classes/draw-abstract-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-draw-abstract-icon", AcmeDrawAbstractIcon);
}
