// Generated by scripts/entries.ts. Do not edit.
import { AcmeDriveFusiontableIcon } from "../generated/icons/classes/drive-fusiontable-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-drive-fusiontable-icon", AcmeDriveFusiontableIcon);
}
