// Generated by scripts/entries.ts. Do not edit.
import { AcmeDropdownIcon } from "../generated/icons/classes/dropdown-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-dropdown-icon", AcmeDropdownIcon);
}
