// Generated by scripts/entries.ts. Do not edit.
import { AcmeDuoIcon } from "../generated/icons/classes/duo-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-duo-icon", AcmeDuoIcon);
}
