// Generated by scripts/entries.ts. Do not edit.
import { AcmeDvrIcon } from "../generated/icons/classes/dvr-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-dvr-icon", AcmeDvrIcon);
}
