// Generated by scripts/entries.ts. Do not edit.
import { AcmeEMobiledataIcon } from "../generated/icons/classes/e-mobiledata-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-e-mobiledata-icon", AcmeEMobiledataIcon);
}
