// Generated by scripts/entries.ts. Do not edit.
import { AcmeEarbudsBatteryIcon } from "../generated/icons/classes/earbuds-battery-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-earbuds-battery-icon", AcmeEarbudsBatteryIcon);
}
