// Generated by scripts/entries.ts. Do not edit.
import { AcmeEarbudRightIcon } from "../generated/icons/classes/earbud-right-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-earbud-right-icon", AcmeEarbudRightIcon);
}
