// Generated by scripts/entries.ts. Do not edit.
import { AcmeEcgHeartIcon } from "../generated/icons/classes/ecg-heart-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-ecg-heart-icon", AcmeEcgHeartIcon);
}
