// Generated by scripts/entries.ts. Do not edit.
import { AcmeEcoIcon } from "../generated/icons/classes/eco-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-eco-icon", AcmeEcoIcon);
}
