// Generated by scripts/entries.ts. Do not edit.
import { AcmeEdgesensorHighIcon } from "../generated/icons/classes/edgesensor-high-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-edgesensor-high-icon", AcmeEdgesensorHighIcon);
}
