// Generated by scripts/entries.ts. Do not edit.
import { AcmeEditNotificationsIcon } from "../generated/icons/classes/edit-notifications-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-edit-notifications-icon", AcmeEditNotificationsIcon);
}
