// Generated by scripts/entries.ts. Do not edit.
import { AcmeEditDocumentIcon } from "../generated/icons/classes/edit-document-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-edit-document-icon", AcmeEditDocumentIcon);
}
