// Generated by scripts/entries.ts. Do not edit.
import { AcmeEditAttributesIcon } from "../generated/icons/classes/edit-attributes-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-edit-attributes-icon", AcmeEditAttributesIcon);
}
