// Generated by scripts/entries.ts. Do not edit.
import { AcmeEditCalendarIcon } from "../generated/icons/classes/edit-calendar-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-edit-calendar-icon", AcmeEditCalendarIcon);
}
