// Generated by scripts/entries.ts. Do not edit.
import { AcmeEjectIcon } from "../generated/icons/classes/eject-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-eject-icon", AcmeEjectIcon);
}
