// Generated by scripts/entries.ts. Do not edit.
import { AcmeElectricMopedIcon } from "../generated/icons/classes/electric-moped-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-electric-moped-icon", AcmeElectricMopedIcon);
}
