// Generated by scripts/entries.ts. Do not edit.
import { AcmeElevationIcon } from "../generated/icons/classes/elevation-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-elevation-icon", AcmeElevationIcon);
}
