// Generated by scripts/entries.ts. Do not edit.
import { AcmeEmojiPeopleIcon } from "../generated/icons/classes/emoji-people-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-emoji-people-icon", AcmeEmojiPeopleIcon);
}
