// Generated by scripts/entries.ts. Do not edit.
import { AcmeEncryptedMinusCircleIcon } from "../generated/icons/classes/encrypted-minus-circle-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-encrypted-minus-circle-icon", AcmeEncryptedMinusCircleIcon);
}
