// Generated by scripts/entries.ts. Do not edit.
import { AcmeEnergySavingsLeafIcon } from "../generated/icons/classes/energy-savings-leaf-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-energy-savings-leaf-icon", AcmeEnergySavingsLeafIcon);
}
