// Generated by scripts/entries.ts. Do not edit.
import { AcmeErrorMedIcon } from "../generated/icons/classes/error-med-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-error-med-icon", AcmeErrorMedIcon);
}
