// Generated by scripts/entries.ts. Do not edit.
import { AcmeErrorIcon } from "../generated/icons/classes/error-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-error-icon", AcmeErrorIcon);
}
