// Generated by scripts/entries.ts. Do not edit.
import { AcmeEscalatorIcon } from "../generated/icons/classes/escalator-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-escalator-icon", AcmeEscalatorIcon);
}
