// Generated by scripts/entries.ts. Do not edit.
import { AcmeEvMobiledataBadgeIcon } from "../generated/icons/classes/ev-mobiledata-badge-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-ev-mobiledata-badge-icon", AcmeEvMobiledataBadgeIcon);
}
