// Generated by scripts/entries.ts. Do not edit.
import { AcmeEvStationIcon } from "../generated/icons/classes/ev-station-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-ev-station-icon", AcmeEvStationIcon);
}
