// Generated by scripts/entries.ts. Do not edit.
import { AcmeEventIcon } from "../generated/icons/classes/event-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-event-icon", AcmeEventIcon);
}
