// Generated by scripts/entries.ts. Do not edit.
import { AcmeExpansionPanelsIcon } from "../generated/icons/classes/expansion-panels-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-expansion-panels-icon", AcmeExpansionPanelsIcon);
}
