// Generated by scripts/entries.ts. Do not edit.
import { AcmeExpandCircleRightIcon } from "../generated/icons/classes/expand-circle-right-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-expand-circle-right-icon", AcmeExpandCircleRightIcon);
}
