// Generated by scripts/entries.ts. Do not edit.
import { AcmeExposurePlus1Icon } from "../generated/icons/classes/exposure-plus-1-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-exposure-plus-1-icon", AcmeExposurePlus1Icon);
}
