// Generated by scripts/entries.ts. Do not edit.
import { AcmeExtensionOffIcon } from "../generated/icons/classes/extension-off-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-extension-off-icon", AcmeExtensionOffIcon);
}
