// Generated by scripts/entries.ts. Do not edit.
import { AcmeEyeTrackingIcon } from "../generated/icons/classes/eye-tracking-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-eye-tracking-icon", AcmeEyeTrackingIcon);
}
