// Generated by scripts/entries.ts. Do not edit.
import { AcmeFaceRightIcon } from "../generated/icons/classes/face-right-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-face-right-icon", AcmeFaceRightIcon);
}
