// Generated by scripts/entries.ts. Do not edit.
import { AcmeFace4Icon } from "../generated/icons/classes/face-4-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-face-4-icon", AcmeFace4Icon);
}
