// Generated by scripts/entries.ts. Do not edit.
import { AcmeFastfoodIcon } from "../generated/icons/classes/fastfood-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-fastfood-icon", AcmeFastfoodIcon);
}
