// Generated by scripts/entries.ts. Do not edit.
import { AcmeFeedbackIcon } from "../generated/icons/classes/feedback-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-feedback-icon", AcmeFeedbackIcon);
}
