// Generated by scripts/entries.ts. Do not edit.
import { AcmeFeedIcon } from "../generated/icons/classes/feed-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-feed-icon", AcmeFeedIcon);
}
