// Generated by scripts/entries.ts. Do not edit.
import { AcmeFiberNewIcon } from "../generated/icons/classes/fiber-new-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-fiber-new-icon", AcmeFiberNewIcon);
}
