// Generated by scripts/entries.ts. Do not edit.
import { AcmeFiberPinIcon } from "../generated/icons/classes/fiber-pin-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-fiber-pin-icon", AcmeFiberPinIcon);
}
