// Generated by scripts/entries.ts. Do not edit.
import { AcmeFileCopyOffIcon } from "../generated/icons/classes/file-copy-off-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-file-copy-off-icon", AcmeFileCopyOffIcon);
}
