// Generated by scripts/entries.ts. Do not edit.
import { AcmeFilterCenterFocusIcon } from "../generated/icons/classes/filter-center-focus-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-filter-center-focus-icon", AcmeFilterCenterFocusIcon);
}
