// Generated by scripts/entries.ts. Do not edit.
import { AcmeFilter6Icon } from "../generated/icons/classes/filter-6-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-filter-6-icon", AcmeFilter6Icon);
}
