// Generated by scripts/entries.ts. Do not edit.
import { AcmeFilter1Icon } from "../generated/icons/classes/filter-1-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-filter-1-icon", AcmeFilter1Icon);
}
