// Generated by scripts/entries.ts. Do not edit.
import { AcmeFilterListIcon } from "../generated/icons/classes/filter-list-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-filter-list-icon", AcmeFilterListIcon);
}
