// Generated by scripts/entries.ts. Do not edit.
import { AcmeFitbitRaquetballIcon } from "../generated/icons/classes/fitbit-raquetball-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-fitbit-raquetball-icon", AcmeFitbitRaquetballIcon);
}
