// Generated by scripts/entries.ts. Do not edit.
import { AcmeFlag2Icon } from "../generated/icons/classes/flag-2-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-flag-2-icon", AcmeFlag2Icon);
}
