// Generated by scripts/entries.ts. Do not edit.
import { AcmeFlashOffIcon } from "../generated/icons/classes/flash-off-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-flash-off-icon", AcmeFlashOffIcon);
}
