// Generated by scripts/entries.ts. Do not edit.
import { AcmeFlashlightOnIcon } from "../generated/icons/classes/flashlight-on-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-flashlight-on-icon", AcmeFlashlightOnIcon);
}
