// Generated by scripts/entries.ts. Do not edit.
import { AcmeFlexWrapIcon } from "../generated/icons/classes/flex-wrap-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-flex-wrap-icon", AcmeFlexWrapIcon);
}
