// Generated by scripts/entries.ts. Do not edit.
import { AcmeFlipToBackIcon } from "../generated/icons/classes/flip-to-back-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-flip-to-back-icon", AcmeFlipToBackIcon);
}
