// Generated by scripts/entries.ts. Do not edit.
import { AcmeFlipIcon } from "../generated/icons/classes/flip-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-flip-icon", AcmeFlipIcon);
}
