// Generated by scripts/entries.ts. Do not edit.
import { AcmeFloatLandscapeIcon } from "../generated/icons/classes/float-landscape-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-float-landscape-icon", AcmeFloatLandscapeIcon);
}
