// Generated by scripts/entries.ts. Do not edit.
import { AcmeFlowsheetIcon } from "../generated/icons/classes/flowsheet-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-flowsheet-icon", AcmeFlowsheetIcon);
}
