// Generated by scripts/entries.ts. Do not edit.
import { AcmeFluidIcon } from "../generated/icons/classes/fluid-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-fluid-icon", AcmeFluidIcon);
}
