// Generated by scripts/entries.ts. Do not edit.
import { AcmeFmdBadIcon } from "../generated/icons/classes/fmd-bad-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-fmd-bad-icon", AcmeFmdBadIcon);
}
