// Generated by scripts/entries.ts. Do not edit.
import { AcmeFollowTheSignsIcon } from "../generated/icons/classes/follow-the-signs-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-follow-the-signs-icon", AcmeFollowTheSignsIcon);
}
