// Generated by scripts/entries.ts. Do not edit.
import { AcmeFontDownloadIcon } from "../generated/icons/classes/font-download-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-font-download-icon", AcmeFontDownloadIcon);
}
