// Generated by scripts/entries.ts. Do not edit.
import { AcmeFormatParagraphIcon } from "../generated/icons/classes/format-paragraph-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-format-paragraph-icon", AcmeFormatParagraphIcon);
}
