// Generated by scripts/entries.ts. Do not edit.
import { AcmeFormatListNumberedRtlIcon } from "../generated/icons/classes/format-list-numbered-rtl-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-format-list-numbered-rtl-icon", AcmeFormatListNumberedRtlIcon);
}
