// Generated by scripts/entries.ts. Do not edit.
import { AcmeFormatAlignJustifyIcon } from "../generated/icons/classes/format-align-justify-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-format-align-justify-icon", AcmeFormatAlignJustifyIcon);
}
