// Generated by scripts/entries.ts. Do not edit.
import { AcmeFormatImageBreakRightIcon } from "../generated/icons/classes/format-image-break-right-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-format-image-break-right-icon", AcmeFormatImageBreakRightIcon);
}
