// Generated by scripts/entries.ts. Do not edit.
import { AcmeFormsAddOnIcon } from "../generated/icons/classes/forms-add-on-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-forms-add-on-icon", AcmeFormsAddOnIcon);
}
