// Generated by scripts/entries.ts. Do not edit.
import { AcmeFormatShapesIcon } from "../generated/icons/classes/format-shapes-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-format-shapes-icon", AcmeFormatShapesIcon);
}
