// Generated by scripts/entries.ts. Do not edit.
import { AcmeFormatQuoteIcon } from "../generated/icons/classes/format-quote-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-format-quote-icon", AcmeFormatQuoteIcon);
}
