// Generated by scripts/entries.ts. Do not edit.
import { AcmeFormatStrikethroughIcon } from "../generated/icons/classes/format-strikethrough-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-format-strikethrough-icon", AcmeFormatStrikethroughIcon);
}
