// Generated by scripts/entries.ts. Do not edit.
import { AcmeFormatAlignCenterIcon } from "../generated/icons/classes/format-align-center-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-format-align-center-icon", AcmeFormatAlignCenterIcon);
}
