// Generated by scripts/entries.ts. Do not edit.
import { AcmeFormatImageInlineLeftIcon } from "../generated/icons/classes/format-image-inline-left-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-format-image-inline-left-icon", AcmeFormatImageInlineLeftIcon);
}
