// Generated by scripts/entries.ts. Do not edit.
import { AcmeFortIcon } from "../generated/icons/classes/fort-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-fort-icon", AcmeFortIcon);
}
