// Generated by scripts/entries.ts. Do not edit.
import { AcmeForward10Icon } from "../generated/icons/classes/forward-10-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-forward-10-icon", AcmeForward10Icon);
}
