// Generated by scripts/entries.ts. Do not edit.
import { AcmeFoundationIcon } from "../generated/icons/classes/foundation-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-foundation-icon", AcmeFoundationIcon);
}
