// Generated by scripts/entries.ts. Do not edit.
import { AcmeFrameSourceIcon } from "../generated/icons/classes/frame-source-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-frame-source-icon", AcmeFrameSourceIcon);
}
