// Generated by scripts/entries.ts. Do not edit.
import { AcmeFullStackedBarChartIcon } from "../generated/icons/classes/full-stacked-bar-chart-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-full-stacked-bar-chart-icon", AcmeFullStackedBarChartIcon);
}
