// Generated by scripts/entries.ts. Do not edit.
import { AcmeFunctionIcon } from "../generated/icons/classes/function-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-function-icon", AcmeFunctionIcon);
}
