// Generated by scripts/entries.ts. Do not edit.
import { AcmeGamepadDownIcon } from "../generated/icons/classes/gamepad-down-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-gamepad-down-icon", AcmeGamepadDownIcon);
}
