// Generated by scripts/entries.ts. Do not edit.
import { AcmeGamepadCircleLeftIcon } from "../generated/icons/classes/gamepad-circle-left-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-gamepad-circle-left-icon", AcmeGamepadCircleLeftIcon);
}
