// Generated by scripts/entries.ts. Do not edit.
import { AcmeGarageCheckIcon } from "../generated/icons/classes/garage-check-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-garage-check-icon", AcmeGarageCheckIcon);
}
