// Generated by scripts/entries.ts. Do not edit.
import { AcmeGarageHomeIcon } from "../generated/icons/classes/garage-home-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-garage-home-icon", AcmeGarageHomeIcon);
}
