// Generated by scripts/entries.ts. Do not edit.
import { AcmeGeneticsIcon } from "../generated/icons/classes/genetics-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-genetics-icon", AcmeGeneticsIcon);
}
