// Generated by scripts/entries.ts. Do not edit.
import { AcmeGiteIcon } from "../generated/icons/classes/gite-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-gite-icon", AcmeGiteIcon);
}
