// Generated by scripts/entries.ts. Do not edit.
import { AcmeGlassCupIcon } from "../generated/icons/classes/glass-cup-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-glass-cup-icon", AcmeGlassCupIcon);
}
