// Generated by scripts/entries.ts. Do not edit.
import { AcmeGlobe2QuestionIcon } from "../generated/icons/classes/globe-2-question-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-globe-2-question-icon", AcmeGlobe2QuestionIcon);
}
