// Generated by scripts/entries.ts. Do not edit.
import { AcmeGraph6Icon } from "../generated/icons/classes/graph-6-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-graph-6-icon", AcmeGraph6Icon);
}
