// Generated by scripts/entries.ts. Do not edit.
import { AcmeGrid3x3Icon } from "../generated/icons/classes/grid-3x3-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-grid-3x3-icon", AcmeGrid3x3Icon);
}
