// Generated by scripts/entries.ts. Do not edit.
import { AcmeGrid4x4Icon } from "../generated/icons/classes/grid-4x4-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-grid-4x4-icon", AcmeGrid4x4Icon);
}
