// Generated by scripts/entries.ts. Do not edit.
import { AcmeHPlusMobiledataBadgeIcon } from "../generated/icons/classes/h-plus-mobiledata-badge-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-h-plus-mobiledata-badge-icon", AcmeHPlusMobiledataBadgeIcon);
}
