// Generated by scripts/entries.ts. Do not edit.
import { register as register0 } from "./separator";
import { AcmeHStack } from "../components/h-stack/h-stack";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  register0(registry);
  registerElement(registry, "acme-h-stack", AcmeHStack);
}
