// Generated by scripts/entries.ts. Do not edit.
import { AcmeHandGestureIcon } from "../generated/icons/classes/hand-gesture-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-hand-gesture-icon", AcmeHandGestureIcon);
}
