// Generated by scripts/entries.ts. Do not edit.
import { AcmeHardDrive2Icon } from "../generated/icons/classes/hard-drive-2-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-hard-drive-2-icon", AcmeHardDrive2Icon);
}
