// Generated by scripts/entries.ts. Do not edit.
import { AcmeHdrPlusOffIcon } from "../generated/icons/classes/hdr-plus-off-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-hdr-plus-off-icon", AcmeHdrPlusOffIcon);
}
