// Generated by scripts/entries.ts. Do not edit.
import { AcmeHdrWeakIcon } from "../generated/icons/classes/hdr-weak-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-hdr-weak-icon", AcmeHdrWeakIcon);
}
