// Generated by scripts/entries.ts. Do not edit.
import { AcmeHealingIcon } from "../generated/icons/classes/healing-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-healing-icon", AcmeHealingIcon);
}
