// Generated by scripts/entries.ts. Do not edit.
import { AcmeHealthMetricsIcon } from "../generated/icons/classes/health-metrics-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-health-metrics-icon", AcmeHealthMetricsIcon);
}
