// Generated by scripts/entries.ts. Do not edit.
import { AcmeHeapSnapshotLargeIcon } from "../generated/icons/classes/heap-snapshot-large-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-heap-snapshot-large-icon", AcmeHeapSnapshotLargeIcon);
}
