// Generated by scripts/entries.ts. Do not edit.
import { AcmeHearingIcon } from "../generated/icons/classes/hearing-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-hearing-icon", AcmeHearingIcon);
}
