// Generated by scripts/entries.ts. Do not edit.
import { AcmeHexagonIcon } from "../generated/icons/classes/hexagon-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-hexagon-icon", AcmeHexagonIcon);
}
