// Generated by scripts/entries.ts. Do not edit.
import { AcmeHighlighterSize4Icon } from "../generated/icons/classes/highlighter-size-4-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-highlighter-size-4-icon", AcmeHighlighterSize4Icon);
}
