// Generated by scripts/entries.ts. Do not edit.
import { AcmeHighChairIcon } from "../generated/icons/classes/high-chair-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-high-chair-icon", AcmeHighChairIcon);
}
