// Generated by scripts/entries.ts. Do not edit.
import { AcmeHighQualityIcon } from "../generated/icons/classes/high-quality-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-high-quality-icon", AcmeHighQualityIcon);
}
