// Generated by scripts/entries.ts. Do not edit.
import { AcmeHistoryOffIcon } from "../generated/icons/classes/history-off-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-history-off-icon", AcmeHistoryOffIcon);
}
