// Generated by scripts/entries.ts. Do not edit.
import { AcmeHlsOffIcon } from "../generated/icons/classes/hls-off-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-hls-off-icon", AcmeHlsOffIcon);
}
