// Generated by scripts/entries.ts. Do not edit.
import { AcmeHomePinIcon } from "../generated/icons/classes/home-pin-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-home-pin-icon", AcmeHomePinIcon);
}
