// Generated by scripts/entries.ts. Do not edit.
import { AcmeHomeMiniIcon } from "../generated/icons/classes/home-mini-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-home-mini-icon", AcmeHomeMiniIcon);
}
