// Generated by scripts/entries.ts. Do not edit.
import { AcmeHomeMaxIcon } from "../generated/icons/classes/home-max-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-home-max-icon", AcmeHomeMaxIcon);
}
