// Generated by scripts/entries.ts. Do not edit.
import { AcmeHourglassArrowUpIcon } from "../generated/icons/classes/hourglass-arrow-up-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-hourglass-arrow-up-icon", AcmeHourglassArrowUpIcon);
}
