// Generated by scripts/entries.ts. Do not edit.
import { AcmeHouseWithShieldIcon } from "../generated/icons/classes/house-with-shield-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-house-with-shield-icon", AcmeHouseWithShieldIcon);
}
