// Generated by scripts/entries.ts. Do not edit.
import { AcmeHouseholdSuppliesIcon } from "../generated/icons/classes/household-supplies-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-household-supplies-icon", AcmeHouseholdSuppliesIcon);
}
