// Generated by scripts/entries.ts. Do not edit.
import { AcmeIflIcon } from "../generated/icons/classes/ifl-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-ifl-icon", AcmeIflIcon);
}
