// Generated by scripts/entries.ts. Do not edit.
import { AcmeImageSearchIcon } from "../generated/icons/classes/image-search-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-image-search-icon", AcmeImageSearchIcon);
}
