// Generated by scripts/entries.ts. Do not edit.
import { AcmeImageAspectRatioIcon } from "../generated/icons/classes/image-aspect-ratio-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-image-aspect-ratio-icon", AcmeImageAspectRatioIcon);
}
