// Generated by scripts/entries.ts. Do not edit.
import { AcmeImmunologyIcon } from "../generated/icons/classes/immunology-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-immunology-icon", AcmeImmunologyIcon);
}
