// Generated by scripts/entries.ts. Do not edit.
import { AcmeInactiveOrderIcon } from "../generated/icons/classes/inactive-order-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-inactive-order-icon", AcmeInactiveOrderIcon);
}
