// Generated by scripts/entries.ts. Do not edit.
import { AcmeInboxTextAsteriskIcon } from "../generated/icons/classes/inbox-text-asterisk-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-inbox-text-asterisk-icon", AcmeInboxTextAsteriskIcon);
}
