// Generated by scripts/entries.ts. Do not edit.
import { AcmeIndeterminateQuestionBoxIcon } from "../generated/icons/classes/indeterminate-question-box-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-indeterminate-question-box-icon", AcmeIndeterminateQuestionBoxIcon);
}
