// Generated by scripts/entries.ts. Do not edit.
import { AcmeInfraredIcon } from "../generated/icons/classes/infrared-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-infrared-icon", AcmeInfraredIcon);
}
