// Generated by scripts/entries.ts. Do not edit.
import { AcmeInstantMixIcon } from "../generated/icons/classes/instant-mix-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-instant-mix-icon", AcmeInstantMixIcon);
}
