// Generated by scripts/entries.ts. Do not edit.
import { AcmeInterestsIcon } from "../generated/icons/classes/interests-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-interests-icon", AcmeInterestsIcon);
}
