// Generated by scripts/entries.ts. Do not edit.
import { AcmeInteractiveSpaceIcon } from "../generated/icons/classes/interactive-space-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-interactive-space-icon", AcmeInteractiveSpaceIcon);
}
