// Generated by scripts/entries.ts. Do not edit.
import { AcmeItemContent } from "../components/item-content/item-content";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-item-content", AcmeItemContent);
}
