// Generated by scripts/entries.ts. Do not edit.
import { AcmeItem } from "../components/item/item";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-item", AcmeItem);
}
