// Generated by scripts/entries.ts. Do not edit.
import { AcmeItemDescription } from "../components/item-description/item-description";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-item-description", AcmeItemDescription);
}
