// Generated by scripts/entries.ts. Do not edit.
import { AcmeJapaneseFlagIcon } from "../generated/icons/classes/japanese-flag-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-japanese-flag-icon", AcmeJapaneseFlagIcon);
}
