// Generated by scripts/entries.ts. Do not edit.
import { AcmeJewelryIcon } from "../generated/icons/classes/jewelry-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-jewelry-icon", AcmeJewelryIcon);
}
