// Generated by scripts/entries.ts. Do not edit.
import { AcmeJumpToElementIcon } from "../generated/icons/classes/jump-to-element-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-jump-to-element-icon", AcmeJumpToElementIcon);
}
