// Generated by scripts/entries.ts. Do not edit.
import { AcmeKeyboardDoubleArrowDownIcon } from "../generated/icons/classes/keyboard-double-arrow-down-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-keyboard-double-arrow-down-icon", AcmeKeyboardDoubleArrowDownIcon);
}
