// Generated by scripts/entries.ts. Do not edit.
import { AcmeKeyboardLockIcon } from "../generated/icons/classes/keyboard-lock-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-keyboard-lock-icon", AcmeKeyboardLockIcon);
}
