// Generated by scripts/entries.ts. Do not edit.
import { AcmeKeyboardOnscreenIcon } from "../generated/icons/classes/keyboard-onscreen-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-keyboard-onscreen-icon", AcmeKeyboardOnscreenIcon);
}
