// Generated by scripts/entries.ts. Do not edit.
import { AcmeKeyboardCapslockBadgeIcon } from "../generated/icons/classes/keyboard-capslock-badge-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-keyboard-capslock-badge-icon", AcmeKeyboardCapslockBadgeIcon);
}
