// Generated by scripts/entries.ts. Do not edit.
import { AcmeKeyboardDoubleArrowLeftIcon } from "../generated/icons/classes/keyboard-double-arrow-left-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-keyboard-double-arrow-left-icon", AcmeKeyboardDoubleArrowLeftIcon);
}
