// Generated by scripts/entries.ts. Do not edit.
import { AcmeKeyboardArrowRightIcon } from "../generated/icons/classes/keyboard-arrow-right-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-keyboard-arrow-right-icon", AcmeKeyboardArrowRightIcon);
}
