// Generated by scripts/entries.ts. Do not edit.
import { AcmeLabPanelIcon } from "../generated/icons/classes/lab-panel-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-lab-panel-icon", AcmeLabPanelIcon);
}
