// Generated by scripts/entries.ts. Do not edit.
import { AcmeLanguageSpanishIcon } from "../generated/icons/classes/language-spanish-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-language-spanish-icon", AcmeLanguageSpanishIcon);
}
