// Generated by scripts/entries.ts. Do not edit.
import { AcmeLegend } from "../components/legend/legend";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-legend", AcmeLegend);
}
