// Generated by scripts/entries.ts. Do not edit.
import { AcmeLensIcon } from "../generated/icons/classes/lens-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-lens-icon", AcmeLensIcon);
}
