// Generated by scripts/entries.ts. Do not edit.
import { AcmeLightbulbIcon } from "../generated/icons/classes/lightbulb-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-lightbulb-icon", AcmeLightbulbIcon);
}
