// Generated by scripts/entries.ts. Do not edit.
import { AcmeList } from "../components/list/list";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-list", AcmeList);
}
