// Generated by scripts/entries.ts. Do not edit.
import { AcmeLivingIcon } from "../generated/icons/classes/living-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-living-icon", AcmeLivingIcon);
}
