// Generated by scripts/entries.ts. Do not edit.
import { AcmeLocalAtmIcon } from "../generated/icons/classes/local-atm-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-local-atm-icon", AcmeLocalAtmIcon);
}
