// Generated by scripts/entries.ts. Do not edit.
import { AcmeLocalDiningIcon } from "../generated/icons/classes/local-dining-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-local-dining-icon", AcmeLocalDiningIcon);
}
