// Generated by scripts/entries.ts. Do not edit.
import { AcmeLocalCafeIcon } from "../generated/icons/classes/local-cafe-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-local-cafe-icon", AcmeLocalCafeIcon);
}
