// Generated by scripts/entries.ts. Do not edit.
import { AcmeLocalParkingIcon } from "../generated/icons/classes/local-parking-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-local-parking-icon", AcmeLocalParkingIcon);
}
