// Generated by scripts/entries.ts. Do not edit.
import { AcmeLocationCityIcon } from "../generated/icons/classes/location-city-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-location-city-icon", AcmeLocationCityIcon);
}
