// Generated by scripts/entries.ts. Do not edit.
import { AcmeLocalPoliceIcon } from "../generated/icons/classes/local-police-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-local-police-icon", AcmeLocalPoliceIcon);
}
