// Generated by scripts/entries.ts. Do not edit.
import { AcmeLockOpenRightIcon } from "../generated/icons/classes/lock-open-right-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-lock-open-right-icon", AcmeLockOpenRightIcon);
}
