// Generated by scripts/entries.ts. Do not edit.
import { AcmeLockIcon } from "../generated/icons/classes/lock-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-lock-icon", AcmeLockIcon);
}
