// Generated by scripts/entries.ts. Do not edit.
import { AcmeLuggageIcon } from "../generated/icons/classes/luggage-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-luggage-icon", AcmeLuggageIcon);
}
