// Generated by scripts/entries.ts. Do not edit.
import { AcmeMailOffIcon } from "../generated/icons/classes/mail-off-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-mail-off-icon", AcmeMailOffIcon);
}
