// Generated by scripts/entries.ts. Do not edit.
import { AcmeMan3Icon } from "../generated/icons/classes/man-3-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-man-3-icon", AcmeMan3Icon);
}
