// Generated by scripts/entries.ts. Do not edit.
import { AcmeMapSearchIcon } from "../generated/icons/classes/map-search-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-map-search-icon", AcmeMapSearchIcon);
}
