// Generated by scripts/entries.ts. Do not edit.
import { AcmeMarkEmailUnreadIcon } from "../generated/icons/classes/mark-email-unread-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-mark-email-unread-icon", AcmeMarkEmailUnreadIcon);
}
