// Generated by scripts/entries.ts. Do not edit.
import { register as register0 } from "./scroll-area";
import { register as register1 } from "./scroll-viewport";
import { AcmeMarkdown } from "../components/markdown/markdown";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  register0(registry);
  register1(registry);
  registerElement(registry, "acme-markdown", AcmeMarkdown);
}
