// Generated by scripts/entries.ts. Do not edit.
import { AcmeMarkdownCopyIcon } from "../generated/icons/classes/markdown-copy-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-markdown-copy-icon", AcmeMarkdownCopyIcon);
}
