// Generated by scripts/entries.ts. Do not edit.
import { AcmeMediaOutputIcon } from "../generated/icons/classes/media-output-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-media-output-icon", AcmeMediaOutputIcon);
}
