// Generated by scripts/entries.ts. Do not edit.
import { AcmeMedicalInformationIcon } from "../generated/icons/classes/medical-information-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-medical-information-icon", AcmeMedicalInformationIcon);
}
