// Generated by scripts/entries.ts. Do not edit.
import { register as register0 } from "./check-icon";
import { register as register1 } from "./chevron-right-icon";
import { AcmeMenuItem } from "../components/menu-item/menu-item";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  register0(registry);
  register1(registry);
  registerElement(registry, "acme-menu-item", AcmeMenuItem);
}
