// Generated by scripts/entries.ts. Do not edit.
import { AcmeMenuOpenIcon } from "../generated/icons/classes/menu-open-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-menu-open-icon", AcmeMenuOpenIcon);
}
