// Generated by scripts/entries.ts. Do not edit.
import { AcmeMicExternalOnIcon } from "../generated/icons/classes/mic-external-on-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-mic-external-on-icon", AcmeMicExternalOnIcon);
}
