// Generated by scripts/entries.ts. Do not edit.
import { AcmeMicNoiseCancelLowIcon } from "../generated/icons/classes/mic-noise-cancel-low-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-mic-noise-cancel-low-icon", AcmeMicNoiseCancelLowIcon);
}
