// Generated by scripts/entries.ts. Do not edit.
import { AcmeMicrowaveIcon } from "../generated/icons/classes/microwave-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-microwave-icon", AcmeMicrowaveIcon);
}
