// Generated by scripts/entries.ts. Do not edit.
import { AcmeMilitaryTechIcon } from "../generated/icons/classes/military-tech-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-military-tech-icon", AcmeMilitaryTechIcon);
}
