// Generated by scripts/entries.ts. Do not edit.
import { AcmeMobileCameraRearIcon } from "../generated/icons/classes/mobile-camera-rear-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-mobile-camera-rear-icon", AcmeMobileCameraRearIcon);
}
