// Generated by scripts/entries.ts. Do not edit.
import { AcmeMobileTapIcon } from "../generated/icons/classes/mobile-tap-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-mobile-tap-icon", AcmeMobileTapIcon);
}
