// Generated by scripts/entries.ts. Do not edit.
import { AcmeMobileCheckIcon } from "../generated/icons/classes/mobile-check-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-mobile-check-icon", AcmeMobileCheckIcon);
}
