// Generated by scripts/entries.ts. Do not edit.
import { AcmeMobileChargeIcon } from "../generated/icons/classes/mobile-charge-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-mobile-charge-icon", AcmeMobileChargeIcon);
}
