// Generated by scripts/entries.ts. Do not edit.
import { AcmeMobileScreenShareIcon } from "../generated/icons/classes/mobile-screen-share-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-mobile-screen-share-icon", AcmeMobileScreenShareIcon);
}
