// Generated by scripts/entries.ts. Do not edit.
import { AcmeModeStandbyIcon } from "../generated/icons/classes/mode-standby-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-mode-standby-icon", AcmeModeStandbyIcon);
}
