// Generated by scripts/entries.ts. Do not edit.
import { AcmeMonitorHeartIcon } from "../generated/icons/classes/monitor-heart-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-monitor-heart-icon", AcmeMonitorHeartIcon);
}
