// Generated by scripts/entries.ts. Do not edit.
import { AcmeMonitoringIcon } from "../generated/icons/classes/monitoring-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-monitoring-icon", AcmeMonitoringIcon);
}
