// Generated by scripts/entries.ts. Do not edit.
import { AcmeMonitorWeightIcon } from "../generated/icons/classes/monitor-weight-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-monitor-weight-icon", AcmeMonitorWeightIcon);
}
