// Generated by scripts/entries.ts. Do not edit.
import { AcmeMonitorWeightGainIcon } from "../generated/icons/classes/monitor-weight-gain-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-monitor-weight-gain-icon", AcmeMonitorWeightGainIcon);
}
