// Generated by scripts/entries.ts. Do not edit.
import { AcmeMoonStarsIcon } from "../generated/icons/classes/moon-stars-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-moon-stars-icon", AcmeMoonStarsIcon);
}
