// Generated by scripts/entries.ts. Do not edit.
import { AcmeMotionModeIcon } from "../generated/icons/classes/motion-mode-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-motion-mode-icon", AcmeMotionModeIcon);
}
