// Generated by scripts/entries.ts. Do not edit.
import { AcmeMotionSensorAlertIcon } from "../generated/icons/classes/motion-sensor-alert-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-motion-sensor-alert-icon", AcmeMotionSensorAlertIcon);
}
