// Generated by scripts/entries.ts. Do not edit.
import { AcmeMotorcycleIcon } from "../generated/icons/classes/motorcycle-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-motorcycle-icon", AcmeMotorcycleIcon);
}
