// Generated by scripts/entries.ts. Do not edit.
import { AcmeMountainFlagIcon } from "../generated/icons/classes/mountain-flag-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-mountain-flag-icon", AcmeMountainFlagIcon);
}
