// Generated by scripts/entries.ts. Do not edit.
import { AcmeMoveSelectionLeftIcon } from "../generated/icons/classes/move-selection-left-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-move-selection-left-icon", AcmeMoveSelectionLeftIcon);
}
