// Generated by scripts/entries.ts. Do not edit.
import { AcmeMoveGroupIcon } from "../generated/icons/classes/move-group-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-move-group-icon", AcmeMoveGroupIcon);
}
