// Generated by scripts/entries.ts. Do not edit.
import { AcmeMpIcon } from "../generated/icons/classes/mp-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-mp-icon", AcmeMpIcon);
}
