// Generated by scripts/entries.ts. Do not edit.
import { AcmeMusicNoteIcon } from "../generated/icons/classes/music-note-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-music-note-icon", AcmeMusicNoteIcon);
}
