// Generated by scripts/entries.ts. Do not edit.
import { AcmeMyLocationIcon } from "../generated/icons/classes/my-location-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-my-location-icon", AcmeMyLocationIcon);
}
