// Generated by scripts/entries.ts. Do not edit.
import { AcmeNearMeIcon } from "../generated/icons/classes/near-me-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-near-me-icon", AcmeNearMeIcon);
}
