// Generated by scripts/entries.ts. Do not edit.
import { AcmeNestCamIqIcon } from "../generated/icons/classes/nest-cam-iq-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-nest-cam-iq-icon", AcmeNestCamIqIcon);
}
