// Generated by scripts/entries.ts. Do not edit.
import { AcmeNestDisplayIcon } from "../generated/icons/classes/nest-display-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-nest-display-icon", AcmeNestDisplayIcon);
}
