// Generated by scripts/entries.ts. Do not edit.
import { AcmeNestMultiRoomIcon } from "../generated/icons/classes/nest-multi-room-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-nest-multi-room-icon", AcmeNestMultiRoomIcon);
}
