// Generated by scripts/entries.ts. Do not edit.
import { AcmeNestHeatLinkGen3Icon } from "../generated/icons/classes/nest-heat-link-gen-3-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-nest-heat-link-gen-3-icon", AcmeNestHeatLinkGen3Icon);
}
