// Generated by scripts/entries.ts. Do not edit.
import { AcmeNestFoundSavingsIcon } from "../generated/icons/classes/nest-found-savings-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-nest-found-savings-icon", AcmeNestFoundSavingsIcon);
}
