// Generated by scripts/entries.ts. Do not edit.
import { AcmeNestThermostatGen3Icon } from "../generated/icons/classes/nest-thermostat-gen-3-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-nest-thermostat-gen-3-icon", AcmeNestThermostatGen3Icon);
}
