// Generated by scripts/entries.ts. Do not edit.
import { AcmeNestProtectIcon } from "../generated/icons/classes/nest-protect-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-nest-protect-icon", AcmeNestProtectIcon);
}
