// Generated by scripts/entries.ts. Do not edit.
import { AcmeNestThermostatSensorIcon } from "../generated/icons/classes/nest-thermostat-sensor-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-nest-thermostat-sensor-icon", AcmeNestThermostatSensorIcon);
}
