// Generated by scripts/entries.ts. Do not edit.
import { AcmeNetworkIntelligenceIcon } from "../generated/icons/classes/network-intelligence-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-network-intelligence-icon", AcmeNetworkIntelligenceIcon);
}
