// Generated by scripts/entries.ts. Do not edit.
import { AcmeNetworkWifi3BarLockedIcon } from "../generated/icons/classes/network-wifi-3-bar-locked-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-network-wifi-3-bar-locked-icon", AcmeNetworkWifi3BarLockedIcon);
}
