// Generated by scripts/entries.ts. Do not edit.
import { AcmeNightSightMaxIcon } from "../generated/icons/classes/night-sight-max-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-night-sight-max-icon", AcmeNightSightMaxIcon);
}
