// Generated by scripts/entries.ts. Do not edit.
import { AcmeNoSoundIcon } from "../generated/icons/classes/no-sound-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-no-sound-icon", AcmeNoSoundIcon);
}
