// Generated by scripts/entries.ts. Do not edit.
import { AcmeNoteStackAddIcon } from "../generated/icons/classes/note-stack-add-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-note-stack-add-icon", AcmeNoteStackAddIcon);
}
