// Generated by scripts/entries.ts. Do not edit.
import { AcmeNoteAltIcon } from "../generated/icons/classes/note-alt-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-note-alt-icon", AcmeNoteAltIcon);
}
