// Generated by scripts/entries.ts. Do not edit.
import { AcmeNotificationAddIcon } from "../generated/icons/classes/notification-add-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-notification-add-icon", AcmeNotificationAddIcon);
}
