// Generated by scripts/entries.ts. Do not edit.
import { AcmeNotificationsUnreadIcon } from "../generated/icons/classes/notifications-unread-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-notifications-unread-icon", AcmeNotificationsUnreadIcon);
}
