// Generated by scripts/entries.ts. Do not edit.
import { register as register0 } from "./add-icon";
import { AcmeNumberInputIncrement } from "../components/number-input-increment/number-input-increment";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  register0(registry);
  registerElement(registry, "acme-number-input-increment", AcmeNumberInputIncrement);
}
