// Generated by scripts/entries.ts. Do not edit.
import { AcmeNutritionIcon } from "../generated/icons/classes/nutrition-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-nutrition-icon", AcmeNutritionIcon);
}
