// Generated by scripts/entries.ts. Do not edit.
import { AcmeOdtIcon } from "../generated/icons/classes/odt-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-odt-icon", AcmeOdtIcon);
}
