// Generated by scripts/entries.ts. Do not edit.
import { AcmeOfflineShareIcon } from "../generated/icons/classes/offline-share-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-offline-share-icon", AcmeOfflineShareIcon);
}
