// Generated by scripts/entries.ts. Do not edit.
import { AcmeOfflinePinOffIcon } from "../generated/icons/classes/offline-pin-off-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-offline-pin-off-icon", AcmeOfflinePinOffIcon);
}
