// Generated by scripts/entries.ts. Do not edit.
import { AcmeOilBarrelIcon } from "../generated/icons/classes/oil-barrel-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-oil-barrel-icon", AcmeOilBarrelIcon);
}
