// Generated by scripts/entries.ts. Do not edit.
import { AcmeOtherAdmissionIcon } from "../generated/icons/classes/other-admission-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-other-admission-icon", AcmeOtherAdmissionIcon);
}
