// Generated by scripts/entries.ts. Do not edit.
import { AcmeOutboxAltIcon } from "../generated/icons/classes/outbox-alt-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-outbox-alt-icon", AcmeOutboxAltIcon);
}
