// Generated by scripts/entries.ts. Do not edit.
import { AcmeOutboundIcon } from "../generated/icons/classes/outbound-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-outbound-icon", AcmeOutboundIcon);
}
