// Generated by scripts/entries.ts. Do not edit.
import { AcmeOutletIcon } from "../generated/icons/classes/outlet-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-outlet-icon", AcmeOutletIcon);
}
