// Generated by scripts/entries.ts. Do not edit.
import { AcmePagesIcon } from "../generated/icons/classes/pages-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-pages-icon", AcmePagesIcon);
}
