// Generated by scripts/entries.ts. Do not edit.
import { AcmePanZoomIcon } from "../generated/icons/classes/pan-zoom-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-pan-zoom-icon", AcmePanZoomIcon);
}
