// Generated by scripts/entries.ts. Do not edit.
import { AcmePanoramaIcon } from "../generated/icons/classes/panorama-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-panorama-icon", AcmePanoramaIcon);
}
