// Generated by scripts/entries.ts. Do not edit.
import { AcmePasswordIcon } from "../generated/icons/classes/password-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-password-icon", AcmePasswordIcon);
}
