// Generated by scripts/entries.ts. Do not edit.
import { AcmePauseIcon } from "../generated/icons/classes/pause-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-pause-icon", AcmePauseIcon);
}
