// Generated by scripts/entries.ts. Do not edit.
import { AcmePauseCircleIcon } from "../generated/icons/classes/pause-circle-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-pause-circle-icon", AcmePauseCircleIcon);
}
