// Generated by scripts/entries.ts. Do not edit.
import { AcmePentagonIcon } from "../generated/icons/classes/pentagon-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-pentagon-icon", AcmePentagonIcon);
}
