// Generated by scripts/entries.ts. Do not edit.
import { AcmePermDataSettingIcon } from "../generated/icons/classes/perm-data-setting-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-perm-data-setting-icon", AcmePermDataSettingIcon);
}
