// Generated by scripts/entries.ts. Do not edit.
import { AcmePersonCancelIcon } from "../generated/icons/classes/person-cancel-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-person-cancel-icon", AcmePersonCancelIcon);
}
