// Generated by scripts/entries.ts. Do not edit.
import { AcmePersonCheckIcon } from "../generated/icons/classes/person-check-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-person-check-icon", AcmePersonCheckIcon);
}
