// Generated by scripts/entries.ts. Do not edit.
import { AcmePersonAddIcon } from "../generated/icons/classes/person-add-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-person-add-icon", AcmePersonAddIcon);
}
