// Generated by scripts/entries.ts. Do not edit.
import { AcmePhonelinkRingIcon } from "../generated/icons/classes/phonelink-ring-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-phonelink-ring-icon", AcmePhonelinkRingIcon);
}
