// Generated by scripts/entries.ts. Do not edit.
import { AcmePhonePausedIcon } from "../generated/icons/classes/phone-paused-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-phone-paused-icon", AcmePhonePausedIcon);
}
