// Generated by scripts/entries.ts. Do not edit.
import { AcmePhonelinkRingOffIcon } from "../generated/icons/classes/phonelink-ring-off-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-phonelink-ring-off-icon", AcmePhonelinkRingOffIcon);
}
