// Generated by scripts/entries.ts. Do not edit.
import { AcmePhotoAlbumIcon } from "../generated/icons/classes/photo-album-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-photo-album-icon", AcmePhotoAlbumIcon);
}
