// Generated by scripts/entries.ts. Do not edit.
import { AcmePhotoAutoMergeIcon } from "../generated/icons/classes/photo-auto-merge-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-photo-auto-merge-icon", AcmePhotoAutoMergeIcon);
}
