// Generated by scripts/entries.ts. Do not edit.
import { AcmePhotoSizeSelectSmallIcon } from "../generated/icons/classes/photo-size-select-small-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-photo-size-select-small-icon", AcmePhotoSizeSelectSmallIcon);
}
