// Generated by scripts/entries.ts. Do not edit.
import { AcmePhotoCameraIcon } from "../generated/icons/classes/photo-camera-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-photo-camera-icon", AcmePhotoCameraIcon);
}
