// Generated by scripts/entries.ts. Do not edit.
import { AcmePipExitIcon } from "../generated/icons/classes/pip-exit-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-pip-exit-icon", AcmePipExitIcon);
}
