// Generated by scripts/entries.ts. Do not edit.
import { AcmePlaneContrailsIcon } from "../generated/icons/classes/plane-contrails-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-plane-contrails-icon", AcmePlaneContrailsIcon);
}
