// Generated by scripts/entries.ts. Do not edit.
import { AcmePlannerReviewIcon } from "../generated/icons/classes/planner-review-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-planner-review-icon", AcmePlannerReviewIcon);
}
