// Generated by scripts/entries.ts. Do not edit.
import { AcmePlayForWorkIcon } from "../generated/icons/classes/play-for-work-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-play-for-work-icon", AcmePlayForWorkIcon);
}
