// Generated by scripts/entries.ts. Do not edit.
import { AcmePointScanIcon } from "../generated/icons/classes/point-scan-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-point-scan-icon", AcmePointScanIcon);
}
