// Generated by scripts/entries.ts. Do not edit.
import { AcmePottedPlantIcon } from "../generated/icons/classes/potted-plant-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-potted-plant-icon", AcmePottedPlantIcon);
}
