// Generated by scripts/entries.ts. Do not edit.
import { AcmePowerInputIcon } from "../generated/icons/classes/power-input-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-power-input-icon", AcmePowerInputIcon);
}
