// Generated by scripts/entries.ts. Do not edit.
import { AcmePrayerTimesIcon } from "../generated/icons/classes/prayer-times-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-prayer-times-icon", AcmePrayerTimesIcon);
}
