// Generated by scripts/entries.ts. Do not edit.
import { AcmePrintAddIcon } from "../generated/icons/classes/print-add-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-print-add-icon", AcmePrintAddIcon);
}
