// Generated by scripts/entries.ts. Do not edit.
import { AcmePriorityHighIcon } from "../generated/icons/classes/priority-high-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-priority-high-icon", AcmePriorityHighIcon);
}
