// Generated by scripts/entries.ts. Do not edit.
import { AcmeProcedureIcon } from "../generated/icons/classes/procedure-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-procedure-icon", AcmeProcedureIcon);
}
