// Generated by scripts/entries.ts. Do not edit.
import { AcmePropaneIcon } from "../generated/icons/classes/propane-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-propane-icon", AcmePropaneIcon);
}
