// Generated by scripts/entries.ts. Do not edit.
import { AcmePublicIcon } from "../generated/icons/classes/public-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-public-icon", AcmePublicIcon);
}
