// Generated by scripts/entries.ts. Do not edit.
import { AcmeQrCodeScannerIcon } from "../generated/icons/classes/qr-code-scanner-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-qr-code-scanner-icon", AcmeQrCodeScannerIcon);
}
