// Generated by scripts/entries.ts. Do not edit.
import { AcmeQuickReferenceAllIcon } from "../generated/icons/classes/quick-reference-all-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-quick-reference-all-icon", AcmeQuickReferenceAllIcon);
}
