// Generated by scripts/entries.ts. Do not edit.
import { AcmeRainySnowIcon } from "../generated/icons/classes/rainy-snow-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-rainy-snow-icon", AcmeRainySnowIcon);
}
