// Generated by scripts/entries.ts. Do not edit.
import { AcmeRearCameraIcon } from "../generated/icons/classes/rear-camera-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-rear-camera-icon", AcmeRearCameraIcon);
}
