// Generated by scripts/entries.ts. Do not edit.
import { AcmeRebaseEditIcon } from "../generated/icons/classes/rebase-edit-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-rebase-edit-icon", AcmeRebaseEditIcon);
}
