// Generated by scripts/entries.ts. Do not edit.
import { AcmeReceiptLongOffIcon } from "../generated/icons/classes/receipt-long-off-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-receipt-long-off-icon", AcmeReceiptLongOffIcon);
}
