// Generated by scripts/entries.ts. Do not edit.
import { AcmeRecentPatientIcon } from "../generated/icons/classes/recent-patient-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-recent-patient-icon", AcmeRecentPatientIcon);
}
