// Generated by scripts/entries.ts. Do not edit.
import { AcmeReceiptIcon } from "../generated/icons/classes/receipt-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-receipt-icon", AcmeReceiptIcon);
}
