// Generated by scripts/entries.ts. Do not edit.
import { AcmeReminderIcon } from "../generated/icons/classes/reminder-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-reminder-icon", AcmeReminderIcon);
}
