// Generated by scripts/entries.ts. Do not edit.
import { AcmeReplaceAudioIcon } from "../generated/icons/classes/replace-audio-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-replace-audio-icon", AcmeReplaceAudioIcon);
}
