// Generated by scripts/entries.ts. Do not edit.
import { AcmeReplay5Icon } from "../generated/icons/classes/replay-5-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-replay-5-icon", AcmeReplay5Icon);
}
