// Generated by scripts/entries.ts. Do not edit.
import { AcmeReplyIcon } from "../generated/icons/classes/reply-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-reply-icon", AcmeReplyIcon);
}
