// Generated by scripts/entries.ts. Do not edit.
import { AcmeReportOffIcon } from "../generated/icons/classes/report-off-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-report-off-icon", AcmeReportOffIcon);
}
