// Generated by scripts/entries.ts. Do not edit.
import { AcmeResetFocusIcon } from "../generated/icons/classes/reset-focus-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-reset-focus-icon", AcmeResetFocusIcon);
}
