// Generated by scripts/entries.ts. Do not edit.
import { AcmeResetTvIcon } from "../generated/icons/classes/reset-tv-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-reset-tv-icon", AcmeResetTvIcon);
}
