// Generated by scripts/entries.ts. Do not edit.
import { AcmeResponsiveLayoutIcon } from "../generated/icons/classes/responsive-layout-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-responsive-layout-icon", AcmeResponsiveLayoutIcon);
}
