// Generated by scripts/entries.ts. Do not edit.
import { AcmeRightPanelOpenIcon } from "../generated/icons/classes/right-panel-open-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-right-panel-open-icon", AcmeRightPanelOpenIcon);
}
