// Generated by scripts/entries.ts. Do not edit.
import { AcmeRobotIcon } from "../generated/icons/classes/robot-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-robot-icon", AcmeRobotIcon);
}
