// Generated by scripts/entries.ts. Do not edit.
import { AcmeRocketLaunchIcon } from "../generated/icons/classes/rocket-launch-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-rocket-launch-icon", AcmeRocketLaunchIcon);
}
