// Generated by scripts/entries.ts. Do not edit.
import { AcmeRoomPreferencesIcon } from "../generated/icons/classes/room-preferences-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-room-preferences-icon", AcmeRoomPreferencesIcon);
}
