// Generated by scripts/entries.ts. Do not edit.
import { AcmeRotate90DegreesCwIcon } from "../generated/icons/classes/rotate-90-degrees-cw-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-rotate-90-degrees-cw-icon", AcmeRotate90DegreesCwIcon);
}
