// Generated by scripts/entries.ts. Do not edit.
import { AcmeRuleFolderIcon } from "../generated/icons/classes/rule-folder-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-rule-folder-icon", AcmeRuleFolderIcon);
}
