// Generated by scripts/entries.ts. Do not edit.
import { AcmeSaunaIcon } from "../generated/icons/classes/sauna-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-sauna-icon", AcmeSaunaIcon);
}
