// Generated by scripts/entries.ts. Do not edit.
import { AcmeSaveIcon } from "../generated/icons/classes/save-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-save-icon", AcmeSaveIcon);
}
