// Generated by scripts/entries.ts. Do not edit.
import { AcmeScaleIcon } from "../generated/icons/classes/scale-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-scale-icon", AcmeScaleIcon);
}
