// Generated by scripts/entries.ts. Do not edit.
import { AcmeScanIcon } from "../generated/icons/classes/scan-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-scan-icon", AcmeScanIcon);
}
