// Generated by scripts/entries.ts. Do not edit.
import { AcmeScatterPlotIcon } from "../generated/icons/classes/scatter-plot-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-scatter-plot-icon", AcmeScatterPlotIcon);
}
