// Generated by scripts/entries.ts. Do not edit.
import { AcmeScienceOffIcon } from "../generated/icons/classes/science-off-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-science-off-icon", AcmeScienceOffIcon);
}
