// Generated by scripts/entries.ts. Do not edit.
import { AcmeSdCardIcon } from "../generated/icons/classes/sd-card-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-sd-card-icon", AcmeSdCardIcon);
}
