// Generated by scripts/entries.ts. Do not edit.
import { AcmeSdkIcon } from "../generated/icons/classes/sdk-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-sdk-icon", AcmeSdkIcon);
}
