// Generated by scripts/entries.ts. Do not edit.
import { AcmeSearchCheck2Icon } from "../generated/icons/classes/search-check-2-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-search-check-2-icon", AcmeSearchCheck2Icon);
}
