// Generated by scripts/entries.ts. Do not edit.
import { AcmeSearchIcon } from "../generated/icons/classes/search-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-search-icon", AcmeSearchIcon);
}
