// Generated by scripts/entries.ts. Do not edit.
import { AcmeSeatReadIcon } from "../generated/icons/classes/seat-read-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-seat-read-icon", AcmeSeatReadIcon);
}
