// Generated by scripts/entries.ts. Do not edit.
import { AcmeSelectWindowIcon } from "../generated/icons/classes/select-window-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-select-window-icon", AcmeSelectWindowIcon);
}
