// Generated by scripts/entries.ts. Do not edit.
import { AcmeSelfCareIcon } from "../generated/icons/classes/self-care-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-self-care-icon", AcmeSelfCareIcon);
}
