// Generated by scripts/entries.ts. Do not edit.
import { AcmeSensorsKrxOffIcon } from "../generated/icons/classes/sensors-krx-off-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-sensors-krx-off-icon", AcmeSensorsKrxOffIcon);
}
