// Generated by scripts/entries.ts. Do not edit.
import { AcmeSeparator } from "../components/separator/separator";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-separator", AcmeSeparator);
}
