// Generated by scripts/entries.ts. Do not edit.
import { AcmeSettingsBackupRestoreIcon } from "../generated/icons/classes/settings-backup-restore-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-settings-backup-restore-icon", AcmeSettingsBackupRestoreIcon);
}
