// Generated by scripts/entries.ts. Do not edit.
import { AcmeSettingsInputAntennaIcon } from "../generated/icons/classes/settings-input-antenna-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-settings-input-antenna-icon", AcmeSettingsInputAntennaIcon);
}
