// Generated by scripts/entries.ts. Do not edit.
import { AcmeSettingsPowerIcon } from "../generated/icons/classes/settings-power-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-settings-power-icon", AcmeSettingsPowerIcon);
}
