// Generated by scripts/entries.ts. Do not edit.
import { AcmeShapeLineIcon } from "../generated/icons/classes/shape-line-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-shape-line-icon", AcmeShapeLineIcon);
}
