// Generated by scripts/entries.ts. Do not edit.
import { AcmeShelfPositionIcon } from "../generated/icons/classes/shelf-position-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-shelf-position-icon", AcmeShelfPositionIcon);
}
