// Generated by scripts/entries.ts. Do not edit.
import { AcmeShieldQuestionIcon } from "../generated/icons/classes/shield-question-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-shield-question-icon", AcmeShieldQuestionIcon);
}
