// Generated by scripts/entries.ts. Do not edit.
import { AcmeShoppingCartIcon } from "../generated/icons/classes/shopping-cart-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-shopping-cart-icon", AcmeShoppingCartIcon);
}
