// Generated by scripts/entries.ts. Do not edit.
import { AcmeShortStayIcon } from "../generated/icons/classes/short-stay-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-short-stay-icon", AcmeShortStayIcon);
}
