// Generated by scripts/entries.ts. Do not edit.
import { register as register0 } from "./expand-more-icon";
import { register as register1 } from "./spinner";
import { AcmeShowMore } from "../components/show-more/show-more";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  register0(registry);
  register1(registry);
  registerElement(registry, "acme-show-more", AcmeShowMore);
}
