// Generated by scripts/entries.ts. Do not edit.
import { AcmeSignalWifiOffIcon } from "../generated/icons/classes/signal-wifi-off-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-signal-wifi-off-icon", AcmeSignalWifiOffIcon);
}
