// Generated by scripts/entries.ts. Do not edit.
import { AcmeSignalCellularAlt1BarIcon } from "../generated/icons/classes/signal-cellular-alt-1-bar-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-signal-cellular-alt-1-bar-icon", AcmeSignalCellularAlt1BarIcon);
}
