// Generated by scripts/entries.ts. Do not edit.
import { AcmeSimCardLockIcon } from "../generated/icons/classes/sim-card-lock-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-sim-card-lock-icon", AcmeSimCardLockIcon);
}
