// Generated by scripts/entries.ts. Do not edit.
import { AcmeSipIcon } from "../generated/icons/classes/sip-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-sip-icon", AcmeSipIcon);
}
