// Generated by scripts/entries.ts. Do not edit.
import { AcmeSmartToyIcon } from "../generated/icons/classes/smart-toy-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-smart-toy-icon", AcmeSmartToyIcon);
}
