// Generated by scripts/entries.ts. Do not edit.
import { AcmeSmartButtonIcon } from "../generated/icons/classes/smart-button-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-smart-button-icon", AcmeSmartButtonIcon);
}
