// Generated by scripts/entries.ts. Do not edit.
import { AcmeSmbShareIcon } from "../generated/icons/classes/smb-share-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-smb-share-icon", AcmeSmbShareIcon);
}
