// Generated by scripts/entries.ts. Do not edit.
import { AcmeSmokeFreeIcon } from "../generated/icons/classes/smoke-free-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-smoke-free-icon", AcmeSmokeFreeIcon);
}
