// Generated by scripts/entries.ts. Do not edit.
import { AcmeSnailIcon } from "../generated/icons/classes/snail-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-snail-icon", AcmeSnailIcon);
}
