// Generated by scripts/entries.ts. Do not edit.
import { AcmeSpaIcon } from "../generated/icons/classes/spa-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-spa-icon", AcmeSpaIcon);
}
