// Generated by scripts/entries.ts. Do not edit.
import { AcmeSpatialAudioOffIcon } from "../generated/icons/classes/spatial-audio-off-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-spatial-audio-off-icon", AcmeSpatialAudioOffIcon);
}
