// Generated by scripts/entries.ts. Do not edit.
import { AcmeSpeed12Icon } from "../generated/icons/classes/speed-1-2-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-speed-1-2-icon", AcmeSpeed12Icon);
}
