// Generated by scripts/entries.ts. Do not edit.
import { AcmeSpeed4Icon } from "../generated/icons/classes/speed-4-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-speed-4-icon", AcmeSpeed4Icon);
}
