// Generated by scripts/entries.ts. Do not edit.
import { AcmeSpeed2Icon } from "../generated/icons/classes/speed-2-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-speed-2-icon", AcmeSpeed2Icon);
}
