// Generated by scripts/entries.ts. Do not edit.
import { AcmeSplitscreenLandscapeAddIcon } from "../generated/icons/classes/splitscreen-landscape-add-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-splitscreen-landscape-add-icon", AcmeSplitscreenLandscapeAddIcon);
}
