// Generated by scripts/entries.ts. Do not edit.
import { AcmeSplitscreenLandscapeIcon } from "../generated/icons/classes/splitscreen-landscape-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-splitscreen-landscape-icon", AcmeSplitscreenLandscapeIcon);
}
