// Generated by scripts/entries.ts. Do not edit.
import { AcmeSportsAndOutdoorsIcon } from "../generated/icons/classes/sports-and-outdoors-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-sports-and-outdoors-icon", AcmeSportsAndOutdoorsIcon);
}
