// Generated by scripts/entries.ts. Do not edit.
import { AcmeSportsMartialArtsIcon } from "../generated/icons/classes/sports-martial-arts-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-sports-martial-arts-icon", AcmeSportsMartialArtsIcon);
}
