// Generated by scripts/entries.ts. Do not edit.
import { AcmeSportsGolfIcon } from "../generated/icons/classes/sports-golf-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-sports-golf-icon", AcmeSportsGolfIcon);
}
