// Generated by scripts/entries.ts. Do not edit.
import { AcmeSportsTennisIcon } from "../generated/icons/classes/sports-tennis-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-sports-tennis-icon", AcmeSportsTennisIcon);
}
