// Generated by scripts/entries.ts. Do not edit.
import { AcmeSportsBarIcon } from "../generated/icons/classes/sports-bar-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-sports-bar-icon", AcmeSportsBarIcon);
}
