// Generated by scripts/entries.ts. Do not edit.
import { AcmeSquareCircleIcon } from "../generated/icons/classes/square-circle-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-square-circle-icon", AcmeSquareCircleIcon);
}
