// Generated by scripts/entries.ts. Do not edit.
import { AcmeStacksIcon } from "../generated/icons/classes/stacks-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-stacks-icon", AcmeStacksIcon);
}
