// Generated by scripts/entries.ts. Do not edit.
import { AcmeStartIcon } from "../generated/icons/classes/start-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-start-icon", AcmeStartIcon);
}
