// Generated by scripts/entries.ts. Do not edit.
import { AcmeStatMinus3Icon } from "../generated/icons/classes/stat-minus-3-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-stat-minus-3-icon", AcmeStatMinus3Icon);
}
