// Generated by scripts/entries.ts. Do not edit.
import { AcmeStat3Icon } from "../generated/icons/classes/stat-3-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-stat-3-icon", AcmeStat3Icon);
}
