// Generated by scripts/entries.ts. Do not edit.
import { AcmeStat } from "../components/stat/stat";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-stat", AcmeStat);
}
