// Generated by scripts/entries.ts. Do not edit.
import { register as register0 } from "./spinner";
import { AcmeStepsNext } from "../components/steps-next/steps-next";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  register0(registry);
  registerElement(registry, "acme-steps-next", AcmeStepsNext);
}
