// Generated by scripts/entries.ts. Do not edit.
import { AcmeStethoscopeCheckIcon } from "../generated/icons/classes/stethoscope-check-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-stethoscope-check-icon", AcmeStethoscopeCheckIcon);
}
