// Generated by scripts/entries.ts. Do not edit.
import { AcmeStylusFountainPenIcon } from "../generated/icons/classes/stylus-fountain-pen-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-stylus-fountain-pen-icon", AcmeStylusFountainPenIcon);
}
