// Generated by scripts/entries.ts. Do not edit.
import { AcmeStylusNoteIcon } from "../generated/icons/classes/stylus-note-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-stylus-note-icon", AcmeStylusNoteIcon);
}
