// Generated by scripts/entries.ts. Do not edit.
import { AcmeSubtitlesOffIcon } from "../generated/icons/classes/subtitles-off-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-subtitles-off-icon", AcmeSubtitlesOffIcon);
}
