// Generated by scripts/entries.ts. Do not edit.
import { AcmeSunnySnowingIcon } from "../generated/icons/classes/sunny-snowing-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-sunny-snowing-icon", AcmeSunnySnowingIcon);
}
