// Generated by scripts/entries.ts. Do not edit.
import { AcmeSwipeLeftAltIcon } from "../generated/icons/classes/swipe-left-alt-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-swipe-left-alt-icon", AcmeSwipeLeftAltIcon);
}
