// Generated by scripts/entries.ts. Do not edit.
import { AcmeSwipeLeftIcon } from "../generated/icons/classes/swipe-left-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-swipe-left-icon", AcmeSwipeLeftIcon);
}
