// Generated by scripts/entries.ts. Do not edit.
import { AcmeSwipeLeft2Icon } from "../generated/icons/classes/swipe-left-2-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-swipe-left-2-icon", AcmeSwipeLeft2Icon);
}
