// Generated by scripts/entries.ts. Do not edit.
import { AcmeSwipeDownAltIcon } from "../generated/icons/classes/swipe-down-alt-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-swipe-down-alt-icon", AcmeSwipeDownAltIcon);
}
