// Generated by scripts/entries.ts. Do not edit.
import { AcmeSwitchAccessShortcutAddIcon } from "../generated/icons/classes/switch-access-shortcut-add-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-switch-access-shortcut-add-icon", AcmeSwitchAccessShortcutAddIcon);
}
