// Generated by scripts/entries.ts. Do not edit.
import { AcmeTabNewRightIcon } from "../generated/icons/classes/tab-new-right-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-tab-new-right-icon", AcmeTabNewRightIcon);
}
