// Generated by scripts/entries.ts. Do not edit.
import { AcmeTabInactiveIcon } from "../generated/icons/classes/tab-inactive-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-tab-inactive-icon", AcmeTabInactiveIcon);
}
