// Generated by scripts/entries.ts. Do not edit.
import { AcmeTableLargeIcon } from "../generated/icons/classes/table-large-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-table-large-icon", AcmeTableLargeIcon);
}
