// Generated by scripts/entries.ts. Do not edit.
import { AcmeTabletAndroidIcon } from "../generated/icons/classes/tablet-android-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-tablet-android-icon", AcmeTabletAndroidIcon);
}
