// Generated by scripts/entries.ts. Do not edit.
import { AcmeTable } from "../components/table/table";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-table", AcmeTable);
}
