// Generated by scripts/entries.ts. Do not edit.
import { AcmeTerminalAddIcon } from "../generated/icons/classes/terminal-add-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-terminal-add-icon", AcmeTerminalAddIcon);
}
