// Generated by scripts/entries.ts. Do not edit.
import { AcmeTextureMinusIcon } from "../generated/icons/classes/texture-minus-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-texture-minus-icon", AcmeTextureMinusIcon);
}
