// Generated by scripts/entries.ts. Do not edit.
import { AcmeTextSelectStartIcon } from "../generated/icons/classes/text-select-start-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-text-select-start-icon", AcmeTextSelectStartIcon);
}
