// Generated by scripts/entries.ts. Do not edit.
import { AcmeTextRotationAngledownIcon } from "../generated/icons/classes/text-rotation-angledown-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-text-rotation-angledown-icon", AcmeTextRotationAngledownIcon);
}
