// Generated by scripts/entries.ts. Do not edit.
import { AcmeThreadUnreadIcon } from "../generated/icons/classes/thread-unread-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-thread-unread-icon", AcmeThreadUnreadIcon);
}
