// Generated by scripts/entries.ts. Do not edit.
import { AcmeThumbDownOffIcon } from "../generated/icons/classes/thumb-down-off-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-thumb-down-off-icon", AcmeThumbDownOffIcon);
}
