// Generated by scripts/entries.ts. Do not edit.
import { AcmeTibiaIcon } from "../generated/icons/classes/tibia-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-tibia-icon", AcmeTibiaIcon);
}
