// Generated by scripts/entries.ts. Do not edit.
import { AcmeTimerArrowUpIcon } from "../generated/icons/classes/timer-arrow-up-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-timer-arrow-up-icon", AcmeTimerArrowUpIcon);
}
