// Generated by scripts/entries.ts. Do not edit.
import { AcmeTimer10Icon } from "../generated/icons/classes/timer-10-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-timer-10-icon", AcmeTimer10Icon);
}
