// Generated by scripts/entries.ts. Do not edit.
import { AcmeTimer2Icon } from "../generated/icons/classes/timer-2-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-timer-2-icon", AcmeTimer2Icon);
}
