// Generated by scripts/entries.ts. Do not edit.
import { AcmeTimerOffIcon } from "../generated/icons/classes/timer-off-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-timer-off-icon", AcmeTimerOffIcon);
}
