// Generated by scripts/entries.ts. Do not edit.
import { AcmeToggleOnIcon } from "../generated/icons/classes/toggle-on-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-toggle-on-icon", AcmeToggleOnIcon);
}
