// Generated by scripts/entries.ts. Do not edit.
import { AcmeTooltip2Icon } from "../generated/icons/classes/tooltip-2-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-tooltip-2-icon", AcmeTooltip2Icon);
}
