// Generated by scripts/entries.ts. Do not edit.
import { AcmeToolbar } from "../components/toolbar/toolbar";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-toolbar", AcmeToolbar);
}
