// Generated by scripts/entries.ts. Do not edit.
import { AcmeTrackpadInput2Icon } from "../generated/icons/classes/trackpad-input-2-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-trackpad-input-2-icon", AcmeTrackpadInput2Icon);
}
