// Generated by scripts/entries.ts. Do not edit.
import { AcmeTrackpadInputIcon } from "../generated/icons/classes/trackpad-input-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-trackpad-input-icon", AcmeTrackpadInputIcon);
}
