// Generated by scripts/entries.ts. Do not edit.
import { AcmeTrafficIcon } from "../generated/icons/classes/traffic-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-traffic-icon", AcmeTrafficIcon);
}
