// Generated by scripts/entries.ts. Do not edit.
import { AcmeTrailLengthShortIcon } from "../generated/icons/classes/trail-length-short-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-trail-length-short-icon", AcmeTrailLengthShortIcon);
}
