// Generated by scripts/entries.ts. Do not edit.
import { AcmeTransitionSlideIcon } from "../generated/icons/classes/transition-slide-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-transition-slide-icon", AcmeTransitionSlideIcon);
}
