// Generated by scripts/entries.ts. Do not edit.
import { AcmeTrendingUpIcon } from "../generated/icons/classes/trending-up-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-trending-up-icon", AcmeTrendingUpIcon);
}
