// Generated by scripts/entries.ts. Do not edit.
import { AcmeTrophyIcon } from "../generated/icons/classes/trophy-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-trophy-icon", AcmeTrophyIcon);
}
