// Generated by scripts/entries.ts. Do not edit.
import { AcmeTurnSlightRightIcon } from "../generated/icons/classes/turn-slight-right-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-turn-slight-right-icon", AcmeTurnSlightRightIcon);
}
