// Generated by scripts/entries.ts. Do not edit.
import { AcmeTypeSpecimenIcon } from "../generated/icons/classes/type-specimen-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-type-specimen-icon", AcmeTypeSpecimenIcon);
}
