// Generated by scripts/entries.ts. Do not edit.
import { AcmeUndoIcon } from "../generated/icons/classes/undo-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-undo-icon", AcmeUndoIcon);
}
