// Generated by scripts/entries.ts. Do not edit.
import { AcmeUnknown2Icon } from "../generated/icons/classes/unknown-2-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-unknown-2-icon", AcmeUnknown2Icon);
}
