// Generated by scripts/entries.ts. Do not edit.
import { AcmeUnpublishedIcon } from "../generated/icons/classes/unpublished-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-unpublished-icon", AcmeUnpublishedIcon);
}
