// Generated by scripts/entries.ts. Do not edit.
import { AcmeUploadIcon } from "../generated/icons/classes/upload-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-upload-icon", AcmeUploadIcon);
}
