// Generated by scripts/entries.ts. Do not edit.
import { AcmeUpload2Icon } from "../generated/icons/classes/upload-2-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-upload-2-icon", AcmeUpload2Icon);
}
