// Generated by scripts/entries.ts. Do not edit.
import { AcmeVapingRoomsIcon } from "../generated/icons/classes/vaping-rooms-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-vaping-rooms-icon", AcmeVapingRoomsIcon);
}
