// Generated by scripts/entries.ts. Do not edit.
import { AcmeVariableAddIcon } from "../generated/icons/classes/variable-add-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-variable-add-icon", AcmeVariableAddIcon);
}
