// Generated by scripts/entries.ts. Do not edit.
import { AcmeVariableRemoveIcon } from "../generated/icons/classes/variable-remove-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-variable-remove-icon", AcmeVariableRemoveIcon);
}
