// Generated by scripts/entries.ts. Do not edit.
import { AcmeVerticalSplitIcon } from "../generated/icons/classes/vertical-split-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-vertical-split-icon", AcmeVerticalSplitIcon);
}
