// Generated by scripts/entries.ts. Do not edit.
import { AcmeVerticalAlignTopIcon } from "../generated/icons/classes/vertical-align-top-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-vertical-align-top-icon", AcmeVerticalAlignTopIcon);
}
