// Generated by scripts/entries.ts. Do not edit.
import { AcmeVerticalAlignBottomIcon } from "../generated/icons/classes/vertical-align-bottom-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-vertical-align-bottom-icon", AcmeVerticalAlignBottomIcon);
}
