// Generated by scripts/entries.ts. Do not edit.
import { AcmeViewArrayIcon } from "../generated/icons/classes/view-array-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-view-array-icon", AcmeViewArrayIcon);
}
