// Generated by scripts/entries.ts. Do not edit.
import { AcmeViewAppsIcon } from "../generated/icons/classes/view-apps-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-view-apps-icon", AcmeViewAppsIcon);
}
