// Generated by scripts/entries.ts. Do not edit.
import { AcmeViewQuiltIcon } from "../generated/icons/classes/view-quilt-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-view-quilt-icon", AcmeViewQuiltIcon);
}
