// Generated by scripts/entries.ts. Do not edit.
import { AcmeVisibilityIcon } from "../generated/icons/classes/visibility-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-visibility-icon", AcmeVisibilityIcon);
}
