// Generated by scripts/entries.ts. Do not edit.
import { AcmeVitalsIcon } from "../generated/icons/classes/vitals-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-vitals-icon", AcmeVitalsIcon);
}
