// Generated by scripts/entries.ts. Do not edit.
import { AcmeVoicemailIcon } from "../generated/icons/classes/voicemail-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-voicemail-icon", AcmeVoicemailIcon);
}
