// Generated by scripts/entries.ts. Do not edit.
import { AcmeVolcanoIcon } from "../generated/icons/classes/volcano-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-volcano-icon", AcmeVolcanoIcon);
}
