// Generated by scripts/entries.ts. Do not edit.
import { AcmeVolumeDownIcon } from "../generated/icons/classes/volume-down-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-volume-down-icon", AcmeVolumeDownIcon);
}
