// Generated by scripts/entries.ts. Do not edit.
import { AcmeWalletIcon } from "../generated/icons/classes/wallet-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-wallet-icon", AcmeWalletIcon);
}
