// Generated by scripts/entries.ts. Do not edit.
import { AcmeWallLampIcon } from "../generated/icons/classes/wall-lamp-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-wall-lamp-icon", AcmeWallLampIcon);
}
