// Generated by scripts/entries.ts. Do not edit.
import { AcmeWandStarsIcon } from "../generated/icons/classes/wand-stars-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-wand-stars-icon", AcmeWandStarsIcon);
}
