// Generated by scripts/entries.ts. Do not edit.
import { AcmeWandShineIcon } from "../generated/icons/classes/wand-shine-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-wand-shine-icon", AcmeWandShineIcon);
}
