// Generated by scripts/entries.ts. Do not edit.
import { AcmeWaterDoIcon } from "../generated/icons/classes/water-do-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-water-do-icon", AcmeWaterDoIcon);
}
