// Generated by scripts/entries.ts. Do not edit.
import { AcmeWaterPumpIcon } from "../generated/icons/classes/water-pump-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-water-pump-icon", AcmeWaterPumpIcon);
}
