// Generated by scripts/entries.ts. Do not edit.
import { AcmeWbSunnyIcon } from "../generated/icons/classes/wb-sunny-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-wb-sunny-icon", AcmeWbSunnyIcon);
}
