// Generated by scripts/entries.ts. Do not edit.
import { AcmeWeatherHailIcon } from "../generated/icons/classes/weather-hail-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-weather-hail-icon", AcmeWeatherHailIcon);
}
