// Generated by scripts/entries.ts. Do not edit.
import { AcmeWeatherSnowyIcon } from "../generated/icons/classes/weather-snowy-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-weather-snowy-icon", AcmeWeatherSnowyIcon);
}
