// Generated by scripts/entries.ts. Do not edit.
import { AcmeWeekendIcon } from "../generated/icons/classes/weekend-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-weekend-icon", AcmeWeekendIcon);
}
