// Generated by scripts/entries.ts. Do not edit.
import { AcmeWestIcon } from "../generated/icons/classes/west-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-west-icon", AcmeWestIcon);
}
