// Generated by scripts/entries.ts. Do not edit.
import { AcmeWifiNotificationIcon } from "../generated/icons/classes/wifi-notification-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-wifi-notification-icon", AcmeWifiNotificationIcon);
}
