// Generated by scripts/entries.ts. Do not edit.
import { AcmeWorkspacesOutlineIcon } from "../generated/icons/classes/workspaces-outline-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-workspaces-outline-icon", AcmeWorkspacesOutlineIcon);
}
