// Generated by scripts/entries.ts. Do not edit.
import { AcmeZoomOutIcon } from "../generated/icons/classes/zoom-out-icon";
import { registerElement } from "../shared/registration";

export function register(registry: CustomElementRegistry): void {
  registerElement(registry, "acme-zoom-out-icon", AcmeZoomOutIcon);
}
