// Generated by the style generator from the reference spec. Do not edit; edit the mapping and regenerate.
import { css } from "lit";
export const drawerCss = css`
  .drawer {
    pointer-events: auto;
    max-height: 80dvh;
    width: 100%;
    transform: translateY(var(--drawer-swipe-movement-y, 0px));
    overscroll-behavior: none;
    border-top-left-radius: var(--acme-marketing-radius);
    border-top-right-radius: var(--acme-marketing-radius);
    border: none;
    background: var(--ds-background-100);
    transition: transform 0.5s cubic-bezier(0.32, 0.72, 0, 1);
    outline-style: none;
    animation-duration: 0.4s;
    animation-timing-function: cubic-bezier(0.32, 0.72, 0, 1);
    -ms-scroll-chaining: none;
    max-width: 100%;
    min-height: 5dvh;
    box-shadow: var(--ds-shadow-menu);
    color: var(--ds-gray-1000);
    padding: 0;
    position: fixed;
    top: auto;
    bottom: 0;
    margin: 0 !important;
  }
  .drawer:where(.max) {
    height: 100%;
  }
  .drawer:where(:not(.noscroll)) {
    overflow-y: auto;
  }
  .drawer:where(.noscroll) {
    overflow-y: hidden;
  }
  .drawer[data-ending-style] {
    transform: translateY(100%);
  }
  .drawer[data-starting-style] {
    transform: translateY(100%);
  }
`;
