// Generated by scripts/split-css.ts from the audited house sheet. Do not edit.
import { css } from "lit";
export const drawerCss = css`
.drawer{position:fixed;left:0;right:0;bottom:0;z-index:110;background:var(--surface);border-radius:var(--r) var(--r) 0 0;box-shadow:var(--ds-shadow-menu);padding:48px;display:flex;flex-direction:column;gap:8px;max-height:92dvh;overflow:auto}
.drawer.static{position:static;max-height:none}
.drawer .title{font-size:18px;line-height:24px;font-weight:600;margin:0}
.drawer .body{font-size:14px;line-height:20px;margin:0}
.drawer .actions{display:flex;gap:8px;margin-top:16px}
.drawer-scrim{position:fixed;inset:0;background:var(--scrim-dark);z-index:109}
`;
