// Generated by the style generator from the reference spec. Do not edit; edit the mapping and regenerate.
import { css } from "lit";
import { registerProperties } from "../../base";

registerProperties([
  { name: "--acme-translate-x", syntax: "*", inherits: false, initialValue: "0" },
  { name: "--acme-translate-y", syntax: "*", inherits: false, initialValue: "0" },
  { name: "--acme-translate-z", syntax: "*", inherits: false, initialValue: "0" },
  { name: "--acme-scale-x", syntax: "*", inherits: false, initialValue: "1" },
  { name: "--acme-scale-y", syntax: "*", inherits: false, initialValue: "1" },
  { name: "--acme-scale-z", syntax: "*", inherits: false, initialValue: "1" },
  { name: "--acme-rotate-x", syntax: "*", inherits: false },
  { name: "--acme-rotate-y", syntax: "*", inherits: false },
  { name: "--acme-rotate-z", syntax: "*", inherits: false },
  { name: "--acme-skew-x", syntax: "*", inherits: false },
  { name: "--acme-skew-y", syntax: "*", inherits: false },
]);
export const videoCss = css`
  .video :where(.box) :where(.frame) :where(.controls) :where(.track) :where(progress) {
    pointer-events: none;
    position: absolute;
    top: calc(50% - 1px);
    left: 0;
    height: 0.25rem;
    width: 100%;
    overflow: hidden;
    border-radius: 5px;
    background-color: var(--ds-gray-1000);
  }
  .video :where(.box) :where(.frame) :where(.controls) :where(.track) :where(.handle) {
    pointer-events: none;
    position: absolute;
    top: calc(50% - 5px);
    width: 0.625rem;
    height: 0.625rem;
    translate: 0.25rem 1px;
    scale: 0% 0%;
    border-radius: 50%;
    background-color: var(--acme-foreground);
    transition-property: width, height, border-radius, transform, background-color;
    transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1);
    transition-duration: 0.1s;
    animation-duration: 0.1s;
    animation-timing-function: cubic-bezier(0.4, 0, 0.2, 1);
  }
  .video :where(.box) :where(.frame) :where(video) {
    position: absolute;
    top: 0;
    left: 0;
    height: 100%;
    width: 100%;
    cursor: pointer;
  }
  .video :where(.box) :where(.frame) :where(.controls) {
    position: absolute;
    bottom: 5%;
    display: flex;
    height: 3rem;
    width: 85%;
    align-items: center;
    border-radius: 0.375rem;
    background-color: var(--acme-background);
    padding-inline: 0.5rem;
    padding-block: 0;
    opacity: 0;
    box-shadow: var(--ds-shadow-tooltip);
    transition-property: all;
    transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1);
    transition-duration: 0.15s;
  }
  .video :where(.box) {
    position: relative;
    margin-inline: auto;
    margin-block: 0;
    width: var(--video-width);
    max-width: 100%;
  }
  .video :where(.box) :where(.frame) {
    position: relative;
    display: flex;
    justify-content: center;
  }
  .video :where(.box) :where(.frame) :where(.controls) :where(.track) {
    position: relative;
    margin-top: -1px;
    display: flex;
    flex: 1 0 auto;
    align-items: center;
  }
  .video {
    margin-inline: 0;
    margin-block: var(--video-margin);
    display: block;
    text-align: center;
  }
  .video :where(.box) :where(.frame) :where(.controls) :where(.play) {
    display: flex;
    width: 2.5rem;
    height: 2.5rem;
    flex: 0 0 40px;
    cursor: pointer;
    align-items: center;
    justify-content: center;
    border-style: solid;
    border-width: 0;
    background-color: #0000;
    padding: 0;
    outline-style: none;
  }
  .video :where(.box) :where(.frame) :where(.controls) :where(.track) :where(.scrub) {
    height: 18px;
    width: 100%;
    cursor: pointer;
    background-color: #0000;
    -webkit-tap-highlight-color: #0000;
  }
  .video :where(.box) :where(.frame) :where(.controls) :where(.current) {
    width: 60px;
    flex: none;
    padding-inline: 0.75rem;
    padding-block: 0;
    padding-left: 0;
    font-size: 13px;
    line-height: 2.5rem;
    font-variant-numeric: tabular-nums;
  }
  .video :where(.box) :where(.frame) :where(.controls) :where(.total) {
    width: 60px;
    flex: none;
    padding-inline: 0.75rem;
    padding-block: 0;
    font-size: 13px;
    line-height: 2.5rem;
    font-variant-numeric: tabular-nums;
  }
  .video:where(.visible) :where(.box) :where(.frame) :where(.controls) {
    --acme-translate-x: 0rem;
    translate: var(--acme-translate-x) var(--acme-translate-y);
    --acme-translate-y: -6px;
    opacity: 1;
    transition-duration: 0.2s;
    transition-timing-function: cubic-bezier(0.25, 0.57, 0.45, 0.94);
    animation-duration: 0.2s;
    animation-timing-function: cubic-bezier(0.25, 0.57, 0.45, 0.94);
  }
  .video:where(.round) :where(.box) :where(.frame) :where(video) {
    border-radius: var(--acme-radius);
  }
  @media not all and (min-width: 992px) {
    .video :where(.box) :where(.frame) :where(.controls) :where(.track) :where(.scrub) {
      height: 18px;
    }
    .video :where(.box) :where(.frame) :where(.controls) {
      --acme-translate-x: 0rem;
      translate: var(--acme-translate-x) var(--acme-translate-y);
      --acme-translate-y: 0rem;
      --acme-scale-x: 100%;
      scale: var(--acme-scale-x) var(--acme-scale-y);
      --acme-scale-y: 0%;
      opacity: 1;
    }
  }
  .video :where(.box) :where(.frame) :where(.controls) :where(.track) :where(progress)::-webkit-progress-bar {
    background-color: var(--ds-gray-200);
  }
  .video :where(.box) :where(.frame) :where(.controls) :where(.track) :where(progress)::-webkit-progress-value {
    background-color: var(--acme-foreground);
  }
  .video :where(.box) :where(.frame) :where(.controls) :where(.play)[data-focus] {
    border-radius: 0.25rem;
    box-shadow: var(--ds-focus-ring);
  }
`;
