// Generated by the style generator from the reference spec. Do not edit; edit the mapping and regenerate.
import { css } from "lit";
export const loadMorePlaceholderCss = css`
  .placeholder:where(.no-gap) {
    margin-top: 0;
  }
  .placeholder:where(:not(.no-gap)) {
    margin-top: 1rem;
  }
  .placeholder {
    height: 2rem;
  }
`;
