import path from "node:path";
import {loadDocs} from '../../../../site/pages/components/index';
import {exampleSources,exampleId} from '../../../../site/example-source';
import assert from 'node:assert/strict';
const root=path.resolve(import.meta.dir,"../../../..");
const examples=[];
for(const doc of await loadDocs())for(const e of doc.examples){if(e.census||e.code)continue; const [source]=await exampleSources(e,exampleId(doc.id,e.h));examples.push({id:exampleId(doc.id,e.h),code:source.code,script:!!e.script});}
for(const example of examples) for(const match of example.code.matchAll(/https:\/\/cdn\.jsdelivr\.net\/npm\/@acmelabs\/design-system@[^/]+\/dist\/([^"'<>]+)/g)) assert.ok(await Bun.file(root+'/dist/'+match[1]).exists(),example.id+': '+match[1]);
const selected=examples.filter(e=>e.id.startsWith('video-')&&e.id!=='video-unavailable-media');
const server=Bun.serve({port:0,fetch(req){const path=new URL(req.url).pathname;if(path.startsWith('/dist/'))return new Response(Bun.file(root+path)); const example=selected.find(e=>'/'+e.id===path);return new Response(example?.code.replaceAll(/https:\/\/cdn\.jsdelivr\.net\/npm\/@acmelabs\/design-system@[^/]+\/dist/g,server.url.origin+'/dist')??'missing',{headers:{'Content-Type':'text/html'}});}});
const runtime=process.env.ACME_BROWSER_RUNTIME;if(!runtime)throw new Error("Set ACME_BROWSER_RUNTIME");process.env.PLAYWRIGHT_BROWSERS_PATH=runtime+"/browsers";const pw=await import(runtime+"/node_modules/playwright/index.mjs");const results=[];
try{for(const engine of ['chromium','firefox','webkit']){const browser=await pw[engine].launch({headless:true,...(engine==='chromium'?{executablePath:process.env.ACME_CHROMIUM_PATH}:{})});const page=await browser.newPage();await page.route("https://fonts.googleapis.com/**",route=>route.abort());await page.route("https://fonts.gstatic.com/**",route=>route.abort());let errors=[];page.on('pageerror',e=>errors.push(String(e)));for(const example of selected){errors=[];try{await page.goto(server.url.origin+'/'+example.id,{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>[...document.querySelectorAll('*')].filter(e=>e.localName.startsWith('acme-')).every(e=>customElements.get(e.localName)));await page.evaluate(async()=>Promise.all([...document.querySelectorAll('*')].map(e=>e.updateComplete)));await page.waitForFunction(()=>document.querySelector("acme-video").getVideoElement().readyState>=1);if(example.id==="video-captions") await page.waitForFunction(()=>document.querySelector("acme-video").getVideoElement().textTracks[0]?.cues?.length>0);assert.deepEqual(errors,[]);results.push({engine,id:example.id,pass:true});}catch(e){results.push({engine,id:example.id,pass:false,error:String(e)});console.log(engine,example.id,e);}}await browser.close();console.log(engine,'copied',selected.length);} }finally{server.stop(true);}
await Bun.write(".artifacts/m23-docs/video-copy-results.json",JSON.stringify({allSourcesChecked:examples.length,results},null,2));if(results.some(r=>!r.pass))process.exitCode=1;
