// Generated by the style generator from the reference spec. Do not edit; edit the mapping and regenerate.
import { css } from "lit";
export const menuSectionCss = css`
  .section :where(.group) {
    margin: 0;
    list-style-type: none;
    padding: 0;
  }
  .section :where(.heading) {
    display: block;
    padding: 0.5rem;
    font-family: var(--acme-font-sans);
    font-size: 14px;
    line-height: 20px;
    font-weight: 400;
    color: var(--ds-gray-800);
  }
  .section :where(.heading) > strong {
    font-weight: 500;
    color: var(--ds-gray-1000);
  }
`;
