/// <reference types="bun" />
// Builds dist/ two ways, following lit.dev/docs/tools/publishing:
//   dist/*.js (+ .d.ts, .d.ts.map)  unbundled ES2022 modules with Lit templates precompiled by @lit-labs/compiler;
//                                    the npm entry, for consumers with a bundler
//   dist/bundle/design-system(.min).js  one self-contained ES module with Lit and the labs packages inside,
//                                    for a static page that loads it from jsdelivr with no build step
//   tokens.css and dashboard.css     the global layers (generated by scripts/split-css.ts)
// Pure Bun: no Node runtime, no Python.

import fs from "node:fs";
import path from "node:path";
import { compileLitTemplates } from "@lit-labs/compiler";
import ts from "typescript";

const ROOT = path.resolve(import.meta.dir, "..");
const SRC = path.join(ROOT, "src"),
  DIST = path.join(ROOT, "dist");
fs.rmSync(DIST, { recursive: true, force: true });
fs.mkdirSync(path.join(DIST, "bundle"), { recursive: true });

const walk = (d: string): string[] =>
  fs
    .readdirSync(d, { withFileTypes: true })
    .flatMap((e) =>
      e.isDirectory() ? (e.name === "__tests__" ? [] : walk(path.join(d, e.name))) : e.name.endsWith(".ts") && !e.name.endsWith(".d.ts") && !e.name.endsWith(".geist.ts") ? [path.join(d, e.name)] : [],
    ); // .geist.ts mappings feed tools/geist/gen.ts, not the package
const files = walk(SRC);
const compilerOptions: ts.CompilerOptions = {
  target: ts.ScriptTarget.ES2022,
  module: ts.ModuleKind.ESNext,
  experimentalDecorators: true,
  useDefineForClassFields: false,
  moduleResolution: ts.ModuleResolutionKind.Bundler,
};

// 1. Unbundled modules, templates precompiled.
let compiled = 0;
for (const f of files) {
  const out = ts.transpileModule(fs.readFileSync(f, "utf8"), { compilerOptions, fileName: f, transformers: { before: [compileLitTemplates()] } });
  const rel = path.relative(SRC, f).replace(/\.ts$/, ".js");
  fs.mkdirSync(path.dirname(path.join(DIST, rel)), { recursive: true });
  fs.writeFileSync(path.join(DIST, rel), out.outputText);
  if (out.outputText.includes("_$LH")) compiled++;
}
console.log(`modules: ${files.length} files, ${compiled} with compiled templates`);

// 2. Declarations with maps.
const program = ts.createProgram(files, {
  ...compilerOptions,
  declaration: true,
  declarationMap: true,
  emitDeclarationOnly: true,
  outDir: DIST,
  rootDir: SRC,
  skipLibCheck: true,
  lib: ["lib.es2022.d.ts", "lib.dom.d.ts", "lib.dom.iterable.d.ts"],
});
const emit = program.emit();
const diags = ts
  .getPreEmitDiagnostics(program)
  .concat(emit.diagnostics)
  .filter((d) => d.category === ts.DiagnosticCategory.Error);
for (const d of diags.slice(0, 30))
  console.error(ts.flattenDiagnosticMessageText(d.messageText, "\n"), d.file ? `${path.relative(ROOT, d.file.fileName)}:${d.file.getLineAndCharacterOfPosition(d.start ?? 0).line + 1}` : "");
if (diags.length) {
  console.error(`${diags.length} type errors`);
  process.exit(1);
}

// 3. The self-contained browser bundle.
for (const [name, minify] of [
  ["design-system.js", false],
  ["design-system.min.js", true],
] as const) {
  const r = await Bun.build({
    entrypoints: [path.join(DIST, "index.js")],
    outdir: path.join(DIST, "bundle"),
    naming: name,
    target: "browser",
    format: "esm",
    minify,
    sourcemap: minify ? "none" : "linked",
  });
  if (!r.success) {
    for (const l of r.logs) console.error(l);
    process.exit(1);
  }
}

// 3b. The standalone bundle: the same, plus tokens.css installed into the document on import.
// For hosts that allow a script from a CDN but no stylesheet from one (the artifact CSP), one tag.
{
  const tokens = fs.readFileSync(path.join(ROOT, "tokens.css"), "utf8");
  const entry = path.join(DIST, `standalone-entry-${process.pid}.js`); // per process: builds may run concurrently
  fs.writeFileSync(
    entry,
    `import "./index";\nconst css = ${JSON.stringify(tokens)};\nif (!document.querySelector("style[data-acme-tokens]")) { const s = document.createElement("style"); s.dataset.acmeTokens = ""; s.textContent = css; document.head.prepend(s); }\n`,
  );
  const r = await Bun.build({ entrypoints: [entry], outdir: path.join(DIST, "bundle"), naming: "design-system.standalone.min.js", target: "browser", format: "esm", minify: true, sourcemap: "none" });
  fs.rmSync(entry, { force: true });
  if (!r.success) {
    for (const l of r.logs) console.error(l);
    process.exit(1);
  }
}

// 4. The dashboard recipe layer: rule families that are page compositions, not elements.
const styleFile = (r: string) => {
  const shared = path.join(SRC, "shared", `${r}.styles.ts`);
  return fs.existsSync(shared) ? shared : path.join(SRC, "components", r, `${r}.styles.ts`);
};
const recipes = ["deploy", "plan", "usage-sum", "classes", "severity", "option", "info-ic", "rail", "subnav", "link-card", "logs", "task", "code", "check"];
const un = (s: string) =>
  s
    .replace(/^[\s\S]*?css`\n/, "")
    .replace(/\n`;\s*$/, "")
    .replace(/\\`/g, "`")
    .replace(/\\\$\{/g, "${")
    .replace(/\\\\/g, "\\");
fs.writeFileSync(
  path.join(ROOT, "dashboard.css"),
  "/* @acmelabs/design-system dashboard.css — Vercel dashboard recipes as plain classes for pages that compose them in light DOM. Generated by scripts/build.ts. */\n" +
    recipes.map((r) => un(fs.readFileSync(styleFile(r), "utf8"))).join("\n") +
    "\n",
);

const size = (p: string) => `${(fs.statSync(p).size / 1024).toFixed(1)} KB`;
console.log(
  "bundle",
  size(path.join(DIST, "bundle/design-system.js")),
  "min",
  size(path.join(DIST, "bundle/design-system.min.js")),
  "tokens.css",
  size(path.join(ROOT, "tokens.css")),
  "dashboard.css",
  size(path.join(ROOT, "dashboard.css")),
);
