import fs from "node:fs";
import path from "node:path";

const ROOT = path.resolve(import.meta.dir, "..");
/** Extract only the binary long-name prefixes; native Intl supplies numbers and base units. */
export function bytePrefixModule(root = ROOT): string {
  const directory = path.join(root, "node_modules/cldr-units-full"),
    pkg = JSON.parse(fs.readFileSync(path.join(directory, "package.json"), "utf8"));
  if (pkg.version !== "48.2.0") throw new Error("Review the pinned CLDR data version before regeneration");
  const unique: string[][] = [],
    indices = new Map<string, number>(),
    locales: Record<string, number> = {};
  for (const locale of fs.readdirSync(path.join(directory, "main")).sort()) {
    const data = JSON.parse(fs.readFileSync(path.join(directory, "main", locale, "units.json"), "utf8"));
    const values = Array.from({ length: 5 }, (_, index) => data.main[locale].units.long[`1024p${index + 1}`]?.unitPrefixPattern);
    if (values.some((value) => typeof value !== "string" || value.split("{0}").length !== 2)) throw new Error("Missing binary prefix pattern: " + locale);
    const key = JSON.stringify(values);
    let index = indices.get(key);
    if (index === undefined) {
      index = unique.length;
      indices.set(key, index);
      unique.push(values);
    }
    locales[locale.toLowerCase()] = index;
  }
  const parents = JSON.parse(fs.readFileSync(path.join(root, "node_modules/cldr-core/supplemental/parentLocales.json"), "utf8")).supplemental.parentLocales.parentLocale;
  const parentLocales = Object.fromEntries(Object.entries(parents).map(([locale, parent]) => [locale.toLowerCase(), String(parent).toLowerCase()]));
  return `// Generated by scripts/byte-prefixes.ts from CLDR ${pkg.version}.\n// SPDX-License-Identifier: Unicode-3.0; see assets/licenses/unicode.txt.\nexport const binaryPrefixVersion=${JSON.stringify(pkg.version)};\nexport const binaryPrefixPatterns=Object.freeze(${JSON.stringify(unique)}.map(patterns=>Object.freeze(patterns)));\nexport const binaryPrefixLocales:Readonly<Record<string,number>>=Object.freeze(${JSON.stringify(locales)});\nexport const binaryPrefixParents:Readonly<Record<string,string>>=Object.freeze(${JSON.stringify(parentLocales)});\n`;
}
export function writeBytePrefixes(root = ROOT): void {
  fs.writeFileSync(path.join(root, "src/generated/byte-prefixes.ts"), bytePrefixModule(root));
  fs.mkdirSync(path.join(root, "assets/licenses"), { recursive: true });
  fs.copyFileSync(path.join(root, "node_modules/cldr-units-full/LICENSE"), path.join(root, "assets/licenses/unicode.txt"));
}
export function verifyBytePrefixes(root = ROOT): void {
  if (fs.readFileSync(path.join(root, "src/generated/byte-prefixes.ts"), "utf8") !== bytePrefixModule(root)) throw new Error("Stale byte prefix data; run bun scripts/byte-prefixes.ts");
  if (fs.readFileSync(path.join(root, "assets/licenses/unicode.txt"), "utf8") !== fs.readFileSync(path.join(root, "node_modules/cldr-units-full/LICENSE"), "utf8"))
    throw new Error("Missing or stale Unicode license");
}
if (import.meta.main) writeBytePrefixes();
