import fs from "node:fs";
import path from "node:path";
import ts from "typescript";

export interface ComponentEntry {
  name: string;
  tag: string;
  className: string;
  file: string;
  dependencies: string[];
}

const HEADER = "// Generated by scripts/entries.ts. Do not edit.\n";
const DEFAULT_ROOT = path.resolve(import.meta.dir, "..");
const portable = (file: string) => file.split(path.sep).join("/");

function sourceFiles(directory: string): string[] {
  return fs
    .readdirSync(directory, { withFileTypes: true })
    .flatMap((entry) => {
      const file = path.join(directory, entry.name);
      if (entry.isDirectory()) return entry.name === "__tests__" || entry.name === "define" ? [] : sourceFiles(file);
      return entry.isFile() && entry.name.endsWith(".ts") && entry.name !== "all.ts" ? [file] : [];
    })
    .sort();
}

/** Read opening tags without mistaking comments, attribute values or raw text for elements. */
function literalTags(markup: string, location: string): string[] {
  const tags: string[] = [];
  let offset = 0;
  while ((offset = markup.indexOf("<", offset)) !== -1) {
    if (markup.startsWith("<!--", offset)) {
      const end = markup.indexOf("-->", offset + 4);
      offset = end < 0 ? markup.length : end + 3;
      continue;
    }
    const name = /^<\/?([^\s/>]+)/.exec(markup.slice(offset))?.[1];
    if (name?.includes("\0")) throw new Error(`Unresolved dynamic tag in Lit template at ${location}; use literal tags or add explicit dependency support`);
    const match = /^<([a-z][a-z0-9-]*)(?=[\s/>])/i.exec(markup.slice(offset));
    if (!match) {
      offset++;
      continue;
    }
    const tag = match[1].toLowerCase();
    if (tag.startsWith("acme-")) tags.push(tag);
    offset += match[0].length;
    let quote = "";
    while (offset < markup.length) {
      const character = markup[offset++];
      if (quote) {
        if (character === quote) quote = "";
      } else if (character === '"' || character === "'") quote = character;
      else if (character === ">") break;
    }
    if (["script", "style", "textarea", "title"].includes(tag)) {
      const end = markup.toLowerCase().indexOf(`</${tag}`, offset);
      offset = end < 0 ? markup.length : end;
    }
  }
  return tags;
}

function importSource(node: ts.Node): string | undefined {
  let parent: ts.Node | undefined = node;
  while (parent && !ts.isImportDeclaration(parent)) parent = parent.parent;
  return parent && ts.isStringLiteral(parent.moduleSpecifier) ? parent.moduleSpecifier.text : undefined;
}

export function collectComponents(root = DEFAULT_ROOT): ComponentEntry[] {
  root = path.resolve(root);
  const files = sourceFiles(path.join(root, "src"));
  const program = ts.createProgram(files, {
    target: ts.ScriptTarget.ES2022,
    module: ts.ModuleKind.ESNext,
    moduleResolution: ts.ModuleResolutionKind.Bundler,
    skipLibCheck: true,
    experimentalDecorators: true,
  });
  const checker = program.getTypeChecker();
  const resolve = (node: ts.Node): ts.Symbol | undefined => {
    const symbol = checker.getSymbolAtLocation(node);
    return symbol && symbol.flags & ts.SymbolFlags.Alias ? checker.getAliasedSymbol(symbol) : symbol;
  };
  const records = new Map<string, { entry: ComponentEntry; declaration: ts.ClassDeclaration }>();
  const location = (node: ts.Node) => {
    const source = node.getSourceFile();
    return `${portable(path.relative(root, source.fileName))}:${source.getLineAndCharacterOfPosition(node.getStart()).line + 1}`;
  };
  for (const file of files) {
    const source = program.getSourceFile(file)!;
    const visit = (node: ts.Node) => {
      if (ts.isInterfaceDeclaration(node) && node.name.text === "HTMLElementTagNameMap") {
        for (const member of node.members) {
          if (!ts.isPropertySignature(member) || !member.name || !ts.isStringLiteral(member.name) || !member.name.text.startsWith("acme-")) continue;
          const tag = member.name.text;
          if (!/^acme-[a-z0-9]+(?:-[a-z0-9]+)*$/.test(tag)) throw new Error(`Invalid component tag ${tag} at ${location(member)}`);
          if (records.has(tag)) throw new Error(`Duplicate component tag ${tag} at ${location(member)}`);
          const symbol = member.type && ts.isTypeReferenceNode(member.type) ? resolve(member.type.typeName) : undefined;
          const declaration = symbol?.declarations?.find(ts.isClassDeclaration);
          if (!declaration?.name) throw new Error(`Missing class for ${tag} at ${location(member)}`);
          const classFile = declaration.getSourceFile();
          const relative = portable(path.relative(root, classFile.fileName));
          if (!relative.startsWith("src/")) throw new Error(`Component class for ${tag} is outside src: ${relative}`);
          const moduleSymbol = checker.getSymbolAtLocation(classFile);
          const exported = moduleSymbol && checker.getExportsOfModule(moduleSymbol).find((item) => item.name === declaration.name!.text);
          if (!exported || (exported.flags & ts.SymbolFlags.Alias ? checker.getAliasedSymbol(exported) : exported) !== symbol) {
            throw new Error(`Missing named class export for ${tag} at ${location(declaration)}`);
          }
          records.set(tag, { entry: { name: tag.slice(5), tag, className: declaration.name.text, file: relative, dependencies: [] }, declaration });
        }
      }
      ts.forEachChild(node, visit);
    };
    visit(source);
  }

  const isLitTemplate = (tag: ts.LeftHandSideExpression): boolean => {
    if (ts.isIdentifier(tag)) {
      const symbol = checker.getSymbolAtLocation(tag);
      return !!symbol?.declarations?.some(
        (declaration) =>
          ts.isImportSpecifier(declaration) &&
          ["html", "svg"].includes((declaration.propertyName ?? declaration.name).text) &&
          ["lit", "lit-html", "lit/static-html.js", "lit-html/static.js"].includes(importSource(declaration) ?? ""),
      );
    }
    if (ts.isPropertyAccessExpression(tag) && ["html", "svg"].includes(tag.name.text)) {
      return !!checker
        .getSymbolAtLocation(tag.expression)
        ?.declarations?.some((declaration) => ts.isNamespaceImport(declaration) && ["lit", "lit-html", "lit/static-html.js", "lit-html/static.js"].includes(importSource(declaration) ?? ""));
    }
    return false;
  };

  const createdTags = (expression: ts.Expression): string[] => {
    if (ts.isStringLiteral(expression) || ts.isNoSubstitutionTemplateLiteral(expression)) return [expression.text];
    const collect = (type: ts.Type): string[] | undefined => {
      if (type.isStringLiteral()) return [type.value];
      if (type.isUnion()) {
        const members = type.types.map(collect);
        return members.every((member) => member !== undefined) ? members.flat() : undefined;
      }
      if (type.flags & ts.TypeFlags.TemplateLiteral) {
        const prefix = (type as ts.TemplateLiteralType).texts[0];
        if (prefix && !prefix.startsWith("acme-") && !"acme-".startsWith(prefix)) return [];
      }
      if (type.flags & ts.TypeFlags.TypeParameter) {
        const constraint = checker.getBaseConstraintOfType(type);
        if (constraint && constraint !== type) return collect(constraint);
      }
      return undefined;
    };
    const names = collect(checker.getTypeAtLocation(expression));
    if (!names) throw new Error(`Unresolved dynamic tag in createElement at ${location(expression)}; use finite literal names or add explicit dependency support`);
    return names;
  };

  for (const { entry, declaration } of records.values()) {
    const tags = new Set<string>();
    const visited = new Set<ts.Node>();
    const scan = (node: ts.Node): void => {
      if (visited.has(node) || ts.isTypeNode(node) || ts.isImportDeclaration(node)) return;
      visited.add(node);
      if (ts.isTaggedTemplateExpression(node) && isLitTemplate(node.tag)) {
        const template = node.template;
        const markup = ts.isNoSubstitutionTemplateLiteral(template) ? template.text : template.head.text + template.templateSpans.map((span) => `\0${span.literal.text}`).join("");
        for (const tag of literalTags(markup, location(node))) tags.add(tag);
      }
      if (ts.isCallExpression(node) && ts.isPropertyAccessExpression(node.expression) && node.expression.name.text === "createElement") {
        const receiver = node.expression.expression;
        if ((ts.isIdentifier(receiver) && receiver.text === "document") || (ts.isPropertyAccessExpression(receiver) && receiver.name.text === "ownerDocument")) {
          const name = node.arguments[0];
          if (name) for (const tag of createdTags(name)) if (tag.startsWith("acme-")) tags.add(tag);
        }
      }
      if (ts.isIdentifier(node)) {
        for (const target of resolve(node)?.declarations ?? []) {
          if ((ts.isVariableDeclaration(target) || ts.isFunctionDeclaration(target)) && path.resolve(target.getSourceFile().fileName).startsWith(`${root}${path.sep}src${path.sep}`)) scan(target);
        }
      }
      ts.forEachChild(node, scan);
    };
    const inherited = new Set<ts.ClassDeclaration>();
    const scanClass = (current: ts.ClassDeclaration): void => {
      if (inherited.has(current)) return;
      inherited.add(current);
      scan(current);
      for (const clause of current.heritageClauses ?? []) {
        if (clause.token !== ts.SyntaxKind.ExtendsKeyword) continue;
        for (const parent of clause.types) {
          const base = resolve(parent.expression)?.declarations?.find(ts.isClassDeclaration);
          if (base && path.resolve(base.getSourceFile().fileName).startsWith(`${root}${path.sep}src${path.sep}`)) scanClass(base);
        }
      }
    };
    scanClass(declaration);
    entry.dependencies = [...tags]
      .map((tag) => {
        const dependency = records.get(tag);
        if (!dependency) throw new Error(`Unknown component tag ${tag} owned by ${entry.tag} (${entry.file})`);
        return dependency.entry.name;
      })
      .sort();
  }

  const entries = [...records.values()].map(({ entry }) => entry).sort((a, b) => a.name.localeCompare(b.name, "en"));
  const byName = new Map(entries.map((entry) => [entry.name, entry]));
  const complete = new Set<string>();
  const visit = (name: string, ancestors: string[]): void => {
    if (ancestors.includes(name)) throw new Error(`Component dependency cycle: ${[...ancestors, name].join(" -> ")}`);
    if (complete.has(name)) return;
    for (const dependency of byName.get(name)!.dependencies) visit(dependency, [...ancestors, name]);
    complete.add(name);
  };
  for (const entry of entries) visit(entry.name, []);
  return entries;
}

export function writeEntries(root = DEFAULT_ROOT): ComponentEntry[] {
  root = path.resolve(root);
  const entries = collectComponents(root);
  const directory = path.join(root, "src/define");
  const outputs = new Map<string, string>();
  for (const entry of entries) {
    const module = portable(path.relative(directory, path.join(root, entry.file))).replace(/\.ts$/, "");
    outputs.set(
      path.join(directory, `${entry.name}.ts`),
      HEADER +
        entry.dependencies.map((name) => `import "./${name}";\n`).join("") +
        `import "${module.startsWith(".") ? module : `./${module}`}";\nimport { ${entry.className} } from "${module.startsWith(".") ? module : `./${module}`}";\n\ncustomElements.define("${entry.tag}", ${entry.className});\n`,
    );
  }
  outputs.set(
    path.join(root, "src/all.ts"),
    HEADER +
      entries
        .filter((entry) => !entry.file.startsWith("src/generated/icons/classes/"))
        .map((entry) => `import "./define/${entry.name}";\n`)
        .join(""),
  );
  for (const file of outputs.keys()) {
    if (fs.existsSync(file) && (fs.lstatSync(file).isSymbolicLink() || !fs.readFileSync(file, "utf8").startsWith(HEADER))) throw new Error(`Refusing to overwrite authored entry: ${file}`);
  }
  fs.mkdirSync(directory, { recursive: true });
  for (const entry of fs.readdirSync(directory, { withFileTypes: true })) {
    const file = path.join(directory, entry.name);
    if (entry.isFile() && entry.name.endsWith(".ts") && !outputs.has(file) && fs.readFileSync(file, "utf8").startsWith(HEADER)) fs.unlinkSync(file);
  }
  for (const [file, content] of outputs) if (!fs.existsSync(file) || fs.readFileSync(file, "utf8") !== content) fs.writeFileSync(file, content);
  return entries;
}

/** Publish exactly the class entries represented by the source tag records. */
export function writePackageExports(entries: ComponentEntry[], root = DEFAULT_ROOT): void {
  const file = path.join(root, "package.json");
  const before = fs.readFileSync(file, "utf8");
  const pkg = JSON.parse(before);
  const exports = Object.fromEntries(Object.entries(pkg.exports ?? {}).filter(([name]) => !name.startsWith("./components/") && name !== "./dist/*"));
  exports["./all"] = { types: "./dist/all.d.ts", import: "./dist/all.js", default: "./dist/all.js" };
  exports["./define/*"] = { types: "./dist/define/*.d.ts", import: "./dist/define/*.js", default: "./dist/define/*.js" };
  exports["./cdn/*"] = "./dist/cdn/*";
  exports["./configure"] = { types: "./dist/configure.d.ts", import: "./dist/configure.js", default: "./dist/configure.js" };
  exports["./icons/*"] = { types: "./dist/generated/icons/classes/*-icon.d.ts", import: "./dist/generated/icons/classes/*-icon.js", default: "./dist/generated/icons/classes/*-icon.js" };
  exports["./icons/artwork/*"] = { types: "./dist/generated/icons/artwork/*.d.ts", import: "./dist/generated/icons/artwork/*.js", default: "./dist/generated/icons/artwork/*.js" };
  exports["./icons/families/*"] = { types: "./dist/generated/icons/families/*.d.ts", import: "./dist/generated/icons/families/*.js", default: "./dist/generated/icons/families/*.js" };
  exports["./icons/all"] = { types: "./dist/generated/icons/all.d.ts", import: "./dist/generated/icons/all.js", default: "./dist/generated/icons/all.js" };
  exports["./icons/catalog"] = "./dist/icons.json";
  for (const entry of entries) {
    const module = "./" + entry.file.replace(/^src\//, "dist/").replace(/\.ts$/, "");
    exports["./components/" + entry.name] = { types: module + ".d.ts", import: module + ".js", default: module + ".js" };
  }
  pkg.exports = exports;
  pkg.sideEffects = [
    "./dist/define/*.js",
    "./dist/all.js",
    "./dist/generated/icons/artwork/**",
    "./dist/generated/icons/families/**",
    "./dist/generated/icons/all.js",
    "./dist/cdn/**",
    "./dist/bundle/**",
    "**/*.css",
  ];
  const content = JSON.stringify(pkg, null, 2) + "\n";
  if (content !== before) fs.writeFileSync(file, content);
}

if (import.meta.main) {
  const root = process.argv[2] ?? DEFAULT_ROOT;
  writePackageExports(writeEntries(root), root);
}
