// Generated by the style generator from the reference spec. Do not edit; edit the mapping and regenerate.
import { css } from "lit";
export const searchInputCss = css`
  .input :where(slot[name="prefix"]) :where(acme-spinner)::part(spinner) {
    width: var(--ds-control-decoration-size);
    height: var(--ds-control-decoration-size);
  }
  .input :where(slot[name="prefix"])::slotted(svg),
  .input :where(slot[name="prefix"]) > svg {
    width: var(--ds-control-decoration-size) !important;
    height: var(--ds-control-decoration-size) !important;
  }
`;
