// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/14mp-icon";
import { Acme14mpIcon } from "../generated/icons/classes/14mp-icon";

customElements.define("acme-14mp-icon", Acme14mpIcon);
