// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/15mp-icon";
import { Acme15mpIcon } from "../generated/icons/classes/15mp-icon";

customElements.define("acme-15mp-icon", Acme15mpIcon);
