// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/24fps-select-icon";
import { Acme24fpsSelectIcon } from "../generated/icons/classes/24fps-select-icon";

customElements.define("acme-24fps-select-icon", Acme24fpsSelectIcon);
