// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/5mp-icon";
import { Acme5mpIcon } from "../generated/icons/classes/5mp-icon";

customElements.define("acme-5mp-icon", Acme5mpIcon);
