// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/7k-plus-icon";
import { Acme7kPlusIcon } from "../generated/icons/classes/7k-plus-icon";

customElements.define("acme-7k-plus-icon", Acme7kPlusIcon);
