// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/9k-plus-icon";
import { Acme9kPlusIcon } from "../generated/icons/classes/9k-plus-icon";

customElements.define("acme-9k-plus-icon", Acme9kPlusIcon);
