// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/account-circle-icon";
import { AcmeAccountCircleIcon } from "../generated/icons/classes/account-circle-icon";

customElements.define("acme-account-circle-icon", AcmeAccountCircleIcon);
