// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/activity-zone-icon";
import { AcmeActivityZoneIcon } from "../generated/icons/classes/activity-zone-icon";

customElements.define("acme-activity-zone-icon", AcmeActivityZoneIcon);
