// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/action-key-icon";
import { AcmeActionKeyIcon } from "../generated/icons/classes/action-key-icon";

customElements.define("acme-action-key-icon", AcmeActionKeyIcon);
