// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/acupuncture-icon";
import { AcmeAcupunctureIcon } from "../generated/icons/classes/acupuncture-icon";

customElements.define("acme-acupuncture-icon", AcmeAcupunctureIcon);
