// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/add-moderator-icon";
import { AcmeAddModeratorIcon } from "../generated/icons/classes/add-moderator-icon";

customElements.define("acme-add-moderator-icon", AcmeAddModeratorIcon);
