// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/add-icon";
import { AcmeAddIcon } from "../generated/icons/classes/add-icon";

customElements.define("acme-add-icon", AcmeAddIcon);
