// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/add-business-icon";
import { AcmeAddBusinessIcon } from "../generated/icons/classes/add-business-icon";

customElements.define("acme-add-business-icon", AcmeAddBusinessIcon);
