// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/add-chart-icon";
import { AcmeAddChartIcon } from "../generated/icons/classes/add-chart-icon";

customElements.define("acme-add-chart-icon", AcmeAddChartIcon);
