// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/add-card-icon";
import { AcmeAddCardIcon } from "../generated/icons/classes/add-card-icon";

customElements.define("acme-add-card-icon", AcmeAddCardIcon);
