// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/add-to-photos-icon";
import { AcmeAddToPhotosIcon } from "../generated/icons/classes/add-to-photos-icon";

customElements.define("acme-add-to-photos-icon", AcmeAddToPhotosIcon);
