// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/add-location-icon";
import { AcmeAddLocationIcon } from "../generated/icons/classes/add-location-icon";

customElements.define("acme-add-location-icon", AcmeAddLocationIcon);
