// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/air-purifier-gen-icon";
import { AcmeAirPurifierGenIcon } from "../generated/icons/classes/air-purifier-gen-icon";

customElements.define("acme-air-purifier-gen-icon", AcmeAirPurifierGenIcon);
