// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/airline-seat-flat-angled-icon";
import { AcmeAirlineSeatFlatAngledIcon } from "../generated/icons/classes/airline-seat-flat-angled-icon";

customElements.define("acme-airline-seat-flat-angled-icon", AcmeAirlineSeatFlatAngledIcon);
