// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/airline-seat-legroom-normal-icon";
import { AcmeAirlineSeatLegroomNormalIcon } from "../generated/icons/classes/airline-seat-legroom-normal-icon";

customElements.define("acme-airline-seat-legroom-normal-icon", AcmeAirlineSeatLegroomNormalIcon);
