// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/airware-icon";
import { AcmeAirwareIcon } from "../generated/icons/classes/airware-icon";

customElements.define("acme-airware-icon", AcmeAirwareIcon);
