// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/align-end-icon";
import { AcmeAlignEndIcon } from "../generated/icons/classes/align-end-icon";

customElements.define("acme-align-end-icon", AcmeAlignEndIcon);
