// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/align-items-stretch-icon";
import { AcmeAlignItemsStretchIcon } from "../generated/icons/classes/align-items-stretch-icon";

customElements.define("acme-align-items-stretch-icon", AcmeAlignItemsStretchIcon);
