// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/all-out-icon";
import { AcmeAllOutIcon } from "../generated/icons/classes/all-out-icon";

customElements.define("acme-all-out-icon", AcmeAllOutIcon);
