// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/android-cell-dual-5-bar-alert-icon";
import { AcmeAndroidCellDual5BarAlertIcon } from "../generated/icons/classes/android-cell-dual-5-bar-alert-icon";

customElements.define("acme-android-cell-dual-5-bar-alert-icon", AcmeAndroidCellDual5BarAlertIcon);
