// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/android-wifi-3-bar-alert-icon";
import { AcmeAndroidWifi3BarAlertIcon } from "../generated/icons/classes/android-wifi-3-bar-alert-icon";

customElements.define("acme-android-wifi-3-bar-alert-icon", AcmeAndroidWifi3BarAlertIcon);
