// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/android-wifi-4-bar-alert-icon";
import { AcmeAndroidWifi4BarAlertIcon } from "../generated/icons/classes/android-wifi-4-bar-alert-icon";

customElements.define("acme-android-wifi-4-bar-alert-icon", AcmeAndroidWifi4BarAlertIcon);
