// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/android-cell-4-bar-alert-icon";
import { AcmeAndroidCell4BarAlertIcon } from "../generated/icons/classes/android-cell-4-bar-alert-icon";

customElements.define("acme-android-cell-4-bar-alert-icon", AcmeAndroidCell4BarAlertIcon);
