// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/app-registration-icon";
import { AcmeAppRegistrationIcon } from "../generated/icons/classes/app-registration-icon";

customElements.define("acme-app-registration-icon", AcmeAppRegistrationIcon);
