// Generated by scripts/entries.ts. Do not edit.
import "./theme-switcher";
import "../components/appbar/appbar";
import { AcmeAppbar } from "../components/appbar/appbar";

customElements.define("acme-appbar", AcmeAppbar);
