// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/approval-icon";
import { AcmeApprovalIcon } from "../generated/icons/classes/approval-icon";

customElements.define("acme-approval-icon", AcmeApprovalIcon);
