// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/architecture-icon";
import { AcmeArchitectureIcon } from "../generated/icons/classes/architecture-icon";

customElements.define("acme-architecture-icon", AcmeArchitectureIcon);
