// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/arrows-more-up-icon";
import { AcmeArrowsMoreUpIcon } from "../generated/icons/classes/arrows-more-up-icon";

customElements.define("acme-arrows-more-up-icon", AcmeArrowsMoreUpIcon);
