// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/arrow-back-ios-icon";
import { AcmeArrowBackIosIcon } from "../generated/icons/classes/arrow-back-ios-icon";

customElements.define("acme-arrow-back-ios-icon", AcmeArrowBackIosIcon);
