// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/arrows-input-icon";
import { AcmeArrowsInputIcon } from "../generated/icons/classes/arrows-input-icon";

customElements.define("acme-arrows-input-icon", AcmeArrowsInputIcon);
