// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/arrow-downward-icon";
import { AcmeArrowDownwardIcon } from "../generated/icons/classes/arrow-downward-icon";

customElements.define("acme-arrow-downward-icon", AcmeArrowDownwardIcon);
