// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/arrows-left-right-circle-icon";
import { AcmeArrowsLeftRightCircleIcon } from "../generated/icons/classes/arrows-left-right-circle-icon";

customElements.define("acme-arrows-left-right-circle-icon", AcmeArrowsLeftRightCircleIcon);
