// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/arrow-back-ios-new-icon";
import { AcmeArrowBackIosNewIcon } from "../generated/icons/classes/arrow-back-ios-new-icon";

customElements.define("acme-arrow-back-ios-new-icon", AcmeArrowBackIosNewIcon);
