// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/arrow-circle-left-icon";
import { AcmeArrowCircleLeftIcon } from "../generated/icons/classes/arrow-circle-left-icon";

customElements.define("acme-arrow-circle-left-icon", AcmeArrowCircleLeftIcon);
