// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/auto-awesome-mosaic-icon";
import { AcmeAutoAwesomeMosaicIcon } from "../generated/icons/classes/auto-awesome-mosaic-icon";

customElements.define("acme-auto-awesome-mosaic-icon", AcmeAutoAwesomeMosaicIcon);
