// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/autofps-select-icon";
import { AcmeAutofpsSelectIcon } from "../generated/icons/classes/autofps-select-icon";

customElements.define("acme-autofps-select-icon", AcmeAutofpsSelectIcon);
