// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/backspace-icon";
import { AcmeBackspaceIcon } from "../generated/icons/classes/backspace-icon";

customElements.define("acme-backspace-icon", AcmeBackspaceIcon);
