// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/bakery-dining-icon";
import { AcmeBakeryDiningIcon } from "../generated/icons/classes/bakery-dining-icon";

customElements.define("acme-bakery-dining-icon", AcmeBakeryDiningIcon);
