// Generated by scripts/entries.ts. Do not edit.
import "./button";
import "./chevron-right-icon";
import "../components/banner/banner";
import { AcmeBanner } from "../components/banner/banner";

customElements.define("acme-banner", AcmeBanner);
