// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/barcode-reader-icon";
import { AcmeBarcodeReaderIcon } from "../generated/icons/classes/barcode-reader-icon";

customElements.define("acme-barcode-reader-icon", AcmeBarcodeReaderIcon);
