// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/bath-private-icon";
import { AcmeBathPrivateIcon } from "../generated/icons/classes/bath-private-icon";

customElements.define("acme-bath-private-icon", AcmeBathPrivateIcon);
