// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/battery-charging-full-2-icon";
import { AcmeBatteryChargingFull2Icon } from "../generated/icons/classes/battery-charging-full-2-icon";

customElements.define("acme-battery-charging-full-2-icon", AcmeBatteryChargingFull2Icon);
