// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/battery-horiz-000-icon";
import { AcmeBatteryHoriz000Icon } from "../generated/icons/classes/battery-horiz-000-icon";

customElements.define("acme-battery-horiz-000-icon", AcmeBatteryHoriz000Icon);
