// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/battery-android-alert-icon";
import { AcmeBatteryAndroidAlertIcon } from "../generated/icons/classes/battery-android-alert-icon";

customElements.define("acme-battery-android-alert-icon", AcmeBatteryAndroidAlertIcon);
