// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/battery-20-icon";
import { AcmeBattery20Icon } from "../generated/icons/classes/battery-20-icon";

customElements.define("acme-battery-20-icon", AcmeBattery20Icon);
