// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/bedroom-child-icon";
import { AcmeBedroomChildIcon } from "../generated/icons/classes/bedroom-child-icon";

customElements.define("acme-bedroom-child-icon", AcmeBedroomChildIcon);
