// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/bedtime-icon";
import { AcmeBedtimeIcon } from "../generated/icons/classes/bedtime-icon";

customElements.define("acme-bedtime-icon", AcmeBedtimeIcon);
