// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/bia-icon";
import { AcmeBiaIcon } from "../generated/icons/classes/bia-icon";

customElements.define("acme-bia-icon", AcmeBiaIcon);
