// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/bike-scooter-icon";
import { AcmeBikeScooterIcon } from "../generated/icons/classes/bike-scooter-icon";

customElements.define("acme-bike-scooter-icon", AcmeBikeScooterIcon);
