// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/bike-lane-icon";
import { AcmeBikeLaneIcon } from "../generated/icons/classes/bike-lane-icon";

customElements.define("acme-bike-lane-icon", AcmeBikeLaneIcon);
