// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/blur-circular-icon";
import { AcmeBlurCircularIcon } from "../generated/icons/classes/blur-circular-icon";

customElements.define("acme-blur-circular-icon", AcmeBlurCircularIcon);
