// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/bookmark-heart-icon";
import { AcmeBookmarkHeartIcon } from "../generated/icons/classes/bookmark-heart-icon";

customElements.define("acme-bookmark-heart-icon", AcmeBookmarkHeartIcon);
