// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/bookmark-star-icon";
import { AcmeBookmarkStarIcon } from "../generated/icons/classes/bookmark-star-icon";

customElements.define("acme-bookmark-star-icon", AcmeBookmarkStarIcon);
