// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/bookmark-stacks-icon";
import { AcmeBookmarkStacksIcon } from "../generated/icons/classes/bookmark-stacks-icon";

customElements.define("acme-bookmark-stacks-icon", AcmeBookmarkStacksIcon);
