// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/book-ribbon-icon";
import { AcmeBookRibbonIcon } from "../generated/icons/classes/book-ribbon-icon";

customElements.define("acme-book-ribbon-icon", AcmeBookRibbonIcon);
