// Generated by scripts/entries.ts. Do not edit.
import "./layers-icon";
import "../components/book/book";
import { AcmeBook } from "../components/book/book";

customElements.define("acme-book", AcmeBook);
