// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/bookmark-bag-icon";
import { AcmeBookmarkBagIcon } from "../generated/icons/classes/bookmark-bag-icon";

customElements.define("acme-bookmark-bag-icon", AcmeBookmarkBagIcon);
