// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/border-right-icon";
import { AcmeBorderRightIcon } from "../generated/icons/classes/border-right-icon";

customElements.define("acme-border-right-icon", AcmeBorderRightIcon);
