// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/border-vertical-icon";
import { AcmeBorderVerticalIcon } from "../generated/icons/classes/border-vertical-icon";

customElements.define("acme-border-vertical-icon", AcmeBorderVerticalIcon);
