// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/borg-icon";
import { AcmeBorgIcon } from "../generated/icons/classes/borg-icon";

customElements.define("acme-borg-icon", AcmeBorgIcon);
