// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/bottom-drawer-icon";
import { AcmeBottomDrawerIcon } from "../generated/icons/classes/bottom-drawer-icon";

customElements.define("acme-bottom-drawer-icon", AcmeBottomDrawerIcon);
