// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/bottom-panel-open-icon";
import { AcmeBottomPanelOpenIcon } from "../generated/icons/classes/bottom-panel-open-icon";

customElements.define("acme-bottom-panel-open-icon", AcmeBottomPanelOpenIcon);
