// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/box-edit-icon";
import { AcmeBoxEditIcon } from "../generated/icons/classes/box-edit-icon";

customElements.define("acme-box-edit-icon", AcmeBoxEditIcon);
