// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/browse-activity-icon";
import { AcmeBrowseActivityIcon } from "../generated/icons/classes/browse-activity-icon";

customElements.define("acme-browse-activity-icon", AcmeBrowseActivityIcon);
