// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/build-icon";
import { AcmeBuildIcon } from "../generated/icons/classes/build-icon";

customElements.define("acme-build-icon", AcmeBuildIcon);
