// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/bus-map-pin-icon";
import { AcmeBusMapPinIcon } from "../generated/icons/classes/bus-map-pin-icon";

customElements.define("acme-bus-map-pin-icon", AcmeBusMapPinIcon);
