// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/calendar-check-icon";
import { AcmeCalendarCheckIcon } from "../generated/icons/classes/calendar-check-icon";

customElements.define("acme-calendar-check-icon", AcmeCalendarCheckIcon);
