// Generated by scripts/entries.ts. Do not edit.
import "./arrow-back-icon";
import "./arrow-forward-icon";
import "./calendar-month-icon";
import "./close-icon";
import "./kbd";
import "../components/calendar/calendar";
import { AcmeCalendar } from "../components/calendar/calendar";

customElements.define("acme-calendar", AcmeCalendar);
