// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/calendar-today-icon";
import { AcmeCalendarTodayIcon } from "../generated/icons/classes/calendar-today-icon";

customElements.define("acme-calendar-today-icon", AcmeCalendarTodayIcon);
