// Generated by scripts/entries.ts. Do not edit.
import "./calendar-month-icon";
import "./chevron-left-icon";
import "./chevron-right-icon";
import "../components/calendar/calendar";
import { AcmeCalendar } from "../components/calendar/calendar";

customElements.define("acme-calendar", AcmeCalendar);
