// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/camera-enhance-icon";
import { AcmeCameraEnhanceIcon } from "../generated/icons/classes/camera-enhance-icon";

customElements.define("acme-camera-enhance-icon", AcmeCameraEnhanceIcon);
