// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/camera-rear-icon";
import { AcmeCameraRearIcon } from "../generated/icons/classes/camera-rear-icon";

customElements.define("acme-camera-rear-icon", AcmeCameraRearIcon);
