// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/car-defrost-mid-low-right-icon";
import { AcmeCarDefrostMidLowRightIcon } from "../generated/icons/classes/car-defrost-mid-low-right-icon";

customElements.define("acme-car-defrost-mid-low-right-icon", AcmeCarDefrostMidLowRightIcon);
