// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/car-rental-icon";
import { AcmeCarRentalIcon } from "../generated/icons/classes/car-rental-icon";

customElements.define("acme-car-rental-icon", AcmeCarRentalIcon);
