// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/cardio-load-icon";
import { AcmeCardioLoadIcon } from "../generated/icons/classes/cardio-load-icon";

customElements.define("acme-cardio-load-icon", AcmeCardioLoadIcon);
