// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/card-membership-icon";
import { AcmeCardMembershipIcon } from "../generated/icons/classes/card-membership-icon";

customElements.define("acme-card-membership-icon", AcmeCardMembershipIcon);
