// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/carry-on-bag-inactive-icon";
import { AcmeCarryOnBagInactiveIcon } from "../generated/icons/classes/carry-on-bag-inactive-icon";

customElements.define("acme-carry-on-bag-inactive-icon", AcmeCarryOnBagInactiveIcon);
