// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/cell-wifi-icon";
import { AcmeCellWifiIcon } from "../generated/icons/classes/cell-wifi-icon";

customElements.define("acme-cell-wifi-icon", AcmeCellWifiIcon);
