// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/center-focus-weak-icon";
import { AcmeCenterFocusWeakIcon } from "../generated/icons/classes/center-focus-weak-icon";

customElements.define("acme-center-focus-weak-icon", AcmeCenterFocusWeakIcon);
