// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/center-focus-strong-icon";
import { AcmeCenterFocusStrongIcon } from "../generated/icons/classes/center-focus-strong-icon";

customElements.define("acme-center-focus-strong-icon", AcmeCenterFocusStrongIcon);
