// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/change-circle-icon";
import { AcmeChangeCircleIcon } from "../generated/icons/classes/change-circle-icon";

customElements.define("acme-change-circle-icon", AcmeChangeCircleIcon);
