// Generated by scripts/entries.ts. Do not edit.
import "./collapsible";
import "./collapsible-content";
import "./collapsible-trigger";
import "./table";
import "../components/chart/chart";
import { AcmeChart } from "../components/chart/chart";

customElements.define("acme-chart", AcmeChart);
