// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/checklist-rtl-icon";
import { AcmeChecklistRtlIcon } from "../generated/icons/classes/checklist-rtl-icon";

customElements.define("acme-checklist-rtl-icon", AcmeChecklistRtlIcon);
