// Generated by scripts/entries.ts. Do not edit.
import "./check-icon";
import "./remove-icon";
import "../components/checkbox/checkbox";
import { AcmeCheckbox } from "../components/checkbox/checkbox";

customElements.define("acme-checkbox", AcmeCheckbox);
