// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/chess-bishop-icon";
import { AcmeChessBishopIcon } from "../generated/icons/classes/chess-bishop-icon";

customElements.define("acme-chess-bishop-icon", AcmeChessBishopIcon);
