// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/chevron-left-icon";
import { AcmeChevronLeftIcon } from "../generated/icons/classes/chevron-left-icon";

customElements.define("acme-chevron-left-icon", AcmeChevronLeftIcon);
