// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/chip-extraction-icon";
import { AcmeChipExtractionIcon } from "../generated/icons/classes/chip-extraction-icon";

customElements.define("acme-chip-extraction-icon", AcmeChipExtractionIcon);
