// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/chromecast-device-icon";
import { AcmeChromecastDeviceIcon } from "../generated/icons/classes/chromecast-device-icon";

customElements.define("acme-chromecast-device-icon", AcmeChromecastDeviceIcon);
