// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/clarify-icon";
import { AcmeClarifyIcon } from "../generated/icons/classes/clarify-icon";

customElements.define("acme-clarify-icon", AcmeClarifyIcon);
