// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/climate-mini-split-icon";
import { AcmeClimateMiniSplitIcon } from "../generated/icons/classes/climate-mini-split-icon";

customElements.define("acme-climate-mini-split-icon", AcmeClimateMiniSplitIcon);
