// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/clinical-notes-icon";
import { AcmeClinicalNotesIcon } from "../generated/icons/classes/clinical-notes-icon";

customElements.define("acme-clinical-notes-icon", AcmeClinicalNotesIcon);
