// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/clock-loader-90-icon";
import { AcmeClockLoader90Icon } from "../generated/icons/classes/clock-loader-90-icon";

customElements.define("acme-clock-loader-90-icon", AcmeClockLoader90Icon);
