// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/close-small-icon";
import { AcmeCloseSmallIcon } from "../generated/icons/classes/close-small-icon";

customElements.define("acme-close-small-icon", AcmeCloseSmallIcon);
