// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/close-icon";
import { AcmeCloseIcon } from "../generated/icons/classes/close-icon";

customElements.define("acme-close-icon", AcmeCloseIcon);
