// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/cloud-upload-icon";
import { AcmeCloudUploadIcon } from "../generated/icons/classes/cloud-upload-icon";

customElements.define("acme-cloud-upload-icon", AcmeCloudUploadIcon);
