// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/cloud-done-icon";
import { AcmeCloudDoneIcon } from "../generated/icons/classes/cloud-done-icon";

customElements.define("acme-cloud-done-icon", AcmeCloudDoneIcon);
