// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/cognition-icon";
import { AcmeCognitionIcon } from "../generated/icons/classes/cognition-icon";

customElements.define("acme-cognition-icon", AcmeCognitionIcon);
