// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/collections-bookmark-icon";
import { AcmeCollectionsBookmarkIcon } from "../generated/icons/classes/collections-bookmark-icon";

customElements.define("acme-collections-bookmark-icon", AcmeCollectionsBookmarkIcon);
