// Generated by scripts/entries.ts. Do not edit.
import "../components/command-divider/command-divider";
import { AcmeCommandDivider } from "../components/command-divider/command-divider";

customElements.define("acme-command-divider", AcmeCommandDivider);
