// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/compass-calibration-icon";
import { AcmeCompassCalibrationIcon } from "../generated/icons/classes/compass-calibration-icon";

customElements.define("acme-compass-calibration-icon", AcmeCompassCalibrationIcon);
