// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/controller-gen-icon";
import { AcmeControllerGenIcon } from "../generated/icons/classes/controller-gen-icon";

customElements.define("acme-controller-gen-icon", AcmeControllerGenIcon);
