// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/contactless-off-icon";
import { AcmeContactlessOffIcon } from "../generated/icons/classes/contactless-off-icon";

customElements.define("acme-contactless-off-icon", AcmeContactlessOffIcon);
