// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/control-point-duplicate-icon";
import { AcmeControlPointDuplicateIcon } from "../generated/icons/classes/control-point-duplicate-icon";

customElements.define("acme-control-point-duplicate-icon", AcmeControlPointDuplicateIcon);
