// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/content-paste-go-icon";
import { AcmeContentPasteGoIcon } from "../generated/icons/classes/content-paste-go-icon";

customElements.define("acme-content-paste-go-icon", AcmeContentPasteGoIcon);
