// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/contacts-product-icon";
import { AcmeContactsProductIcon } from "../generated/icons/classes/contacts-product-icon";

customElements.define("acme-contacts-product-icon", AcmeContactsProductIcon);
