// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/contract-delete-icon";
import { AcmeContractDeleteIcon } from "../generated/icons/classes/contract-delete-icon";

customElements.define("acme-contract-delete-icon", AcmeContractDeleteIcon);
