// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/cool-to-dry-icon";
import { AcmeCoolToDryIcon } from "../generated/icons/classes/cool-to-dry-icon";

customElements.define("acme-cool-to-dry-icon", AcmeCoolToDryIcon);
