// Generated by scripts/entries.ts. Do not edit.
import "./check-icon";
import "./content-copy-icon";
import "./spinner";
import "../components/copy-button/copy-button";
import { AcmeCopyButton } from "../components/copy-button/copy-button";

customElements.define("acme-copy-button", AcmeCopyButton);
