// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/countertops-icon";
import { AcmeCountertopsIcon } from "../generated/icons/classes/countertops-icon";

customElements.define("acme-countertops-icon", AcmeCountertopsIcon);
