// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/credit-card-off-icon";
import { AcmeCreditCardOffIcon } from "../generated/icons/classes/credit-card-off-icon";

customElements.define("acme-credit-card-off-icon", AcmeCreditCardOffIcon);
