// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/crop-2-3-icon";
import { AcmeCrop23Icon } from "../generated/icons/classes/crop-2-3-icon";

customElements.define("acme-crop-2-3-icon", AcmeCrop23Icon);
