// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/crop-21-9-icon";
import { AcmeCrop219Icon } from "../generated/icons/classes/crop-21-9-icon";

customElements.define("acme-crop-21-9-icon", AcmeCrop219Icon);
