// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/crop-5-4-icon";
import { AcmeCrop54Icon } from "../generated/icons/classes/crop-5-4-icon";

customElements.define("acme-crop-5-4-icon", AcmeCrop54Icon);
