// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/crop-square-icon";
import { AcmeCropSquareIcon } from "../generated/icons/classes/crop-square-icon";

customElements.define("acme-crop-square-icon", AcmeCropSquareIcon);
