// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/crossword-icon";
import { AcmeCrosswordIcon } from "../generated/icons/classes/crossword-icon";

customElements.define("acme-crossword-icon", AcmeCrosswordIcon);
