// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/dashboard-2-edit-icon";
import { AcmeDashboard2EditIcon } from "../generated/icons/classes/dashboard-2-edit-icon";

customElements.define("acme-dashboard-2-edit-icon", AcmeDashboard2EditIcon);
