// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/data-loss-prevention-icon";
import { AcmeDataLossPreventionIcon } from "../generated/icons/classes/data-loss-prevention-icon";

customElements.define("acme-data-loss-prevention-icon", AcmeDataLossPreventionIcon);
