// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/data-exploration-icon";
import { AcmeDataExplorationIcon } from "../generated/icons/classes/data-exploration-icon";

customElements.define("acme-data-exploration-icon", AcmeDataExplorationIcon);
