// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/data-table-icon";
import { AcmeDataTableIcon } from "../generated/icons/classes/data-table-icon";

customElements.define("acme-data-table-icon", AcmeDataTableIcon);
