// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/delete-sweep-icon";
import { AcmeDeleteSweepIcon } from "../generated/icons/classes/delete-sweep-icon";

customElements.define("acme-delete-sweep-icon", AcmeDeleteSweepIcon);
