// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/delete-forever-icon";
import { AcmeDeleteForeverIcon } from "../generated/icons/classes/delete-forever-icon";

customElements.define("acme-delete-forever-icon", AcmeDeleteForeverIcon);
