// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/delete-icon";
import { AcmeDeleteIcon } from "../generated/icons/classes/delete-icon";

customElements.define("acme-delete-icon", AcmeDeleteIcon);
