// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/desktop-landscape-add-icon";
import { AcmeDesktopLandscapeAddIcon } from "../generated/icons/classes/desktop-landscape-add-icon";

customElements.define("acme-desktop-landscape-add-icon", AcmeDesktopLandscapeAddIcon);
