// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/deskphone-icon";
import { AcmeDeskphoneIcon } from "../generated/icons/classes/deskphone-icon";

customElements.define("acme-deskphone-icon", AcmeDeskphoneIcon);
