// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/details-icon";
import { AcmeDetailsIcon } from "../generated/icons/classes/details-icon";

customElements.define("acme-details-icon", AcmeDetailsIcon);
