// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/detector-status-icon";
import { AcmeDetectorStatusIcon } from "../generated/icons/classes/detector-status-icon";

customElements.define("acme-detector-status-icon", AcmeDetectorStatusIcon);
