// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/device-band-icon";
import { AcmeDeviceBandIcon } from "../generated/icons/classes/device-band-icon";

customElements.define("acme-device-band-icon", AcmeDeviceBandIcon);
