// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/devices-other-icon";
import { AcmeDevicesOtherIcon } from "../generated/icons/classes/devices-other-icon";

customElements.define("acme-devices-other-icon", AcmeDevicesOtherIcon);
