// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/dialpad-icon";
import { AcmeDialpadIcon } from "../generated/icons/classes/dialpad-icon";

customElements.define("acme-dialpad-icon", AcmeDialpadIcon);
