// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/dine-in-icon";
import { AcmeDineInIcon } from "../generated/icons/classes/dine-in-icon";

customElements.define("acme-dine-in-icon", AcmeDineInIcon);
