// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/directions-run-icon";
import { AcmeDirectionsRunIcon } from "../generated/icons/classes/directions-run-icon";

customElements.define("acme-directions-run-icon", AcmeDirectionsRunIcon);
