// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/diversity-2-icon";
import { AcmeDiversity2Icon } from "../generated/icons/classes/diversity-2-icon";

customElements.define("acme-diversity-2-icon", AcmeDiversity2Icon);
