// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/do-not-disturb-on-icon";
import { AcmeDoNotDisturbOnIcon } from "../generated/icons/classes/do-not-disturb-on-icon";

customElements.define("acme-do-not-disturb-on-icon", AcmeDoNotDisturbOnIcon);
