// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/dock-icon";
import { AcmeDockIcon } from "../generated/icons/classes/dock-icon";

customElements.define("acme-dock-icon", AcmeDockIcon);
