// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/domino-mask-icon";
import { AcmeDominoMaskIcon } from "../generated/icons/classes/domino-mask-icon";

customElements.define("acme-domino-mask-icon", AcmeDominoMaskIcon);
