// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/done-outline-icon";
import { AcmeDoneOutlineIcon } from "../generated/icons/classes/done-outline-icon";

customElements.define("acme-done-outline-icon", AcmeDoneOutlineIcon);
