// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/download-icon";
import { AcmeDownloadIcon } from "../generated/icons/classes/download-icon";

customElements.define("acme-download-icon", AcmeDownloadIcon);
