// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/download-for-offline-icon";
import { AcmeDownloadForOfflineIcon } from "../generated/icons/classes/download-for-offline-icon";

customElements.define("acme-download-for-offline-icon", AcmeDownloadForOfflineIcon);
