// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/drafts-icon";
import { AcmeDraftsIcon } from "../generated/icons/classes/drafts-icon";

customElements.define("acme-drafts-icon", AcmeDraftsIcon);
