// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/draw-icon";
import { AcmeDrawIcon } from "../generated/icons/classes/draw-icon";

customElements.define("acme-draw-icon", AcmeDrawIcon);
