// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/draw-abstract-icon";
import { AcmeDrawAbstractIcon } from "../generated/icons/classes/draw-abstract-icon";

customElements.define("acme-draw-abstract-icon", AcmeDrawAbstractIcon);
