// Generated by scripts/entries.ts. Do not edit.
import "./spinner";
import "../components/drawer-close/drawer-close";
import { AcmeDrawerClose } from "../components/drawer-close/drawer-close";

customElements.define("acme-drawer-close", AcmeDrawerClose);
