// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/drive-file-move-rtl-icon";
import { AcmeDriveFileMoveRtlIcon } from "../generated/icons/classes/drive-file-move-rtl-icon";

customElements.define("acme-drive-file-move-rtl-icon", AcmeDriveFileMoveRtlIcon);
