// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/dropdown-icon";
import { AcmeDropdownIcon } from "../generated/icons/classes/dropdown-icon";

customElements.define("acme-dropdown-icon", AcmeDropdownIcon);
