// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/earbuds-battery-icon";
import { AcmeEarbudsBatteryIcon } from "../generated/icons/classes/earbuds-battery-icon";

customElements.define("acme-earbuds-battery-icon", AcmeEarbudsBatteryIcon);
