// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/earbud-case-icon";
import { AcmeEarbudCaseIcon } from "../generated/icons/classes/earbud-case-icon";

customElements.define("acme-earbud-case-icon", AcmeEarbudCaseIcon);
