// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/earbud-left-icon";
import { AcmeEarbudLeftIcon } from "../generated/icons/classes/earbud-left-icon";

customElements.define("acme-earbud-left-icon", AcmeEarbudLeftIcon);
