// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/earthquake-icon";
import { AcmeEarthquakeIcon } from "../generated/icons/classes/earthquake-icon";

customElements.define("acme-earthquake-icon", AcmeEarthquakeIcon);
