// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/edit-audio-icon";
import { AcmeEditAudioIcon } from "../generated/icons/classes/edit-audio-icon";

customElements.define("acme-edit-audio-icon", AcmeEditAudioIcon);
