// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/egg-alt-icon";
import { AcmeEggAltIcon } from "../generated/icons/classes/egg-alt-icon";

customElements.define("acme-egg-alt-icon", AcmeEggAltIcon);
