// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/elevation-icon";
import { AcmeElevationIcon } from "../generated/icons/classes/elevation-icon";

customElements.define("acme-elevation-icon", AcmeElevationIcon);
