// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/emergency-share-off-icon";
import { AcmeEmergencyShareOffIcon } from "../generated/icons/classes/emergency-share-off-icon";

customElements.define("acme-emergency-share-off-icon", AcmeEmergencyShareOffIcon);
