// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/energy-program-saving-icon";
import { AcmeEnergyProgramSavingIcon } from "../generated/icons/classes/energy-program-saving-icon";

customElements.define("acme-energy-program-saving-icon", AcmeEnergyProgramSavingIcon);
