// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/energy-program-time-used-icon";
import { AcmeEnergyProgramTimeUsedIcon } from "../generated/icons/classes/energy-program-time-used-icon";

customElements.define("acme-energy-program-time-used-icon", AcmeEnergyProgramTimeUsedIcon);
