// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/enterprise-icon";
import { AcmeEnterpriseIcon } from "../generated/icons/classes/enterprise-icon";

customElements.define("acme-enterprise-icon", AcmeEnterpriseIcon);
