// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/equal-icon";
import { AcmeEqualIcon } from "../generated/icons/classes/equal-icon";

customElements.define("acme-equal-icon", AcmeEqualIcon);
