// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/eraser-size-4-icon";
import { AcmeEraserSize4Icon } from "../generated/icons/classes/eraser-size-4-icon";

customElements.define("acme-eraser-size-4-icon", AcmeEraserSize4Icon);
