// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/event-available-icon";
import { AcmeEventAvailableIcon } from "../generated/icons/classes/event-available-icon";

customElements.define("acme-event-available-icon", AcmeEventAvailableIcon);
