// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/eyebrow-icon";
import { AcmeEyebrowIcon } from "../generated/icons/classes/eyebrow-icon";

customElements.define("acme-eyebrow-icon", AcmeEyebrowIcon);
