// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/eyeglasses-icon";
import { AcmeEyeglassesIcon } from "../generated/icons/classes/eyeglasses-icon";

customElements.define("acme-eyeglasses-icon", AcmeEyeglassesIcon);
