// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/eyeglasses-2-sound-icon";
import { AcmeEyeglasses2SoundIcon } from "../generated/icons/classes/eyeglasses-2-sound-icon";

customElements.define("acme-eyeglasses-2-sound-icon", AcmeEyeglasses2SoundIcon);
