// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/eyeglasses-3-icon";
import { AcmeEyeglasses3Icon } from "../generated/icons/classes/eyeglasses-3-icon";

customElements.define("acme-eyeglasses-3-icon", AcmeEyeglasses3Icon);
