// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/eyeglasses-2-icon";
import { AcmeEyeglasses2Icon } from "../generated/icons/classes/eyeglasses-2-icon";

customElements.define("acme-eyeglasses-2-icon", AcmeEyeglasses2Icon);
