// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/family-home-icon";
import { AcmeFamilyHomeIcon } from "../generated/icons/classes/family-home-icon";

customElements.define("acme-family-home-icon", AcmeFamilyHomeIcon);
