// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/fastfood-icon";
import { AcmeFastfoodIcon } from "../generated/icons/classes/fastfood-icon";

customElements.define("acme-fastfood-icon", AcmeFastfoodIcon);
