// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/feature-search-icon";
import { AcmeFeatureSearchIcon } from "../generated/icons/classes/feature-search-icon";

customElements.define("acme-feature-search-icon", AcmeFeatureSearchIcon);
