// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/fiber-dvr-icon";
import { AcmeFiberDvrIcon } from "../generated/icons/classes/fiber-dvr-icon";

customElements.define("acme-fiber-dvr-icon", AcmeFiberDvrIcon);
