// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/fiber-smart-record-icon";
import { AcmeFiberSmartRecordIcon } from "../generated/icons/classes/fiber-smart-record-icon";

customElements.define("acme-fiber-smart-record-icon", AcmeFiberSmartRecordIcon);
