// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/file-save-icon";
import { AcmeFileSaveIcon } from "../generated/icons/classes/file-save-icon";

customElements.define("acme-file-save-icon", AcmeFileSaveIcon);
