// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/files-icon";
import { AcmeFilesIcon } from "../generated/icons/classes/files-icon";

customElements.define("acme-files-icon", AcmeFilesIcon);
