// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/filter-icon";
import { AcmeFilterIcon } from "../generated/icons/classes/filter-icon";

customElements.define("acme-filter-icon", AcmeFilterIcon);
