// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/filter-none-icon";
import { AcmeFilterNoneIcon } from "../generated/icons/classes/filter-none-icon";

customElements.define("acme-filter-none-icon", AcmeFilterNoneIcon);
