// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/filter-3-icon";
import { AcmeFilter3Icon } from "../generated/icons/classes/filter-3-icon";

customElements.define("acme-filter-3-icon", AcmeFilter3Icon);
