// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/find-replace-icon";
import { AcmeFindReplaceIcon } from "../generated/icons/classes/find-replace-icon";

customElements.define("acme-find-replace-icon", AcmeFindReplaceIcon);
