// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/fit-page-icon";
import { AcmeFitPageIcon } from "../generated/icons/classes/fit-page-icon";

customElements.define("acme-fit-page-icon", AcmeFitPageIcon);
