// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/flashlight-on-icon";
import { AcmeFlashlightOnIcon } from "../generated/icons/classes/flashlight-on-icon";

customElements.define("acme-flashlight-on-icon", AcmeFlashlightOnIcon);
