// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/flatware-icon";
import { AcmeFlatwareIcon } from "../generated/icons/classes/flatware-icon";

customElements.define("acme-flatware-icon", AcmeFlatwareIcon);
