// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/flex-direction-icon";
import { AcmeFlexDirectionIcon } from "../generated/icons/classes/flex-direction-icon";

customElements.define("acme-flex-direction-icon", AcmeFlexDirectionIcon);
