// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/flip-icon";
import { AcmeFlipIcon } from "../generated/icons/classes/flip-icon";

customElements.define("acme-flip-icon", AcmeFlipIcon);
