// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/floor-lamp-icon";
import { AcmeFloorLampIcon } from "../generated/icons/classes/floor-lamp-icon";

customElements.define("acme-floor-lamp-icon", AcmeFloorLampIcon);
