// Generated by scripts/entries.ts. Do not edit.
import "./button";
import "./collapsible";
import "./collapsible-content";
import "./collapsible-trigger";
import "../components/flow-diagram/flow-diagram";
import { AcmeFlowDiagram } from "../components/flow-diagram/flow-diagram";

customElements.define("acme-flow-diagram", AcmeFlowDiagram);
