// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/folder-data-icon";
import { AcmeFolderDataIcon } from "../generated/icons/classes/folder-data-icon";

customElements.define("acme-folder-data-icon", AcmeFolderDataIcon);
