// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/folder-managed-icon";
import { AcmeFolderManagedIcon } from "../generated/icons/classes/folder-managed-icon";

customElements.define("acme-folder-managed-icon", AcmeFolderManagedIcon);
