// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/folder-eye-icon";
import { AcmeFolderEyeIcon } from "../generated/icons/classes/folder-eye-icon";

customElements.define("acme-folder-eye-icon", AcmeFolderEyeIcon);
