// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/folder-match-icon";
import { AcmeFolderMatchIcon } from "../generated/icons/classes/folder-match-icon";

customElements.define("acme-folder-match-icon", AcmeFolderMatchIcon);
