// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/font-download-icon";
import { AcmeFontDownloadIcon } from "../generated/icons/classes/font-download-icon";

customElements.define("acme-font-download-icon", AcmeFontDownloadIcon);
