// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/fork-left-icon";
import { AcmeForkLeftIcon } from "../generated/icons/classes/fork-left-icon";

customElements.define("acme-fork-left-icon", AcmeForkLeftIcon);
