// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/format-line-spacing-icon";
import { AcmeFormatLineSpacingIcon } from "../generated/icons/classes/format-line-spacing-icon";

customElements.define("acme-format-line-spacing-icon", AcmeFormatLineSpacingIcon);
