// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/format-align-justify-icon";
import { AcmeFormatAlignJustifyIcon } from "../generated/icons/classes/format-align-justify-icon";

customElements.define("acme-format-align-justify-icon", AcmeFormatAlignJustifyIcon);
