// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/format-image-right-icon";
import { AcmeFormatImageRightIcon } from "../generated/icons/classes/format-image-right-icon";

customElements.define("acme-format-image-right-icon", AcmeFormatImageRightIcon);
