// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/format-letter-spacing-standard-icon";
import { AcmeFormatLetterSpacingStandardIcon } from "../generated/icons/classes/format-letter-spacing-standard-icon";

customElements.define("acme-format-letter-spacing-standard-icon", AcmeFormatLetterSpacingStandardIcon);
