// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/fort-icon";
import { AcmeFortIcon } from "../generated/icons/classes/fort-icon";

customElements.define("acme-fort-icon", AcmeFortIcon);
