// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/forward-icon";
import { AcmeForwardIcon } from "../generated/icons/classes/forward-icon";

customElements.define("acme-forward-icon", AcmeForwardIcon);
