// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/fullscreen-icon";
import { AcmeFullscreenIcon } from "../generated/icons/classes/fullscreen-icon";

customElements.define("acme-fullscreen-icon", AcmeFullscreenIcon);
