// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/fullscreen-exit-icon";
import { AcmeFullscreenExitIcon } from "../generated/icons/classes/fullscreen-exit-icon";

customElements.define("acme-fullscreen-exit-icon", AcmeFullscreenExitIcon);
