// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/game-button-r-icon";
import { AcmeGameButtonRIcon } from "../generated/icons/classes/game-button-r-icon";

customElements.define("acme-game-button-r-icon", AcmeGameButtonRIcon);
