// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/game-stick-l3-icon";
import { AcmeGameStickL3Icon } from "../generated/icons/classes/game-stick-l3-icon";

customElements.define("acme-game-stick-l3-icon", AcmeGameStickL3Icon);
