// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/garage-check-icon";
import { AcmeGarageCheckIcon } from "../generated/icons/classes/garage-check-icon";

customElements.define("acme-garage-check-icon", AcmeGarageCheckIcon);
