// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/gif-icon";
import { AcmeGifIcon } from "../generated/icons/classes/gif-icon";

customElements.define("acme-gif-icon", AcmeGifIcon);
