// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/gondola-lift-icon";
import { AcmeGondolaLiftIcon } from "../generated/icons/classes/gondola-lift-icon";

customElements.define("acme-gondola-lift-icon", AcmeGondolaLiftIcon);
