// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/google-wifi-icon";
import { AcmeGoogleWifiIcon } from "../generated/icons/classes/google-wifi-icon";

customElements.define("acme-google-wifi-icon", AcmeGoogleWifiIcon);
