// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/grid-guides-icon";
import { AcmeGridGuidesIcon } from "../generated/icons/classes/grid-guides-icon";

customElements.define("acme-grid-guides-icon", AcmeGridGuidesIcon);
