// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/group-off-icon";
import { AcmeGroupOffIcon } from "../generated/icons/classes/group-off-icon";

customElements.define("acme-group-off-icon", AcmeGroupOffIcon);
