// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/gynecology-icon";
import { AcmeGynecologyIcon } from "../generated/icons/classes/gynecology-icon";

customElements.define("acme-gynecology-icon", AcmeGynecologyIcon);
