// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/h-plus-mobiledata-badge-icon";
import { AcmeHPlusMobiledataBadgeIcon } from "../generated/icons/classes/h-plus-mobiledata-badge-icon";

customElements.define("acme-h-plus-mobiledata-badge-icon", AcmeHPlusMobiledataBadgeIcon);
