// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/handyman-icon";
import { AcmeHandymanIcon } from "../generated/icons/classes/handyman-icon";

customElements.define("acme-handyman-icon", AcmeHandymanIcon);
