// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/hard-disk-icon";
import { AcmeHardDiskIcon } from "../generated/icons/classes/hard-disk-icon";

customElements.define("acme-hard-disk-icon", AcmeHardDiskIcon);
