// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/hard-drive-2-icon";
import { AcmeHardDrive2Icon } from "../generated/icons/classes/hard-drive-2-icon";

customElements.define("acme-hard-drive-2-icon", AcmeHardDrive2Icon);
