// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/hdr-on-icon";
import { AcmeHdrOnIcon } from "../generated/icons/classes/hdr-on-icon";

customElements.define("acme-hdr-on-icon", AcmeHdrOnIcon);
