// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/headphones-battery-icon";
import { AcmeHeadphonesBatteryIcon } from "../generated/icons/classes/headphones-battery-icon";

customElements.define("acme-headphones-battery-icon", AcmeHeadphonesBatteryIcon);
