// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/health-metrics-icon";
import { AcmeHealthMetricsIcon } from "../generated/icons/classes/health-metrics-icon";

customElements.define("acme-health-metrics-icon", AcmeHealthMetricsIcon);
