// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/health-and-beauty-icon";
import { AcmeHealthAndBeautyIcon } from "../generated/icons/classes/health-and-beauty-icon";

customElements.define("acme-health-and-beauty-icon", AcmeHealthAndBeautyIcon);
