// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/health-cross-icon";
import { AcmeHealthCrossIcon } from "../generated/icons/classes/health-cross-icon";

customElements.define("acme-health-cross-icon", AcmeHealthCrossIcon);
