// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/heap-snapshot-thumbnail-icon";
import { AcmeHeapSnapshotThumbnailIcon } from "../generated/icons/classes/heap-snapshot-thumbnail-icon";

customElements.define("acme-heap-snapshot-thumbnail-icon", AcmeHeapSnapshotThumbnailIcon);
