// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/heap-snapshot-large-icon";
import { AcmeHeapSnapshotLargeIcon } from "../generated/icons/classes/heap-snapshot-large-icon";

customElements.define("acme-heap-snapshot-large-icon", AcmeHeapSnapshotLargeIcon);
