// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/hearing-icon";
import { AcmeHearingIcon } from "../generated/icons/classes/hearing-icon";

customElements.define("acme-hearing-icon", AcmeHearingIcon);
