// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/heart-broken-icon";
import { AcmeHeartBrokenIcon } from "../generated/icons/classes/heart-broken-icon";

customElements.define("acme-heart-broken-icon", AcmeHeartBrokenIcon);
