// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/help-icon";
import { AcmeHelpIcon } from "../generated/icons/classes/help-icon";

customElements.define("acme-help-icon", AcmeHelpIcon);
