// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/hexagon-icon";
import { AcmeHexagonIcon } from "../generated/icons/classes/hexagon-icon";

customElements.define("acme-hexagon-icon", AcmeHexagonIcon);
