// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/highlight-icon";
import { AcmeHighlightIcon } from "../generated/icons/classes/highlight-icon";

customElements.define("acme-highlight-icon", AcmeHighlightIcon);
