// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/highlight-keyboard-focus-icon";
import { AcmeHighlightKeyboardFocusIcon } from "../generated/icons/classes/highlight-keyboard-focus-icon";

customElements.define("acme-highlight-keyboard-focus-icon", AcmeHighlightKeyboardFocusIcon);
