// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/home-max-icon";
import { AcmeHomeMaxIcon } from "../generated/icons/classes/home-max-icon";

customElements.define("acme-home-max-icon", AcmeHomeMaxIcon);
