// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/horizontal-align-left-icon";
import { AcmeHorizontalAlignLeftIcon } from "../generated/icons/classes/horizontal-align-left-icon";

customElements.define("acme-horizontal-align-left-icon", AcmeHorizontalAlignLeftIcon);
