// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/houseboat-icon";
import { AcmeHouseboatIcon } from "../generated/icons/classes/houseboat-icon";

customElements.define("acme-houseboat-icon", AcmeHouseboatIcon);
