// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/id-card-icon";
import { AcmeIdCardIcon } from "../generated/icons/classes/id-card-icon";

customElements.define("acme-id-card-icon", AcmeIdCardIcon);
