// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/image-not-supported-icon";
import { AcmeImageNotSupportedIcon } from "../generated/icons/classes/image-not-supported-icon";

customElements.define("acme-image-not-supported-icon", AcmeImageNotSupportedIcon);
