// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/in-home-mode-icon";
import { AcmeInHomeModeIcon } from "../generated/icons/classes/in-home-mode-icon";

customElements.define("acme-in-home-mode-icon", AcmeInHomeModeIcon);
