// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/inbox-customize-icon";
import { AcmeInboxCustomizeIcon } from "../generated/icons/classes/inbox-customize-icon";

customElements.define("acme-inbox-customize-icon", AcmeInboxCustomizeIcon);
