// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/indeterminate-check-box-icon";
import { AcmeIndeterminateCheckBoxIcon } from "../generated/icons/classes/indeterminate-check-box-icon";

customElements.define("acme-indeterminate-check-box-icon", AcmeIndeterminateCheckBoxIcon);
