// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/ink-highlighter-icon";
import { AcmeInkHighlighterIcon } from "../generated/icons/classes/ink-highlighter-icon";

customElements.define("acme-ink-highlighter-icon", AcmeInkHighlighterIcon);
