// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/interactive-space-icon";
import { AcmeInteractiveSpaceIcon } from "../generated/icons/classes/interactive-space-icon";

customElements.define("acme-interactive-space-icon", AcmeInteractiveSpaceIcon);
