// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/integration-instructions-icon";
import { AcmeIntegrationInstructionsIcon } from "../generated/icons/classes/integration-instructions-icon";

customElements.define("acme-integration-instructions-icon", AcmeIntegrationInstructionsIcon);
