// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/inventory-icon";
import { AcmeInventoryIcon } from "../generated/icons/classes/inventory-icon";

customElements.define("acme-inventory-icon", AcmeInventoryIcon);
