// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/ios-icon";
import { AcmeIosIcon } from "../generated/icons/classes/ios-icon";

customElements.define("acme-ios-icon", AcmeIosIcon);
