// Generated by scripts/entries.ts. Do not edit.
import "../components/item-heading/item-heading";
import { AcmeItemHeading } from "../components/item-heading/item-heading";

customElements.define("acme-item-heading", AcmeItemHeading);
