// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/join-left-icon";
import { AcmeJoinLeftIcon } from "../generated/icons/classes/join-left-icon";

customElements.define("acme-join-left-icon", AcmeJoinLeftIcon);
