// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/join-right-icon";
import { AcmeJoinRightIcon } from "../generated/icons/classes/join-right-icon";

customElements.define("acme-join-right-icon", AcmeJoinRightIcon);
