// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/join-icon";
import { AcmeJoinIcon } from "../generated/icons/classes/join-icon";

customElements.define("acme-join-icon", AcmeJoinIcon);
