// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/join-full-icon";
import { AcmeJoinFullIcon } from "../generated/icons/classes/join-full-icon";

customElements.define("acme-join-full-icon", AcmeJoinFullIcon);
