// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/key-vertical-icon";
import { AcmeKeyVerticalIcon } from "../generated/icons/classes/key-vertical-icon";

customElements.define("acme-key-vertical-icon", AcmeKeyVerticalIcon);
