// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/keyboard-hide-icon";
import { AcmeKeyboardHideIcon } from "../generated/icons/classes/keyboard-hide-icon";

customElements.define("acme-keyboard-hide-icon", AcmeKeyboardHideIcon);
