// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/keyboard-capslock-badge-icon";
import { AcmeKeyboardCapslockBadgeIcon } from "../generated/icons/classes/keyboard-capslock-badge-icon";

customElements.define("acme-keyboard-capslock-badge-icon", AcmeKeyboardCapslockBadgeIcon);
