// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/keyboard-alt-icon";
import { AcmeKeyboardAltIcon } from "../generated/icons/classes/keyboard-alt-icon";

customElements.define("acme-keyboard-alt-icon", AcmeKeyboardAltIcon);
