// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/keyboard-keys-icon";
import { AcmeKeyboardKeysIcon } from "../generated/icons/classes/keyboard-keys-icon";

customElements.define("acme-keyboard-keys-icon", AcmeKeyboardKeysIcon);
