// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/keyboard-return-icon";
import { AcmeKeyboardReturnIcon } from "../generated/icons/classes/keyboard-return-icon";

customElements.define("acme-keyboard-return-icon", AcmeKeyboardReturnIcon);
