// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/keyboard-arrow-up-icon";
import { AcmeKeyboardArrowUpIcon } from "../generated/icons/classes/keyboard-arrow-up-icon";

customElements.define("acme-keyboard-arrow-up-icon", AcmeKeyboardArrowUpIcon);
