// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/label-important-icon";
import { AcmeLabelImportantIcon } from "../generated/icons/classes/label-important-icon";

customElements.define("acme-label-important-icon", AcmeLabelImportantIcon);
