// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/landslide-icon";
import { AcmeLandslideIcon } from "../generated/icons/classes/landslide-icon";

customElements.define("acme-landslide-icon", AcmeLandslideIcon);
