// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/language-us-dvorak-icon";
import { AcmeLanguageUsDvorakIcon } from "../generated/icons/classes/language-us-dvorak-icon";

customElements.define("acme-language-us-dvorak-icon", AcmeLanguageUsDvorakIcon);
