// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/language-chinese-quick-icon";
import { AcmeLanguageChineseQuickIcon } from "../generated/icons/classes/language-chinese-quick-icon";

customElements.define("acme-language-chinese-quick-icon", AcmeLanguageChineseQuickIcon);
