// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/language-korean-latin-icon";
import { AcmeLanguageKoreanLatinIcon } from "../generated/icons/classes/language-korean-latin-icon";

customElements.define("acme-language-korean-latin-icon", AcmeLanguageKoreanLatinIcon);
