// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/lens-blur-icon";
import { AcmeLensBlurIcon } from "../generated/icons/classes/lens-blur-icon";

customElements.define("acme-lens-blur-icon", AcmeLensBlurIcon);
