// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/library-music-icon";
import { AcmeLibraryMusicIcon } from "../generated/icons/classes/library-music-icon";

customElements.define("acme-library-music-icon", AcmeLibraryMusicIcon);
