// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/light-group-2-icon";
import { AcmeLightGroup2Icon } from "../generated/icons/classes/light-group-2-icon";

customElements.define("acme-light-group-2-icon", AcmeLightGroup2Icon);
