// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/lightbulb-2-icon";
import { AcmeLightbulb2Icon } from "../generated/icons/classes/lightbulb-2-icon";

customElements.define("acme-lightbulb-2-icon", AcmeLightbulb2Icon);
