// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/light-group-icon";
import { AcmeLightGroupIcon } from "../generated/icons/classes/light-group-icon";

customElements.define("acme-light-group-icon", AcmeLightGroupIcon);
