// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/line-start-arrow-notch-icon";
import { AcmeLineStartArrowNotchIcon } from "../generated/icons/classes/line-start-arrow-notch-icon";

customElements.define("acme-line-start-arrow-notch-icon", AcmeLineStartArrowNotchIcon);
