// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/line-weight-icon";
import { AcmeLineWeightIcon } from "../generated/icons/classes/line-weight-icon";

customElements.define("acme-line-weight-icon", AcmeLineWeightIcon);
