// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/link-off-icon";
import { AcmeLinkOffIcon } from "../generated/icons/classes/link-off-icon";

customElements.define("acme-link-off-icon", AcmeLinkOffIcon);
