// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/live-tv-icon";
import { AcmeLiveTvIcon } from "../generated/icons/classes/live-tv-icon";

customElements.define("acme-live-tv-icon", AcmeLiveTvIcon);
