// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/local-gas-station-icon";
import { AcmeLocalGasStationIcon } from "../generated/icons/classes/local-gas-station-icon";

customElements.define("acme-local-gas-station-icon", AcmeLocalGasStationIcon);
