// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/login-icon";
import { AcmeLoginIcon } from "../generated/icons/classes/login-icon";

customElements.define("acme-login-icon", AcmeLoginIcon);
