// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/low-density-icon";
import { AcmeLowDensityIcon } from "../generated/icons/classes/low-density-icon";

customElements.define("acme-low-density-icon", AcmeLowDensityIcon);
