// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/lte-mobiledata-badge-icon";
import { AcmeLteMobiledataBadgeIcon } from "../generated/icons/classes/lte-mobiledata-badge-icon";

customElements.define("acme-lte-mobiledata-badge-icon", AcmeLteMobiledataBadgeIcon);
