// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/macro-auto-icon";
import { AcmeMacroAutoIcon } from "../generated/icons/classes/macro-auto-icon";

customElements.define("acme-macro-auto-icon", AcmeMacroAutoIcon);
