// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/magnification-large-icon";
import { AcmeMagnificationLargeIcon } from "../generated/icons/classes/magnification-large-icon";

customElements.define("acme-magnification-large-icon", AcmeMagnificationLargeIcon);
