// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/mail-lock-icon";
import { AcmeMailLockIcon } from "../generated/icons/classes/mail-lock-icon";

customElements.define("acme-mail-lock-icon", AcmeMailLockIcon);
