// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/mail-spark-icon";
import { AcmeMailSparkIcon } from "../generated/icons/classes/mail-spark-icon";

customElements.define("acme-mail-spark-icon", AcmeMailSparkIcon);
