// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/map-pin-review-icon";
import { AcmeMapPinReviewIcon } from "../generated/icons/classes/map-pin-review-icon";

customElements.define("acme-map-pin-review-icon", AcmeMapPinReviewIcon);
