// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/mark-chat-read-icon";
import { AcmeMarkChatReadIcon } from "../generated/icons/classes/mark-chat-read-icon";

customElements.define("acme-mark-chat-read-icon", AcmeMarkChatReadIcon);
