// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/masked-transitions-icon";
import { AcmeMaskedTransitionsIcon } from "../generated/icons/classes/masked-transitions-icon";

customElements.define("acme-masked-transitions-icon", AcmeMaskedTransitionsIcon);
