// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/match-case-icon";
import { AcmeMatchCaseIcon } from "../generated/icons/classes/match-case-icon";

customElements.define("acme-match-case-icon", AcmeMatchCaseIcon);
