// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/media-output-icon";
import { AcmeMediaOutputIcon } from "../generated/icons/classes/media-output-icon";

customElements.define("acme-media-output-icon", AcmeMediaOutputIcon);
