// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/menu-book-icon";
import { AcmeMenuBookIcon } from "../generated/icons/classes/menu-book-icon";

customElements.define("acme-menu-book-icon", AcmeMenuBookIcon);
