// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/merge-type-icon";
import { AcmeMergeTypeIcon } from "../generated/icons/classes/merge-type-icon";

customElements.define("acme-merge-type-icon", AcmeMergeTypeIcon);
