// Generated by scripts/entries.ts. Do not edit.
import "../components/middle-truncate/middle-truncate";
import { AcmeMiddleTruncate } from "../components/middle-truncate/middle-truncate";

customElements.define("acme-middle-truncate", AcmeMiddleTruncate);
