// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/mintmark-icon";
import { AcmeMintmarkIcon } from "../generated/icons/classes/mintmark-icon";

customElements.define("acme-mintmark-icon", AcmeMintmarkIcon);
