// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/mitre-icon";
import { AcmeMitreIcon } from "../generated/icons/classes/mitre-icon";

customElements.define("acme-mitre-icon", AcmeMitreIcon);
