// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/mixture-med-icon";
import { AcmeMixtureMedIcon } from "../generated/icons/classes/mixture-med-icon";

customElements.define("acme-mixture-med-icon", AcmeMixtureMedIcon);
