// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/mobile-theft-icon";
import { AcmeMobileTheftIcon } from "../generated/icons/classes/mobile-theft-icon";

customElements.define("acme-mobile-theft-icon", AcmeMobileTheftIcon);
