// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/mobile-charge-icon";
import { AcmeMobileChargeIcon } from "../generated/icons/classes/mobile-charge-icon";

customElements.define("acme-mobile-charge-icon", AcmeMobileChargeIcon);
