// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/mobile-screensaver-icon";
import { AcmeMobileScreensaverIcon } from "../generated/icons/classes/mobile-screensaver-icon";

customElements.define("acme-mobile-screensaver-icon", AcmeMobileScreensaverIcon);
