// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/mobile-text-2-icon";
import { AcmeMobileText2Icon } from "../generated/icons/classes/mobile-text-2-icon";

customElements.define("acme-mobile-text-2-icon", AcmeMobileText2Icon);
