// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/mobile-landscape-icon";
import { AcmeMobileLandscapeIcon } from "../generated/icons/classes/mobile-landscape-icon";

customElements.define("acme-mobile-landscape-icon", AcmeMobileLandscapeIcon);
