// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/mobile-layout-icon";
import { AcmeMobileLayoutIcon } from "../generated/icons/classes/mobile-layout-icon";

customElements.define("acme-mobile-layout-icon", AcmeMobileLayoutIcon);
