// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/mobile-lock-landscape-icon";
import { AcmeMobileLockLandscapeIcon } from "../generated/icons/classes/mobile-lock-landscape-icon";

customElements.define("acme-mobile-lock-landscape-icon", AcmeMobileLockLandscapeIcon);
