// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/mode-off-on-icon";
import { AcmeModeOffOnIcon } from "../generated/icons/classes/mode-off-on-icon";

customElements.define("acme-mode-off-on-icon", AcmeModeOffOnIcon);
