// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/money-icon";
import { AcmeMoneyIcon } from "../generated/icons/classes/money-icon";

customElements.define("acme-money-icon", AcmeMoneyIcon);
