// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/monitor-icon";
import { AcmeMonitorIcon } from "../generated/icons/classes/monitor-icon";

customElements.define("acme-monitor-icon", AcmeMonitorIcon);
