// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/moon-stars-icon";
import { AcmeMoonStarsIcon } from "../generated/icons/classes/moon-stars-icon";

customElements.define("acme-moon-stars-icon", AcmeMoonStarsIcon);
