// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/motion-sensor-alert-icon";
import { AcmeMotionSensorAlertIcon } from "../generated/icons/classes/motion-sensor-alert-icon";

customElements.define("acme-motion-sensor-alert-icon", AcmeMotionSensorAlertIcon);
