// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/motion-sensor-idle-icon";
import { AcmeMotionSensorIdleIcon } from "../generated/icons/classes/motion-sensor-idle-icon";

customElements.define("acme-motion-sensor-idle-icon", AcmeMotionSensorIdleIcon);
