// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/move-location-icon";
import { AcmeMoveLocationIcon } from "../generated/icons/classes/move-location-icon";

customElements.define("acme-move-location-icon", AcmeMoveLocationIcon);
