// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/move-up-icon";
import { AcmeMoveUpIcon } from "../generated/icons/classes/move-up-icon";

customElements.define("acme-move-up-icon", AcmeMoveUpIcon);
