// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/move-selection-right-icon";
import { AcmeMoveSelectionRightIcon } from "../generated/icons/classes/move-selection-right-icon";

customElements.define("acme-move-selection-right-icon", AcmeMoveSelectionRightIcon);
