// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/move-icon";
import { AcmeMoveIcon } from "../generated/icons/classes/move-icon";

customElements.define("acme-move-icon", AcmeMoveIcon);
