// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/moving-beds-icon";
import { AcmeMovingBedsIcon } from "../generated/icons/classes/moving-beds-icon";

customElements.define("acme-moving-beds-icon", AcmeMovingBedsIcon);
