// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/moving-icon";
import { AcmeMovingIcon } from "../generated/icons/classes/moving-icon";

customElements.define("acme-moving-icon", AcmeMovingIcon);
