// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/movie-speaker-icon";
import { AcmeMovieSpeakerIcon } from "../generated/icons/classes/movie-speaker-icon";

customElements.define("acme-movie-speaker-icon", AcmeMovieSpeakerIcon);
