// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/mp-icon";
import { AcmeMpIcon } from "../generated/icons/classes/mp-icon";

customElements.define("acme-mp-icon", AcmeMpIcon);
