// Generated by scripts/entries.ts. Do not edit.
import "./expand-more-icon";
import "../components/multi-select/multi-select";
import { AcmeMultiSelect } from "../components/multi-select/multi-select";

customElements.define("acme-multi-select", AcmeMultiSelect);
