// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/multiple-airports-icon";
import { AcmeMultipleAirportsIcon } from "../generated/icons/classes/multiple-airports-icon";

customElements.define("acme-multiple-airports-icon", AcmeMultipleAirportsIcon);
