// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/mystery-icon";
import { AcmeMysteryIcon } from "../generated/icons/classes/mystery-icon";

customElements.define("acme-mystery-icon", AcmeMysteryIcon);
