// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/near-me-disabled-icon";
import { AcmeNearMeDisabledIcon } from "../generated/icons/classes/near-me-disabled-icon";

customElements.define("acme-near-me-disabled-icon", AcmeNearMeDisabledIcon);
