// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/nest-clock-farsight-digital-icon";
import { AcmeNestClockFarsightDigitalIcon } from "../generated/icons/classes/nest-clock-farsight-digital-icon";

customElements.define("acme-nest-clock-farsight-digital-icon", AcmeNestClockFarsightDigitalIcon);
