// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/nest-wifi-mistral-icon";
import { AcmeNestWifiMistralIcon } from "../generated/icons/classes/nest-wifi-mistral-icon";

customElements.define("acme-nest-wifi-mistral-icon", AcmeNestWifiMistralIcon);
