// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/nest-wake-on-approach-icon";
import { AcmeNestWakeOnApproachIcon } from "../generated/icons/classes/nest-wake-on-approach-icon";

customElements.define("acme-nest-wake-on-approach-icon", AcmeNestWakeOnApproachIcon);
