// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/nest-farsight-dual-icon";
import { AcmeNestFarsightDualIcon } from "../generated/icons/classes/nest-farsight-dual-icon";

customElements.define("acme-nest-farsight-dual-icon", AcmeNestFarsightDualIcon);
