// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/nest-gale-wifi-icon";
import { AcmeNestGaleWifiIcon } from "../generated/icons/classes/nest-gale-wifi-icon";

customElements.define("acme-nest-gale-wifi-icon", AcmeNestGaleWifiIcon);
