// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/nest-cam-outdoor-icon";
import { AcmeNestCamOutdoorIcon } from "../generated/icons/classes/nest-cam-outdoor-icon";

customElements.define("acme-nest-cam-outdoor-icon", AcmeNestCamOutdoorIcon);
