// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/nest-cam-wall-mount-icon";
import { AcmeNestCamWallMountIcon } from "../generated/icons/classes/nest-cam-wall-mount-icon";

customElements.define("acme-nest-cam-wall-mount-icon", AcmeNestCamWallMountIcon);
