// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/network-wifi-1-bar-icon";
import { AcmeNetworkWifi1BarIcon } from "../generated/icons/classes/network-wifi-1-bar-icon";

customElements.define("acme-network-wifi-1-bar-icon", AcmeNetworkWifi1BarIcon);
