// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/network-locked-icon";
import { AcmeNetworkLockedIcon } from "../generated/icons/classes/network-locked-icon";

customElements.define("acme-network-locked-icon", AcmeNetworkLockedIcon);
