// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/network-wifi-3-bar-icon";
import { AcmeNetworkWifi3BarIcon } from "../generated/icons/classes/network-wifi-3-bar-icon";

customElements.define("acme-network-wifi-3-bar-icon", AcmeNetworkWifi3BarIcon);
