// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/network-wifi-2-bar-locked-icon";
import { AcmeNetworkWifi2BarLockedIcon } from "../generated/icons/classes/network-wifi-2-bar-locked-icon";

customElements.define("acme-network-wifi-2-bar-locked-icon", AcmeNetworkWifi2BarLockedIcon);
