// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/new-releases-icon";
import { AcmeNewReleasesIcon } from "../generated/icons/classes/new-releases-icon";

customElements.define("acme-new-releases-icon", AcmeNewReleasesIcon);
