// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/nfc-off-icon";
import { AcmeNfcOffIcon } from "../generated/icons/classes/nfc-off-icon";

customElements.define("acme-nfc-off-icon", AcmeNfcOffIcon);
