// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/nfc-icon";
import { AcmeNfcIcon } from "../generated/icons/classes/nfc-icon";

customElements.define("acme-nfc-icon", AcmeNfcIcon);
