// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/no-crash-icon";
import { AcmeNoCrashIcon } from "../generated/icons/classes/no-crash-icon";

customElements.define("acme-no-crash-icon", AcmeNoCrashIcon);
