// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/no-encryption-icon";
import { AcmeNoEncryptionIcon } from "../generated/icons/classes/no-encryption-icon";

customElements.define("acme-no-encryption-icon", AcmeNoEncryptionIcon);
