// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/north-icon";
import { AcmeNorthIcon } from "../generated/icons/classes/north-icon";

customElements.define("acme-north-icon", AcmeNorthIcon);
