// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/notifications-paused-icon";
import { AcmeNotificationsPausedIcon } from "../generated/icons/classes/notifications-paused-icon";

customElements.define("acme-notifications-paused-icon", AcmeNotificationsPausedIcon);
