// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/ods-icon";
import { AcmeOdsIcon } from "../generated/icons/classes/ods-icon";

customElements.define("acme-ods-icon", AcmeOdsIcon);
