// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/offline-pin-icon";
import { AcmeOfflinePinIcon } from "../generated/icons/classes/offline-pin-icon";

customElements.define("acme-offline-pin-icon", AcmeOfflinePinIcon);
