// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/opacity-icon";
import { AcmeOpacityIcon } from "../generated/icons/classes/opacity-icon";

customElements.define("acme-opacity-icon", AcmeOpacityIcon);
