// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/open-in-new-off-icon";
import { AcmeOpenInNewOffIcon } from "../generated/icons/classes/open-in-new-off-icon";

customElements.define("acme-open-in-new-off-icon", AcmeOpenInNewOffIcon);
