// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/oral-disease-icon";
import { AcmeOralDiseaseIcon } from "../generated/icons/classes/oral-disease-icon";

customElements.define("acme-oral-disease-icon", AcmeOralDiseaseIcon);
