// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/order-play-icon";
import { AcmeOrderPlayIcon } from "../generated/icons/classes/order-play-icon";

customElements.define("acme-order-play-icon", AcmeOrderPlayIcon);
