// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/overview-key-icon";
import { AcmeOverviewKeyIcon } from "../generated/icons/classes/overview-key-icon";

customElements.define("acme-overview-key-icon", AcmeOverviewKeyIcon);
