// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/padding-icon";
import { AcmePaddingIcon } from "../generated/icons/classes/padding-icon";

customElements.define("acme-padding-icon", AcmePaddingIcon);
