// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/page-control-icon";
import { AcmePageControlIcon } from "../generated/icons/classes/page-control-icon";

customElements.define("acme-page-control-icon", AcmePageControlIcon);
