// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/pageview-icon";
import { AcmePageviewIcon } from "../generated/icons/classes/pageview-icon";

customElements.define("acme-pageview-icon", AcmePageviewIcon);
