// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/pan-tool-alt-icon";
import { AcmePanToolAltIcon } from "../generated/icons/classes/pan-tool-alt-icon";

customElements.define("acme-pan-tool-alt-icon", AcmePanToolAltIcon);
