// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/partner-exchange-icon";
import { AcmePartnerExchangeIcon } from "../generated/icons/classes/partner-exchange-icon";

customElements.define("acme-partner-exchange-icon", AcmePartnerExchangeIcon);
