// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/password-icon";
import { AcmePasswordIcon } from "../generated/icons/classes/password-icon";

customElements.define("acme-password-icon", AcmePasswordIcon);
