// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/patient-list-icon";
import { AcmePatientListIcon } from "../generated/icons/classes/patient-list-icon";

customElements.define("acme-patient-list-icon", AcmePatientListIcon);
