// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/percent-discount-icon";
import { AcmePercentDiscountIcon } from "../generated/icons/classes/percent-discount-icon";

customElements.define("acme-percent-discount-icon", AcmePercentDiscountIcon);
