// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/perm-phone-msg-icon";
import { AcmePermPhoneMsgIcon } from "../generated/icons/classes/perm-phone-msg-icon";

customElements.define("acme-perm-phone-msg-icon", AcmePermPhoneMsgIcon);
