// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/perm-camera-mic-icon";
import { AcmePermCameraMicIcon } from "../generated/icons/classes/perm-camera-mic-icon";

customElements.define("acme-perm-camera-mic-icon", AcmePermCameraMicIcon);
