// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/person-4-icon";
import { AcmePerson4Icon } from "../generated/icons/classes/person-4-icon";

customElements.define("acme-person-4-icon", AcmePerson4Icon);
