// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/person-cancel-icon";
import { AcmePersonCancelIcon } from "../generated/icons/classes/person-cancel-icon";

customElements.define("acme-person-cancel-icon", AcmePersonCancelIcon);
