// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/person-filled-icon";
import { AcmePersonFilledIcon } from "../generated/icons/classes/person-filled-icon";

customElements.define("acme-person-filled-icon", AcmePersonFilledIcon);
