// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/person-text-icon";
import { AcmePersonTextIcon } from "../generated/icons/classes/person-text-icon";

customElements.define("acme-person-text-icon", AcmePersonTextIcon);
