// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/person-add-disabled-icon";
import { AcmePersonAddDisabledIcon } from "../generated/icons/classes/person-add-disabled-icon";

customElements.define("acme-person-add-disabled-icon", AcmePersonAddDisabledIcon);
