// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/person-edit-icon";
import { AcmePersonEditIcon } from "../generated/icons/classes/person-edit-icon";

customElements.define("acme-person-edit-icon", AcmePersonEditIcon);
