// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/person-alert-icon";
import { AcmePersonAlertIcon } from "../generated/icons/classes/person-alert-icon";

customElements.define("acme-person-alert-icon", AcmePersonAlertIcon);
