// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/pest-control-rodent-icon";
import { AcmePestControlRodentIcon } from "../generated/icons/classes/pest-control-rodent-icon";

customElements.define("acme-pest-control-rodent-icon", AcmePestControlRodentIcon);
