// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/pets-icon";
import { AcmePetsIcon } from "../generated/icons/classes/pets-icon";

customElements.define("acme-pets-icon", AcmePetsIcon);
