// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/photo-size-select-large-icon";
import { AcmePhotoSizeSelectLargeIcon } from "../generated/icons/classes/photo-size-select-large-icon";

customElements.define("acme-photo-size-select-large-icon", AcmePhotoSizeSelectLargeIcon);
