// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/php-icon";
import { AcmePhpIcon } from "../generated/icons/classes/php-icon";

customElements.define("acme-php-icon", AcmePhpIcon);
