// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/pie-chart-icon";
import { AcmePieChartIcon } from "../generated/icons/classes/pie-chart-icon";

customElements.define("acme-pie-chart-icon", AcmePieChartIcon);
