// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/pill-off-icon";
import { AcmePillOffIcon } from "../generated/icons/classes/pill-off-icon";

customElements.define("acme-pill-off-icon", AcmePillOffIcon);
