// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/pin-drop-icon";
import { AcmePinDropIcon } from "../generated/icons/classes/pin-drop-icon";

customElements.define("acme-pin-drop-icon", AcmePinDropIcon);
