// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/play-lesson-icon";
import { AcmePlayLessonIcon } from "../generated/icons/classes/play-lesson-icon";

customElements.define("acme-play-lesson-icon", AcmePlayLessonIcon);
