// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/playlist-remove-icon";
import { AcmePlaylistRemoveIcon } from "../generated/icons/classes/playlist-remove-icon";

customElements.define("acme-playlist-remove-icon", AcmePlaylistRemoveIcon);
