// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/playlist-add-circle-icon";
import { AcmePlaylistAddCircleIcon } from "../generated/icons/classes/playlist-add-circle-icon";

customElements.define("acme-playlist-add-circle-icon", AcmePlaylistAddCircleIcon);
