// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/point-of-sale-icon";
import { AcmePointOfSaleIcon } from "../generated/icons/classes/point-of-sale-icon";

customElements.define("acme-point-of-sale-icon", AcmePointOfSaleIcon);
