// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/point-scan-icon";
import { AcmePointScanIcon } from "../generated/icons/classes/point-scan-icon";

customElements.define("acme-point-scan-icon", AcmePointScanIcon);
