// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/portrait-lighting-off-icon";
import { AcmePortraitLightingOffIcon } from "../generated/icons/classes/portrait-lighting-off-icon";

customElements.define("acme-portrait-lighting-off-icon", AcmePortraitLightingOffIcon);
