// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/position-bottom-left-icon";
import { AcmePositionBottomLeftIcon } from "../generated/icons/classes/position-bottom-left-icon";

customElements.define("acme-position-bottom-left-icon", AcmePositionBottomLeftIcon);
