// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/post-add-icon";
import { AcmePostAddIcon } from "../generated/icons/classes/post-add-icon";

customElements.define("acme-post-add-icon", AcmePostAddIcon);
