// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/power-settings-circle-icon";
import { AcmePowerSettingsCircleIcon } from "../generated/icons/classes/power-settings-circle-icon";

customElements.define("acme-power-settings-circle-icon", AcmePowerSettingsCircleIcon);
