// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/preview-icon";
import { AcmePreviewIcon } from "../generated/icons/classes/preview-icon";

customElements.define("acme-preview-icon", AcmePreviewIcon);
