// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/print-icon";
import { AcmePrintIcon } from "../generated/icons/classes/print-icon";

customElements.define("acme-print-icon", AcmePrintIcon);
