// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/priority-high-icon";
import { AcmePriorityHighIcon } from "../generated/icons/classes/priority-high-icon";

customElements.define("acme-priority-high-icon", AcmePriorityHighIcon);
