// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/process-chart-icon";
import { AcmeProcessChartIcon } from "../generated/icons/classes/process-chart-icon";

customElements.define("acme-process-chart-icon", AcmeProcessChartIcon);
