// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/public-off-icon";
import { AcmePublicOffIcon } from "../generated/icons/classes/public-off-icon";

customElements.define("acme-public-off-icon", AcmePublicOffIcon);
