// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/push-pin-icon";
import { AcmePushPinIcon } from "../generated/icons/classes/push-pin-icon";

customElements.define("acme-push-pin-icon", AcmePushPinIcon);
