// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/qr-code-scanner-icon";
import { AcmeQrCodeScannerIcon } from "../generated/icons/classes/qr-code-scanner-icon";

customElements.define("acme-qr-code-scanner-icon", AcmeQrCodeScannerIcon);
