// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/quick-reference-all-icon";
import { AcmeQuickReferenceAllIcon } from "../generated/icons/classes/quick-reference-all-icon";

customElements.define("acme-quick-reference-all-icon", AcmeQuickReferenceAllIcon);
