// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/ramp-left-icon";
import { AcmeRampLeftIcon } from "../generated/icons/classes/ramp-left-icon";

customElements.define("acme-ramp-left-icon", AcmeRampLeftIcon);
