// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/range-hood-icon";
import { AcmeRangeHoodIcon } from "../generated/icons/classes/range-hood-icon";

customElements.define("acme-range-hood-icon", AcmeRangeHoodIcon);
