// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/raw-on-icon";
import { AcmeRawOnIcon } from "../generated/icons/classes/raw-on-icon";

customElements.define("acme-raw-on-icon", AcmeRawOnIcon);
