// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/rear-camera-icon";
import { AcmeRearCameraIcon } from "../generated/icons/classes/rear-camera-icon";

customElements.define("acme-rear-camera-icon", AcmeRearCameraIcon);
