// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/rectangle-icon";
import { AcmeRectangleIcon } from "../generated/icons/classes/rectangle-icon";

customElements.define("acme-rectangle-icon", AcmeRectangleIcon);
