// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/recycling-icon";
import { AcmeRecyclingIcon } from "../generated/icons/classes/recycling-icon";

customElements.define("acme-recycling-icon", AcmeRecyclingIcon);
