// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/redo-icon";
import { AcmeRedoIcon } from "../generated/icons/classes/redo-icon";

customElements.define("acme-redo-icon", AcmeRedoIcon);
