// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/reduce-capacity-icon";
import { AcmeReduceCapacityIcon } from "../generated/icons/classes/reduce-capacity-icon";

customElements.define("acme-reduce-capacity-icon", AcmeReduceCapacityIcon);
