// Generated by scripts/entries.ts. Do not edit.
import "../components/relative-time/relative-time";
import { AcmeRelativeTime } from "../components/relative-time/relative-time";

customElements.define("acme-relative-time", AcmeRelativeTime);
