// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/reply-icon";
import { AcmeReplyIcon } from "../generated/icons/classes/reply-icon";

customElements.define("acme-reply-icon", AcmeReplyIcon);
