// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/replace-image-icon";
import { AcmeReplaceImageIcon } from "../generated/icons/classes/replace-image-icon";

customElements.define("acme-replace-image-icon", AcmeReplaceImageIcon);
