// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/replace-audio-icon";
import { AcmeReplaceAudioIcon } from "../generated/icons/classes/replace-audio-icon";

customElements.define("acme-replace-audio-icon", AcmeReplaceAudioIcon);
