// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/request-quote-icon";
import { AcmeRequestQuoteIcon } from "../generated/icons/classes/request-quote-icon";

customElements.define("acme-request-quote-icon", AcmeRequestQuoteIcon);
