// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/reset-exposure-icon";
import { AcmeResetExposureIcon } from "../generated/icons/classes/reset-exposure-icon";

customElements.define("acme-reset-exposure-icon", AcmeResetExposureIcon);
