// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/resume-icon";
import { AcmeResumeIcon } from "../generated/icons/classes/resume-icon";

customElements.define("acme-resume-icon", AcmeResumeIcon);
