// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/right-panel-close-icon";
import { AcmeRightPanelCloseIcon } from "../generated/icons/classes/right-panel-close-icon";

customElements.define("acme-right-panel-close-icon", AcmeRightPanelCloseIcon);
