// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/room-service-icon";
import { AcmeRoomServiceIcon } from "../generated/icons/classes/room-service-icon";

customElements.define("acme-room-service-icon", AcmeRoomServiceIcon);
