// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/router-off-icon";
import { AcmeRouterOffIcon } from "../generated/icons/classes/router-off-icon";

customElements.define("acme-router-off-icon", AcmeRouterOffIcon);
