// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/rowing-icon";
import { AcmeRowingIcon } from "../generated/icons/classes/rowing-icon";

customElements.define("acme-rowing-icon", AcmeRowingIcon);
