// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/satellite-alt-icon";
import { AcmeSatelliteAltIcon } from "../generated/icons/classes/satellite-alt-icon";

customElements.define("acme-satellite-alt-icon", AcmeSatelliteAltIcon);
