// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/save-icon";
import { AcmeSaveIcon } from "../generated/icons/classes/save-icon";

customElements.define("acme-save-icon", AcmeSaveIcon);
