// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/sd-card-icon";
import { AcmeSdCardIcon } from "../generated/icons/classes/sd-card-icon";

customElements.define("acme-sd-card-icon", AcmeSdCardIcon);
