// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/sd-icon";
import { AcmeSdIcon } from "../generated/icons/classes/sd-icon";

customElements.define("acme-sd-icon", AcmeSdIcon);
