// Generated by scripts/entries.ts. Do not edit.
import "./input";
import "./kbd";
import "./spinner";
import { AcmeSearch } from "../components/search/search";

customElements.define("acme-search", AcmeSearch);
