// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/search-off-icon";
import { AcmeSearchOffIcon } from "../generated/icons/classes/search-off-icon";

customElements.define("acme-search-off-icon", AcmeSearchOffIcon);
