// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/security-icon";
import { AcmeSecurityIcon } from "../generated/icons/classes/security-icon";

customElements.define("acme-security-icon", AcmeSecurityIcon);
