// Generated by scripts/entries.ts. Do not edit.
import "./group";
import "../internal/define/selection-indicator";
import "../components/segmented-control/segmented-control";
import { AcmeSegmentedControl } from "../components/segmented-control/segmented-control";

customElements.define("acme-segmented-control", AcmeSegmentedControl);
