// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/segment-icon";
import { AcmeSegmentIcon } from "../generated/icons/classes/segment-icon";

customElements.define("acme-segment-icon", AcmeSegmentIcon);
