// Generated by scripts/entries.ts. Do not edit.
import "../components/segmented-control-item/segmented-control-item";
import { AcmeSegmentedControlItem } from "../components/segmented-control-item/segmented-control-item";

customElements.define("acme-segmented-control-item", AcmeSegmentedControlItem);
