// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/self-care-icon";
import { AcmeSelfCareIcon } from "../generated/icons/classes/self-care-icon";

customElements.define("acme-self-care-icon", AcmeSelfCareIcon);
