// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/send-and-archive-icon";
import { AcmeSendAndArchiveIcon } from "../generated/icons/classes/send-and-archive-icon";

customElements.define("acme-send-and-archive-icon", AcmeSendAndArchiveIcon);
