// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/sensor-occupied-icon";
import { AcmeSensorOccupiedIcon } from "../generated/icons/classes/sensor-occupied-icon";

customElements.define("acme-sensor-occupied-icon", AcmeSensorOccupiedIcon);
