// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/sensors-off-icon";
import { AcmeSensorsOffIcon } from "../generated/icons/classes/sensors-off-icon";

customElements.define("acme-sensors-off-icon", AcmeSensorsOffIcon);
