// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/sensor-door-icon";
import { AcmeSensorDoorIcon } from "../generated/icons/classes/sensor-door-icon";

customElements.define("acme-sensor-door-icon", AcmeSensorDoorIcon);
