// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/sentiment-neutral-icon";
import { AcmeSentimentNeutralIcon } from "../generated/icons/classes/sentiment-neutral-icon";

customElements.define("acme-sentiment-neutral-icon", AcmeSentimentNeutralIcon);
