// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/sentiment-excited-icon";
import { AcmeSentimentExcitedIcon } from "../generated/icons/classes/sentiment-excited-icon";

customElements.define("acme-sentiment-excited-icon", AcmeSentimentExcitedIcon);
