// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/sentiment-content-icon";
import { AcmeSentimentContentIcon } from "../generated/icons/classes/sentiment-content-icon";

customElements.define("acme-sentiment-content-icon", AcmeSentimentContentIcon);
