// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/sentiment-worried-icon";
import { AcmeSentimentWorriedIcon } from "../generated/icons/classes/sentiment-worried-icon";

customElements.define("acme-sentiment-worried-icon", AcmeSentimentWorriedIcon);
