// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/settings-cell-icon";
import { AcmeSettingsCellIcon } from "../generated/icons/classes/settings-cell-icon";

customElements.define("acme-settings-cell-icon", AcmeSettingsCellIcon);
