// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/settings-heart-icon";
import { AcmeSettingsHeartIcon } from "../generated/icons/classes/settings-heart-icon";

customElements.define("acme-settings-heart-icon", AcmeSettingsHeartIcon);
