// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/settings-input-hdmi-icon";
import { AcmeSettingsInputHdmiIcon } from "../generated/icons/classes/settings-input-hdmi-icon";

customElements.define("acme-settings-input-hdmi-icon", AcmeSettingsInputHdmiIcon);
