// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/settings-bluetooth-icon";
import { AcmeSettingsBluetoothIcon } from "../generated/icons/classes/settings-bluetooth-icon";

customElements.define("acme-settings-bluetooth-icon", AcmeSettingsBluetoothIcon);
