// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/shadow-minus-icon";
import { AcmeShadowMinusIcon } from "../generated/icons/classes/shadow-minus-icon";

customElements.define("acme-shadow-minus-icon", AcmeShadowMinusIcon);
