// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/shades-icon";
import { AcmeShadesIcon } from "../generated/icons/classes/shades-icon";

customElements.define("acme-shades-icon", AcmeShadesIcon);
