// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/shelves-icon";
import { AcmeShelvesIcon } from "../generated/icons/classes/shelves-icon";

customElements.define("acme-shelves-icon", AcmeShelvesIcon);
