// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/shield-question-icon";
import { AcmeShieldQuestionIcon } from "../generated/icons/classes/shield-question-icon";

customElements.define("acme-shield-question-icon", AcmeShieldQuestionIcon);
