// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/shift-lock-off-icon";
import { AcmeShiftLockOffIcon } from "../generated/icons/classes/shift-lock-off-icon";

customElements.define("acme-shift-lock-off-icon", AcmeShiftLockOffIcon);
