// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/shopping-cart-off-icon";
import { AcmeShoppingCartOffIcon } from "../generated/icons/classes/shopping-cart-off-icon";

customElements.define("acme-shopping-cart-off-icon", AcmeShoppingCartOffIcon);
