// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/short-stay-icon";
import { AcmeShortStayIcon } from "../generated/icons/classes/short-stay-icon";

customElements.define("acme-short-stay-icon", AcmeShortStayIcon);
