// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/shower-icon";
import { AcmeShowerIcon } from "../generated/icons/classes/shower-icon";

customElements.define("acme-shower-icon", AcmeShowerIcon);
