// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/side-navigation-icon";
import { AcmeSideNavigationIcon } from "../generated/icons/classes/side-navigation-icon";

customElements.define("acme-side-navigation-icon", AcmeSideNavigationIcon);
