// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/signal-wifi-statusbar-not-connected-icon";
import { AcmeSignalWifiStatusbarNotConnectedIcon } from "../generated/icons/classes/signal-wifi-statusbar-not-connected-icon";

customElements.define("acme-signal-wifi-statusbar-not-connected-icon", AcmeSignalWifiStatusbarNotConnectedIcon);
