// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/signpost-icon";
import { AcmeSignpostIcon } from "../generated/icons/classes/signpost-icon";

customElements.define("acme-signpost-icon", AcmeSignpostIcon);
