// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/signal-cellular-connected-no-internet-0-bar-icon";
import { AcmeSignalCellularConnectedNoInternet0BarIcon } from "../generated/icons/classes/signal-cellular-connected-no-internet-0-bar-icon";

customElements.define("acme-signal-cellular-connected-no-internet-0-bar-icon", AcmeSignalCellularConnectedNoInternet0BarIcon);
