// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/signal-cellular-off-icon";
import { AcmeSignalCellularOffIcon } from "../generated/icons/classes/signal-cellular-off-icon";

customElements.define("acme-signal-cellular-off-icon", AcmeSignalCellularOffIcon);
