// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/sim-card-download-icon";
import { AcmeSimCardDownloadIcon } from "../generated/icons/classes/sim-card-download-icon";

customElements.define("acme-sim-card-download-icon", AcmeSimCardDownloadIcon);
