// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/skeleton-icon";
import { AcmeSkeletonIcon } from "../generated/icons/classes/skeleton-icon";

customElements.define("acme-skeleton-icon", AcmeSkeletonIcon);
