// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/skull-icon";
import { AcmeSkullIcon } from "../generated/icons/classes/skull-icon";

customElements.define("acme-skull-icon", AcmeSkullIcon);
