// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/slide-library-icon";
import { AcmeSlideLibraryIcon } from "../generated/icons/classes/slide-library-icon";

customElements.define("acme-slide-library-icon", AcmeSlideLibraryIcon);
