// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/smart-screen-icon";
import { AcmeSmartScreenIcon } from "../generated/icons/classes/smart-screen-icon";

customElements.define("acme-smart-screen-icon", AcmeSmartScreenIcon);
