// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/sms-icon";
import { AcmeSmsIcon } from "../generated/icons/classes/sms-icon";

customElements.define("acme-sms-icon", AcmeSmsIcon);
