// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/snail-icon";
import { AcmeSnailIcon } from "../generated/icons/classes/snail-icon";

customElements.define("acme-snail-icon", AcmeSnailIcon);
