// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/snooze-icon";
import { AcmeSnoozeIcon } from "../generated/icons/classes/snooze-icon";

customElements.define("acme-snooze-icon", AcmeSnoozeIcon);
