// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/snowflake-icon";
import { AcmeSnowflakeIcon } from "../generated/icons/classes/snowflake-icon";

customElements.define("acme-snowflake-icon", AcmeSnowflakeIcon);
