// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/soundbar-icon";
import { AcmeSoundbarIcon } from "../generated/icons/classes/soundbar-icon";

customElements.define("acme-soundbar-icon", AcmeSoundbarIcon);
