// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/speaker-phone-icon";
import { AcmeSpeakerPhoneIcon } from "../generated/icons/classes/speaker-phone-icon";

customElements.define("acme-speaker-phone-icon", AcmeSpeakerPhoneIcon);
