// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/speech-to-text-2-icon";
import { AcmeSpeechToText2Icon } from "../generated/icons/classes/speech-to-text-2-icon";

customElements.define("acme-speech-to-text-2-icon", AcmeSpeechToText2Icon);
