// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/splitscreen-top-icon";
import { AcmeSplitscreenTopIcon } from "../generated/icons/classes/splitscreen-top-icon";

customElements.define("acme-splitscreen-top-icon", AcmeSplitscreenTopIcon);
