// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/splitscreen-vertical-add-icon";
import { AcmeSplitscreenVerticalAddIcon } from "../generated/icons/classes/splitscreen-vertical-add-icon";

customElements.define("acme-splitscreen-vertical-add-icon", AcmeSplitscreenVerticalAddIcon);
