// Generated by scripts/entries.ts. Do not edit.
import "./check-icon";
import "./chevron-right-icon";
import "../components/split-button-item/split-button-item";
import { AcmeSplitButtonItem } from "../components/split-button-item/split-button-item";

customElements.define("acme-split-button-item", AcmeSplitButtonItem);
