// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/sports-bar-icon";
import { AcmeSportsBarIcon } from "../generated/icons/classes/sports-bar-icon";

customElements.define("acme-sports-bar-icon", AcmeSportsBarIcon);
