// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/sports-soccer-icon";
import { AcmeSportsSoccerIcon } from "../generated/icons/classes/sports-soccer-icon";

customElements.define("acme-sports-soccer-icon", AcmeSportsSoccerIcon);
