// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/square-foot-icon";
import { AcmeSquareFootIcon } from "../generated/icons/classes/square-foot-icon";

customElements.define("acme-square-foot-icon", AcmeSquareFootIcon);
