// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/stack-star-icon";
import { AcmeStackStarIcon } from "../generated/icons/classes/stack-star-icon";

customElements.define("acme-stack-star-icon", AcmeStackStarIcon);
