// Generated by scripts/entries.ts. Do not edit.
import "./separator";
import "../components/stack/stack";
import { AcmeStack } from "../components/stack/stack";

customElements.define("acme-stack", AcmeStack);
