// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/stadia-controller-icon";
import { AcmeStadiaControllerIcon } from "../generated/icons/classes/stadia-controller-icon";

customElements.define("acme-stadia-controller-icon", AcmeStadiaControllerIcon);
