// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/stairs-2-icon";
import { AcmeStairs2Icon } from "../generated/icons/classes/stairs-2-icon";

customElements.define("acme-stairs-2-icon", AcmeStairs2Icon);
