// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/star-shine-icon";
import { AcmeStarShineIcon } from "../generated/icons/classes/star-shine-icon";

customElements.define("acme-star-shine-icon", AcmeStarShineIcon);
