// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/step-icon";
import { AcmeStepIcon } from "../generated/icons/classes/step-icon";

customElements.define("acme-step-icon", AcmeStepIcon);
