// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/steps-icon";
import { AcmeStepsIcon } from "../generated/icons/classes/steps-icon";

customElements.define("acme-steps-icon", AcmeStepsIcon);
