// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/stethoscope-icon";
import { AcmeStethoscopeIcon } from "../generated/icons/classes/stethoscope-icon";

customElements.define("acme-stethoscope-icon", AcmeStethoscopeIcon);
