// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/stroke-partial-icon";
import { AcmeStrokePartialIcon } from "../generated/icons/classes/stroke-partial-icon";

customElements.define("acme-stroke-partial-icon", AcmeStrokePartialIcon);
