// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/subtitles-off-icon";
import { AcmeSubtitlesOffIcon } from "../generated/icons/classes/subtitles-off-icon";

customElements.define("acme-subtitles-off-icon", AcmeSubtitlesOffIcon);
