// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/subway-walk-icon";
import { AcmeSubwayWalkIcon } from "../generated/icons/classes/subway-walk-icon";

customElements.define("acme-subway-walk-icon", AcmeSubwayWalkIcon);
