// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/supervisor-account-icon";
import { AcmeSupervisorAccountIcon } from "../generated/icons/classes/supervisor-account-icon";

customElements.define("acme-supervisor-account-icon", AcmeSupervisorAccountIcon);
