// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/support-icon";
import { AcmeSupportIcon } from "../generated/icons/classes/support-icon";

customElements.define("acme-support-icon", AcmeSupportIcon);
