// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/swap-vertical-circle-icon";
import { AcmeSwapVerticalCircleIcon } from "../generated/icons/classes/swap-vertical-circle-icon";

customElements.define("acme-swap-vertical-circle-icon", AcmeSwapVerticalCircleIcon);
