// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/swipe-up-icon";
import { AcmeSwipeUpIcon } from "../generated/icons/classes/swipe-up-icon";

customElements.define("acme-swipe-up-icon", AcmeSwipeUpIcon);
