// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/switches-icon";
import { AcmeSwitchesIcon } from "../generated/icons/classes/switches-icon";

customElements.define("acme-switches-icon", AcmeSwitchesIcon);
