// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/switch-access-2-icon";
import { AcmeSwitchAccess2Icon } from "../generated/icons/classes/switch-access-2-icon";

customElements.define("acme-switch-access-2-icon", AcmeSwitchAccess2Icon);
