// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/switch-camera-icon";
import { AcmeSwitchCameraIcon } from "../generated/icons/classes/switch-camera-icon";

customElements.define("acme-switch-camera-icon", AcmeSwitchCameraIcon);
