// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/switch-off-icon";
import { AcmeSwitchOffIcon } from "../generated/icons/classes/switch-off-icon";

customElements.define("acme-switch-off-icon", AcmeSwitchOffIcon);
