// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/switch-icon";
import { AcmeSwitchIcon } from "../generated/icons/classes/switch-icon";

customElements.define("acme-switch-icon", AcmeSwitchIcon);
