// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/switch-access-icon";
import { AcmeSwitchAccessIcon } from "../generated/icons/classes/switch-access-icon";

customElements.define("acme-switch-access-icon", AcmeSwitchAccessIcon);
