// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/sync-icon";
import { AcmeSyncIcon } from "../generated/icons/classes/sync-icon";

customElements.define("acme-sync-icon", AcmeSyncIcon);
