// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/tab-search-icon";
import { AcmeTabSearchIcon } from "../generated/icons/classes/tab-search-icon";

customElements.define("acme-tab-search-icon", AcmeTabSearchIcon);
