// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/tab-icon";
import { AcmeTabIcon } from "../generated/icons/classes/tab-icon";

customElements.define("acme-tab-icon", AcmeTabIcon);
