// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/table-eye-icon";
import { AcmeTableEyeIcon } from "../generated/icons/classes/table-eye-icon";

customElements.define("acme-table-eye-icon", AcmeTableEyeIcon);
