// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/task-icon";
import { AcmeTaskIcon } from "../generated/icons/classes/task-icon";

customElements.define("acme-task-icon", AcmeTaskIcon);
