// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/temp-preferences-eco-icon";
import { AcmeTempPreferencesEcoIcon } from "../generated/icons/classes/temp-preferences-eco-icon";

customElements.define("acme-temp-preferences-eco-icon", AcmeTempPreferencesEcoIcon);
