// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/temp-preferences-custom-icon";
import { AcmeTempPreferencesCustomIcon } from "../generated/icons/classes/temp-preferences-custom-icon";

customElements.define("acme-temp-preferences-custom-icon", AcmeTempPreferencesCustomIcon);
