// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/text-fields-icon";
import { AcmeTextFieldsIcon } from "../generated/icons/classes/text-fields-icon";

customElements.define("acme-text-fields-icon", AcmeTextFieldsIcon);
