// Generated by scripts/entries.ts. Do not edit.
import "../components/textarea/textarea";
import { AcmeTextarea } from "../components/textarea/textarea";

customElements.define("acme-textarea", AcmeTextarea);
