// Generated by scripts/entries.ts. Do not edit.
import "../components/theme-switcher/theme-switcher";
import { AcmeThemeSwitcher } from "../components/theme-switcher/theme-switcher";

customElements.define("acme-theme-switcher", AcmeThemeSwitcher);
