// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/thermostat-icon";
import { AcmeThermostatIcon } from "../generated/icons/classes/thermostat-icon";

customElements.define("acme-thermostat-icon", AcmeThermostatIcon);
