// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/thermostat-carbon-icon";
import { AcmeThermostatCarbonIcon } from "../generated/icons/classes/thermostat-carbon-icon";

customElements.define("acme-thermostat-carbon-icon", AcmeThermostatCarbonIcon);
