// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/thermometer-gain-icon";
import { AcmeThermometerGainIcon } from "../generated/icons/classes/thermometer-gain-icon";

customElements.define("acme-thermometer-gain-icon", AcmeThermometerGainIcon);
