// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/things-to-do-icon";
import { AcmeThingsToDoIcon } from "../generated/icons/classes/things-to-do-icon";

customElements.define("acme-things-to-do-icon", AcmeThingsToDoIcon);
