// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/thread-unread-icon";
import { AcmeThreadUnreadIcon } from "../generated/icons/classes/thread-unread-icon";

customElements.define("acme-thread-unread-icon", AcmeThreadUnreadIcon);
