// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/thumbs-up-double-icon";
import { AcmeThumbsUpDoubleIcon } from "../generated/icons/classes/thumbs-up-double-icon";

customElements.define("acme-thumbs-up-double-icon", AcmeThumbsUpDoubleIcon);
