// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/tilt-arrow-down-icon";
import { AcmeTiltArrowDownIcon } from "../generated/icons/classes/tilt-arrow-down-icon";

customElements.define("acme-tilt-arrow-down-icon", AcmeTiltArrowDownIcon);
