// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/timer-10-select-icon";
import { AcmeTimer10SelectIcon } from "../generated/icons/classes/timer-10-select-icon";

customElements.define("acme-timer-10-select-icon", AcmeTimer10SelectIcon);
