// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/timer-3-select-icon";
import { AcmeTimer3SelectIcon } from "../generated/icons/classes/timer-3-select-icon";

customElements.define("acme-timer-3-select-icon", AcmeTimer3SelectIcon);
