// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/time-auto-icon";
import { AcmeTimeAutoIcon } from "../generated/icons/classes/time-auto-icon";

customElements.define("acme-time-auto-icon", AcmeTimeAutoIcon);
