// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/timer-arrow-down-icon";
import { AcmeTimerArrowDownIcon } from "../generated/icons/classes/timer-arrow-down-icon";

customElements.define("acme-timer-arrow-down-icon", AcmeTimerArrowDownIcon);
