// Generated by scripts/entries.ts. Do not edit.
import "../components/timeline-item/timeline-item";
import { AcmeTimelineItem } from "../components/timeline-item/timeline-item";

customElements.define("acme-timeline-item", AcmeTimelineItem);
