// Generated by scripts/entries.ts. Do not edit.
import "./close-icon";
import "./undo-icon";
import "../components/toast/toast";
import { AcmeToast } from "../components/toast/toast";

customElements.define("acme-toast", AcmeToast);
