// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/toast-icon";
import { AcmeToastIcon } from "../generated/icons/classes/toast-icon";

customElements.define("acme-toast-icon", AcmeToastIcon);
