// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/tooltip-2-icon";
import { AcmeTooltip2Icon } from "../generated/icons/classes/tooltip-2-icon";

customElements.define("acme-tooltip-2-icon", AcmeTooltip2Icon);
