// Generated by scripts/entries.ts. Do not edit.
import "../components/toolbar/toolbar";
import { AcmeToolbar } from "../components/toolbar/toolbar";

customElements.define("acme-toolbar", AcmeToolbar);
