// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/touch-double-icon";
import { AcmeTouchDoubleIcon } from "../generated/icons/classes/touch-double-icon";

customElements.define("acme-touch-double-icon", AcmeTouchDoubleIcon);
