// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/touch-app-icon";
import { AcmeTouchAppIcon } from "../generated/icons/classes/touch-app-icon";

customElements.define("acme-touch-app-icon", AcmeTouchAppIcon);
