// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/trail-length-icon";
import { AcmeTrailLengthIcon } from "../generated/icons/classes/trail-length-icon";

customElements.define("acme-trail-length-icon", AcmeTrailLengthIcon);
