// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/transition-chop-icon";
import { AcmeTransitionChopIcon } from "../generated/icons/classes/transition-chop-icon";

customElements.define("acme-transition-chop-icon", AcmeTransitionChopIcon);
