// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/transition-dissolve-icon";
import { AcmeTransitionDissolveIcon } from "../generated/icons/classes/transition-dissolve-icon";

customElements.define("acme-transition-dissolve-icon", AcmeTransitionDissolveIcon);
