// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/transcribe-icon";
import { AcmeTranscribeIcon } from "../generated/icons/classes/transcribe-icon";

customElements.define("acme-transcribe-icon", AcmeTranscribeIcon);
