// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/turn-right-icon";
import { AcmeTurnRightIcon } from "../generated/icons/classes/turn-right-icon";

customElements.define("acme-turn-right-icon", AcmeTurnRightIcon);
