// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/turn-slight-left-icon";
import { AcmeTurnSlightLeftIcon } from "../generated/icons/classes/turn-slight-left-icon";

customElements.define("acme-turn-slight-left-icon", AcmeTurnSlightLeftIcon);
