// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/u-turn-right-icon";
import { AcmeUTurnRightIcon } from "../generated/icons/classes/u-turn-right-icon";

customElements.define("acme-u-turn-right-icon", AcmeUTurnRightIcon);
