// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/umbrella-icon";
import { AcmeUmbrellaIcon } from "../generated/icons/classes/umbrella-icon";

customElements.define("acme-umbrella-icon", AcmeUmbrellaIcon);
