// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/ungroup-icon";
import { AcmeUngroupIcon } from "../generated/icons/classes/ungroup-icon";

customElements.define("acme-ungroup-icon", AcmeUngroupIcon);
