// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/upload-icon";
import { AcmeUploadIcon } from "../generated/icons/classes/upload-icon";

customElements.define("acme-upload-icon", AcmeUploadIcon);
