// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/vacuum-2-icon";
import { AcmeVacuum2Icon } from "../generated/icons/classes/vacuum-2-icon";

customElements.define("acme-vacuum-2-icon", AcmeVacuum2Icon);
