// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/variable-remove-icon";
import { AcmeVariableRemoveIcon } from "../generated/icons/classes/variable-remove-icon";

customElements.define("acme-variable-remove-icon", AcmeVariableRemoveIcon);
