// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/ventilator-icon";
import { AcmeVentilatorIcon } from "../generated/icons/classes/ventilator-icon";

customElements.define("acme-ventilator-icon", AcmeVentilatorIcon);
