// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/vertical-split-icon";
import { AcmeVerticalSplitIcon } from "../generated/icons/classes/vertical-split-icon";

customElements.define("acme-vertical-split-icon", AcmeVerticalSplitIcon);
