// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/video-label-icon";
import { AcmeVideoLabelIcon } from "../generated/icons/classes/video-label-icon";

customElements.define("acme-video-label-icon", AcmeVideoLabelIcon);
