// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/video-chat-icon";
import { AcmeVideoChatIcon } from "../generated/icons/classes/video-chat-icon";

customElements.define("acme-video-chat-icon", AcmeVideoChatIcon);
