// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/video-camera-back-add-icon";
import { AcmeVideoCameraBackAddIcon } from "../generated/icons/classes/video-camera-back-add-icon";

customElements.define("acme-video-camera-back-add-icon", AcmeVideoCameraBackAddIcon);
