// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/view-week-icon";
import { AcmeViewWeekIcon } from "../generated/icons/classes/view-week-icon";

customElements.define("acme-view-week-icon", AcmeViewWeekIcon);
