// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/view-headline-icon";
import { AcmeViewHeadlineIcon } from "../generated/icons/classes/view-headline-icon";

customElements.define("acme-view-headline-icon", AcmeViewHeadlineIcon);
