// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/view-column-2-icon";
import { AcmeViewColumn2Icon } from "../generated/icons/classes/view-column-2-icon";

customElements.define("acme-view-column-2-icon", AcmeViewColumn2Icon);
