// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/view-apps-icon";
import { AcmeViewAppsIcon } from "../generated/icons/classes/view-apps-icon";

customElements.define("acme-view-apps-icon", AcmeViewAppsIcon);
