// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/vital-signs-icon";
import { AcmeVitalSignsIcon } from "../generated/icons/classes/vital-signs-icon";

customElements.define("acme-vital-signs-icon", AcmeVitalSignsIcon);
