// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/voice-selection-off-icon";
import { AcmeVoiceSelectionOffIcon } from "../generated/icons/classes/voice-selection-off-icon";

customElements.define("acme-voice-selection-off-icon", AcmeVoiceSelectionOffIcon);
