// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/voice-over-off-icon";
import { AcmeVoiceOverOffIcon } from "../generated/icons/classes/voice-over-off-icon";

customElements.define("acme-voice-over-off-icon", AcmeVoiceOverOffIcon);
