// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/voicemail-2-icon";
import { AcmeVoicemail2Icon } from "../generated/icons/classes/voicemail-2-icon";

customElements.define("acme-voicemail-2-icon", AcmeVoicemail2Icon);
