// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/volume-up-icon";
import { AcmeVolumeUpIcon } from "../generated/icons/classes/volume-up-icon";

customElements.define("acme-volume-up-icon", AcmeVolumeUpIcon);
