// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/vpn-key-icon";
import { AcmeVpnKeyIcon } from "../generated/icons/classes/vpn-key-icon";

customElements.define("acme-vpn-key-icon", AcmeVpnKeyIcon);
