// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/vr180-create2d-off-icon";
import { AcmeVr180Create2dOffIcon } from "../generated/icons/classes/vr180-create2d-off-icon";

customElements.define("acme-vr180-create2d-off-icon", AcmeVr180Create2dOffIcon);
