// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/watch-wake-icon";
import { AcmeWatchWakeIcon } from "../generated/icons/classes/watch-wake-icon";

customElements.define("acme-watch-wake-icon", AcmeWatchWakeIcon);
