// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/water-ec-icon";
import { AcmeWaterEcIcon } from "../generated/icons/classes/water-ec-icon";

customElements.define("acme-water-ec-icon", AcmeWaterEcIcon);
