// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/waterfall-chart-icon";
import { AcmeWaterfallChartIcon } from "../generated/icons/classes/waterfall-chart-icon";

customElements.define("acme-waterfall-chart-icon", AcmeWaterfallChartIcon);
