// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/water-heater-icon";
import { AcmeWaterHeaterIcon } from "../generated/icons/classes/water-heater-icon";

customElements.define("acme-water-heater-icon", AcmeWaterHeaterIcon);
