// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/weather-hail-icon";
import { AcmeWeatherHailIcon } from "../generated/icons/classes/weather-hail-icon";

customElements.define("acme-weather-hail-icon", AcmeWeatherHailIcon);
