// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/widgets-icon";
import { AcmeWidgetsIcon } from "../generated/icons/classes/widgets-icon";

customElements.define("acme-widgets-icon", AcmeWidgetsIcon);
