// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/width-wide-icon";
import { AcmeWidthWideIcon } from "../generated/icons/classes/width-wide-icon";

customElements.define("acme-width-wide-icon", AcmeWidthWideIcon);
