// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/width-normal-icon";
import { AcmeWidthNormalIcon } from "../generated/icons/classes/width-normal-icon";

customElements.define("acme-width-normal-icon", AcmeWidthNormalIcon);
