// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/wifi-find-icon";
import { AcmeWifiFindIcon } from "../generated/icons/classes/wifi-find-icon";

customElements.define("acme-wifi-find-icon", AcmeWifiFindIcon);
