// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/wifi-proxy-icon";
import { AcmeWifiProxyIcon } from "../generated/icons/classes/wifi-proxy-icon";

customElements.define("acme-wifi-proxy-icon", AcmeWifiProxyIcon);
