// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/woman-icon";
import { AcmeWomanIcon } from "../generated/icons/classes/woman-icon";

customElements.define("acme-woman-icon", AcmeWomanIcon);
