// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/workspace-premium-icon";
import { AcmeWorkspacePremiumIcon } from "../generated/icons/classes/workspace-premium-icon";

customElements.define("acme-workspace-premium-icon", AcmeWorkspacePremiumIcon);
