// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/yakitori-icon";
import { AcmeYakitoriIcon } from "../generated/icons/classes/yakitori-icon";

customElements.define("acme-yakitori-icon", AcmeYakitoriIcon);
