// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/youtube-searched-for-icon";
import { AcmeYoutubeSearchedForIcon } from "../generated/icons/classes/youtube-searched-for-icon";

customElements.define("acme-youtube-searched-for-icon", AcmeYoutubeSearchedForIcon);
