// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/youtube-activity-icon";
import { AcmeYoutubeActivityIcon } from "../generated/icons/classes/youtube-activity-icon";

customElements.define("acme-youtube-activity-icon", AcmeYoutubeActivityIcon);
