// Generated by scripts/entries.ts. Do not edit.
import "../generated/icons/classes/zoom-in-map-icon";
import { AcmeZoomInMapIcon } from "../generated/icons/classes/zoom-in-map-icon";

customElements.define("acme-zoom-in-map-icon", AcmeZoomInMapIcon);
