// Generated by scripts/split-css.ts from the audited house sheet. Do not edit.
import { css } from "lit";
export const tableCss = css`
.table-wrap{overflow-x:auto;-webkit-overflow-scrolling:touch}
table.table{width:100%;border-collapse:collapse;font-size:14px;line-height:20px}
.table th{text-align:left;height:36px;padding:0 8px;font-size:14px;line-height:20px;font-weight:500;color:var(--text-2);border-bottom:1px solid var(--border);white-space:nowrap}
.table td:first-child{border-radius:var(--r-sm) 0 0 var(--r-sm)}
.table td:last-child{border-radius:0 var(--r-sm) var(--r-sm) 0}
.table.flush th:first-child,.table.flush td:first-child{padding-left:0}
.table.flush th:last-child,.table.flush td:last-child{padding-right:0}
.table th[aria-sort]{cursor:pointer}
.table th[aria-sort]:hover{color:var(--text)}
.table th[aria-sort="ascending"]::after{content:" ↑";color:var(--text-2)}
.table th[aria-sort="descending"]::after{content:" ↓";color:var(--text-2)}
.table td{padding:10px 8px;height:40px;color:var(--text-2);vertical-align:top}
.table td b,.table td strong,.table td .title{color:var(--text)}
.table.lined td{border-bottom:1px solid var(--hair)}
.table.lined tr:last-child td{border-bottom:none}
.table.interactive tbody tr:hover td{background:var(--comp);cursor:pointer}
.table.striped tbody tr:nth-child(even) td{background:var(--surface-2)}
.table.striped tbody tr:nth-child(even) td:first-child{border-radius:var(--r-sm) 0 0 var(--r-sm)}
.table.bordered td{border-bottom:1px solid var(--border)}
.table.bordered tr:last-child td{border-bottom:none}
.table.framed{box-shadow:0 0 0 1px var(--border);border-radius:var(--r-sm);overflow:hidden}
.table.framed th,.table.framed td{padding-left:12px;padding-right:12px}
.table td.n,.table th.n{text-align:right;font-family:var(--mono);font-variant-numeric:tabular-nums}
.table td .sub{display:block;font-size:var(--t-xs);line-height:16px;color:var(--text-2);margin-top:1px}
.table td.secondary{color:var(--text-2)}
.table .empty td{color:var(--text-2);text-align:center;padding:28px 0}
.table tfoot td{font-weight:500;color:var(--text);border-top:1px solid var(--border);border-bottom:none}
@media (max-width:560px){
  .table.stack thead{display:none}
  .table.stack,.table.stack tbody{display:block}
  .table.stack tr{display:flex;flex-wrap:wrap;align-items:baseline;gap:4px 10px;padding:10px 0;border-bottom:1px solid var(--hair)}
  .table.stack tr:last-child{border-bottom:none}
  .table.stack td{display:block;padding:0;border:0;min-height:0}
  .table.stack td:first-child{flex:1 1 100%}
  .table.stack td.n{margin-left:auto}
  .table.stack .hide-sm{display:none}
  .table.stack .empty td{flex:1 1 100%;padding:20px 0}
}
.table td[class*="hue-"]{font-family:var(--mono);font-variant-numeric:tabular-nums}
.cellbar{position:relative;display:inline-block;min-width:56px;height:24px;line-height:24px;padding:0 6px;border-radius:4px;font-variant-numeric:tabular-nums;z-index:0}
.cellbar::before{content:"";position:absolute;inset:0;width:var(--pct,0%);background:var(--ds-gray-100);border-radius:4px;z-index:-1}
.cellspark{display:inline-block;vertical-align:middle;margin-left:6px}
.cellspark svg{width:40px;height:16px;display:block;overflow:visible}
.cellspark path{fill:none;stroke:var(--ds-gray-500);stroke-width:1.25;stroke-linejoin:round}
.cellspark.bad path{stroke:var(--warn)}
.table td.chev{width:24px;text-align:right;color:var(--text-2)}
.table td .favicon{display:inline-grid;place-items:center;width:20px;height:20px;border-radius:4px;background:var(--text);color:var(--on-contrast);margin-right:8px;vertical-align:middle;font-size:10px}
.table-foot{display:flex;align-items:center;gap:12px;padding:8px 0 0;border-top:1px solid var(--hair);margin-top:4px;font-size:var(--t-sm);color:var(--text-2)}
.table-foot .pager{margin-left:auto;display:inline-flex;align-items:center;gap:8px}
.table-foot .pager .iconbtn{width:24px;height:24px;border-radius:4px}
.table-foot .pager .iconbtn[disabled]{background:var(--ds-gray-100);border-color:transparent}
.table-foot .count{font-size:var(--t-xs);color:var(--text-2)}
.table.geist th{height:42px;color:var(--text-2);font-weight:500;font-size:14px;line-height:24px}
.table.geist th .sort{display:inline-grid;place-items:center;width:16px;height:16px;border-radius:50%;background:var(--comp);margin-left:6px;vertical-align:middle}
.table.geist td{height:43px;padding:9px 8px;vertical-align:middle;line-height:24px}
.table.geist{box-shadow:0 0 0 1px var(--border);border-radius:var(--r-sm);overflow:hidden}
.table.geist th:first-child,.table.geist td:first-child{padding-left:16px}
.table.geist th:last-child,.table.geist td:last-child{padding-right:16px}
.matrix td.c,.matrix th.c{text-align:center;width:110px}
.matrix .group td{background:var(--surface-2);font-weight:500}
.matrix .group .lead-chev{width:14px;height:14px;vertical-align:middle;margin-right:8px;color:var(--text-2);transform:rotate(90deg)}
.matrix td a{color:var(--text);text-decoration:underline;text-underline-offset:2px}
`;
