// Generated by the style generator from the reference spec. Do not edit; edit the mapping and regenerate.
import { css } from "lit";
export const breadcrumbsCss = css`
  .list {
    display: flex;
  }
  .list:where(:not(.menu)) {
    list-style-type: none;
    gap: 0.375rem;
    padding: 0;
  }
  .list:where(.menu) {
    gap: 0.5rem;
  }
  @media not all and (min-width: 401px) {
    .list:where(.menu) {
      overflow-x: auto;
    }
  }
`;
