// Generated by the style generator from the reference spec. Do not edit; edit the mapping and regenerate.
import { css } from "lit";
import { registerProperties } from "../../base";

registerProperties([
  { name: "--acme-translate-x", syntax: "*", inherits: false, initialValue: "0" },
  { name: "--acme-translate-y", syntax: "*", inherits: false, initialValue: "0" },
  { name: "--acme-translate-z", syntax: "*", inherits: false, initialValue: "0" },
  { name: "--acme-scale-x", syntax: "*", inherits: false, initialValue: "1" },
  { name: "--acme-scale-y", syntax: "*", inherits: false, initialValue: "1" },
  { name: "--acme-scale-z", syntax: "*", inherits: false, initialValue: "1" },
  { name: "--acme-rotate-x", syntax: "*", inherits: false },
  { name: "--acme-rotate-y", syntax: "*", inherits: false },
  { name: "--acme-rotate-z", syntax: "*", inherits: false },
  { name: "--acme-skew-x", syntax: "*", inherits: false },
  { name: "--acme-skew-y", syntax: "*", inherits: false },
]);
export const toggleCss = css`
  .toggle :where(input) {
    clip-path: inset(50%);
    white-space: nowrap;
    border-width: 0;
    width: 1px;
    height: 1px;
    margin: -1px;
    padding: 0;
    position: absolute;
    overflow: hidden;
  }
  .toggle {
    position: relative;
    display: inline-flex;
    touch-action: manipulation;
    align-items: center;
    gap: var(--acme-space-gap-half);
    padding-block: 3px;
    font-size: 0.75rem;
    font-weight: 500;
    white-space: nowrap;
    color: var(--acme-secondary);
    -webkit-user-select: none;
    user-select: none;
  }
  .toggle :where(.track) {
    position: relative;
    display: inline-block;
    border-radius: 14px;
    border-style: solid;
    border-width: 0;
    transition-property: background, border-color;
    transition-timing-function: cubic-bezier(0, 0, 0.2, 1);
    transition-duration: 0.15s;
    animation-duration: 0.15s;
    animation-timing-function: cubic-bezier(0, 0, 0.2, 1);
  }
  .toggle:where(.no-margin) :where(.track) {
    margin: 0;
  }
  .toggle :where(.track) :where(.thumb) :where(.icon) {
    display: flex;
    height: 100%;
    width: 100%;
    align-items: center;
    justify-content: center;
  }
  .toggle:where(:not(.md, .lg)) :where(.track) :where(.thumb) {
    height: 11px;
    width: 11px;
  }
  .toggle:where(:not(.md, .lg)) :where(.track) {
    height: 14px;
    width: 28px;
  }
  .toggle:where(.md) :where(.track) :where(.thumb) {
    height: 17px;
    width: 17px;
  }
  .toggle:where(.md) :where(.track) {
    height: 20px;
    width: 36px;
  }
  .toggle:where(.lg) :where(.track) :where(.thumb) {
    height: 21px;
    width: 21px;
  }
  .toggle:where(.lg) :where(.track) {
    height: 24px;
    width: 40px;
  }
  .toggle:where(:not([data-checked])) :where(.track) :where(.thumb) {
    --acme-translate-x: 0rem;
    translate: var(--acme-translate-x) var(--acme-translate-y);
  }
  .toggle:where(:not(.md, .lg)[data-checked]) :where(.track) :where(.thumb) {
    --acme-translate-x: 14px;
    translate: var(--acme-translate-x) var(--acme-translate-y);
  }
  .toggle:where(:is(.md, .lg)[data-checked]) :where(.track) :where(.thumb) {
    --acme-translate-x: 16px;
    translate: var(--acme-translate-x) var(--acme-translate-y);
  }
  .toggle :where(.track) :where(.thumb) {
    position: absolute;
    top: 50%;
    left: 1.5px;
    --acme-translate-y: -50%;
    translate: var(--acme-translate-x) var(--acme-translate-y);
    border-radius: 50%;
    border-style: solid;
    border-width: 0;
    transition-property: transform, translate, scale, rotate;
    transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1);
    transition-duration: 0.15s;
    animation-duration: 0.15s;
    animation-timing-function: cubic-bezier(0.4, 0, 0.2, 1);
  }
  .toggle:where([data-disabled]) :where(.track) {
    cursor: not-allowed;
  }
  .toggle:where([data-disabled]) :where(.track) :where(.thumb) {
    cursor: not-allowed;
    border-color: #0000;
    box-shadow: none;
  }
  .toggle:where(:not([data-disabled])) :where(.track) {
    cursor: pointer;
    border-color: var(--ds-gray-alpha-300);
  }
  .toggle:where(:not([data-disabled])) :where(.track) :where(.thumb) {
    cursor: pointer;
    box-shadow:
      0 0 3px -1px #0000003d,
      0 0 0.5px #00000029,
      -0.5px 2px 3px -2px #0000005c;
  }
  .toggle:where(.switch-first) {
    flex-direction: row-reverse;
  }
  .toggle:where(:not([data-checked])[data-disabled]) :where(.track) {
    border-color: var(--ds-gray-200);
    background-color: var(--ds-gray-200);
  }
  .toggle:where([data-checked][data-disabled]) :where(.track) {
    border-color: var(--ds-gray-500);
    background-color: var(--ds-gray-500);
  }
  .toggle:where([data-checked]:not([data-disabled])) :where(.track) :where(.thumb) {
    background-color: var(--ds-background-100) !important;
  }
  .toggle:where([data-checked]:not([data-disabled])) :where(.track) {
    background-color: var(--checked-bg-color-override, var(--acme-success));
  }
  .toggle:where([data-checked][data-disabled]) :where(.track) :where(.thumb) {
    background-color: var(--ds-gray-100);
  }
  .toggle:where(:not([data-checked]):not([data-disabled])) :where(.track) :where(.thumb) {
    background-color: var(--thumb-unchecked-bg-color-override, var(--ds-background-100));
  }
  .toggle:where(:not([data-checked])[data-disabled]) :where(.track) :where(.thumb) {
    background-color: var(--thumb-unchecked-bg-color-override, var(--ds-background-200));
  }
  .toggle:where(:not([data-checked]):not([data-disabled])) :where(.track) {
    background-color: var(--unchecked-bg-color-override, var(--ds-gray-400));
  }
  .toggle:where([data-checked]) :where(.track) {
    background-clip: border-box;
  }
  .toggle:where(:not([data-checked]).colored) :where(.track) {
    background-clip: border-box;
  }
  .toggle:where(:not([data-checked]):not(.colored)) :where(.track) {
    background-clip: padding-box;
  }
  .toggle:where([data-disabled]) :where(.track) :where(.thumb) :where(.icon) {
    color: var(--ds-gray-700);
  }
  .toggle:where(:not([data-disabled])) :where(.track) :where(.thumb) :where(.icon) {
    color: var(--thumb-light-fg-color-override, var(--ds-gray-900));
  }
  .toggle:where(:not(.normal)) {
    text-transform: capitalize;
  }
  .toggle[data-focus] :where(.track) {
    box-shadow: 0 0 0 calc(1px + 0px) var(--ds-focus-ring);
  }
  :where(:host([data-dark])) .toggle :where(.track) :where(.thumb) {
    border-style: solid;
    border-width: 1px;
  }
  :where(:host([data-dark])) .toggle:where([data-checked][data-disabled]) :where(.track) {
    border-color: var(--ds-gray-alpha-100);
    background-color: var(--ds-gray-400);
  }
  :where(:host([data-dark])) .toggle:where(:not([data-disabled])) :where(.track) :where(.thumb) {
    border-color: var(--ds-gray-alpha-600);
  }
  :where(:host([data-dark])) .toggle:where([data-disabled]) :where(.track) :where(.thumb) {
    border-color: #0000;
  }
  :where(:host([data-dark])) .toggle:where([data-checked]:not([data-disabled])) :where(.track) :where(.thumb) {
    background-color: hsla(var(--ds-gray-1000-value), 0.84) !important;
  }
  :where(:host([data-dark])) .toggle:where(:not([data-checked])[data-disabled]) :where(.track) :where(.thumb) {
    background-color: var(--ds-gray-500);
  }
  :where(:host([data-dark])) .toggle:where([data-checked][data-disabled]) :where(.track) :where(.thumb) {
    background-color: var(--ds-gray-600);
  }
  :where(:host([data-dark])) .toggle:where(:not([data-checked]):not([data-disabled])) :where(.track) :where(.thumb) {
    background-color: var(--thumb-unchecked-bg-color-override, hsla(var(--ds-gray-1000-value), 0.84));
  }
  :where(:host([data-dark])) .toggle:where([data-checked]:not(.colored)) :where(.track) :where(.thumb) :where(.icon) {
    color: var(--ds-gray-700);
  }
  :where(:host([data-dark])) .toggle:where(:not([data-checked])[data-disabled]) :where(.track) :where(.thumb) :where(.icon) {
    color: var(--ds-gray-900);
  }
  :where(:host([data-dark])) .toggle:where(:not([data-disabled])) :where(.track) :where(.thumb) :where(.icon) {
    color: var(--thumb-fg-color-override, var(--ds-background-100));
  }
`;
