import { expect, test } from "bun:test";
import "../../../all";
test("Switch has canonical checked/reset state and an independent submission value", async () => {
  const control = document.createElement("acme-switch");
  control.textContent = "Updates";
  document.body.append(control);
  await control.updateComplete;
  expect(control.size).toBe("small");
  expect(control.labelPosition).toBe("start");
  expect(control.checked).toBe(false);
  const seen: unknown[] = [];
  control.addEventListener("acme-change", (e) => seen.push((e as CustomEvent).detail));
  control.click();
  expect(control.checked).toBe(true);
  expect(seen).toEqual([{ checked: true }]);
  control.value = "yes";
  expect(control.checked).toBe(true);
  control.defaultChecked = true;
  control.checked = false;
  control.formResetCallback();
  expect(control.checked).toBe(true);
  expect(seen).toHaveLength(1);
  control.remove();
});
