// Generated by the style generator from the reference spec. Do not edit; edit the mapping and regenerate.
import { css } from "lit";
export const codeBlockCss = css`
  .code-block :where(acme-copy-button.floating)::part(button) {
    position: absolute;
    top: min(16%, 16px);
    right: 1rem;
    z-index: 1;
    width: 2rem;
    height: 2rem;
    background-color: var(--ds-background-200);
    opacity: 0;
  }
  .code-block {
    position: relative;
    margin-block: 1rem;
    overflow: hidden;
    border-radius: 0.5rem;
  }
  .code-block :where(.bar) :where(.name) {
    margin: 0;
    margin-right: auto;
    display: flex;
    min-width: 0;
    align-items: center;
    gap: 0.5rem;
    font-family: var(--acme-font-sans);
    font-size: 13px;
    line-height: 16px;
    font-weight: 400;
    color: var(--ds-gray-900);
  }
  .code-block :where(.strip) :where(acme-switch) {
    margin-bottom: 0.75rem;
    scrollbar-width: none;
    -webkit-overflow-scrolling: touch;
    flex-wrap: nowrap;
    align-items: center;
    overflow-x: auto;
    padding-bottom: 1px;
    box-shadow: none !important;
  }
  .code-block :where(.strip) {
    display: flex;
    align-items: center;
    justify-content: space-between;
    overflow-x: auto;
    border-bottom-style: solid;
    border-bottom-width: 0;
    border-color: var(--ds-gray-400);
    padding-bottom: 0;
  }
  .code-block :where(.bar) {
    display: flex;
    height: var(--ds-size-large);
    align-items: center;
    border-top-left-radius: 0.5rem;
    border-top-right-radius: 0.5rem;
    border-style: solid;
    border-width: 1px;
    border-color: var(--ds-gray-400);
    background-color: var(--ds-background-200);
    padding-block: 0;
    padding-right: 5px;
    padding-left: 1rem;
  }
  .code-block :where(.bar) :where(.name) :where(.file-icon) {
    display: flex;
    width: 1rem;
    flex-shrink: 0;
    align-items: center;
  }
  .code-block :where(.bar) :where(.actions) {
    display: flex;
    gap: 0.25rem;
  }
  .code-block :where(.foot) {
    display: flex;
    height: var(--ds-size-large);
    align-items: center;
    justify-content: flex-end;
    border-bottom-right-radius: 0.5rem;
    border-bottom-left-radius: 0.5rem;
    border-style: solid;
    border-width: 1px;
    border-color: var(--ds-gray-400);
    background-color: var(--ds-background-200);
    padding: 0.75rem;
  }
  .code-block :where(.content) :where(.pre) :where(.body) {
    display: grid;
    text-align: left;
    font-family: var(--font-mono);
    font-size: 13px !important;
    line-height: 20px;
    overflow-wrap: normal;
    word-break: normal;
    -webkit-hyphens: none;
    hyphens: none;
    white-space: pre;
    color: var(--ds-gray-1000);
  }
  .code-block :where(.bar) :where(.name) :where(.filename) {
    display: inline-block;
    max-width: 100%;
    min-width: 0;
    text-overflow: ellipsis;
    white-space: nowrap;
    overflow: hidden;
    overflow-wrap: normal;
    word-break: normal;
  }
  .code-block :where(.bar) :where(.actions) :where(acme-copy-button)::part(label) {
    display: inline-flex;
    flex-shrink: 0;
    align-items: center;
    justify-content: center;
    text-overflow: ellipsis;
    white-space: nowrap;
    overflow: hidden;
    padding-inline: 0.375rem;
  }
  .code-block :where(acme-copy-button.floating)::part(label) {
    display: inline-flex;
    flex-shrink: 0;
    align-items: center;
    justify-content: center;
    text-overflow: ellipsis;
    white-space: nowrap;
    overflow: hidden;
    padding-inline: 0.375rem;
  }
  .code-block :where(.bar) :where(.actions) :where(acme-copy-button)::part(button) {
    width: 1.75rem;
    height: 1.75rem;
    color: var(--ds-gray-900) !important;
  }
  .code-block :where(.bar) :where(.actions) :where(acme-select.switcher) {
    height: 2rem;
  }
  .code-block:where(:not(.with-bar)) :where(.content) {
    border-top-left-radius: 0.5rem;
    border-top-right-radius: 0.5rem;
    border-top-style: solid;
    border-top-width: 1px;
  }
  .code-block:where(.with-bar) {
    border-bottom-right-radius: 0.5rem;
    border-bottom-left-radius: 0.5rem;
  }
  .code-block:where(:not(.ask, .build)) :where(.content) {
    border-bottom-right-radius: 0.5rem;
    border-bottom-left-radius: 0.5rem;
    border-bottom-style: solid;
    border-bottom-width: 1px;
  }
  .code-block :where(.content) {
    border-inline-style: solid;
    border-inline-width: 1px;
    border-color: var(--ds-gray-400);
  }
  .code-block :where(.strip) :where(acme-switch)::-webkit-scrollbar {
    display: none;
  }
  .code-block :where(.bar) :where(.name) > strong {
    font-weight: 500;
    color: var(--ds-gray-1000);
  }
  .code-block :where(.bar) :where(.actions) :where(acme-copy-button) svg {
    flex-shrink: 0;
  }
  .code-block :where(acme-copy-button.floating) svg {
    flex-shrink: 0;
    color: var(--ds-gray-900) !important;
  }
  .code-block :where(.foot) :where(acme-button) svg {
    flex-shrink: 0;
  }
  .code-block:where(:not(.with-bar)) :where(.content) > pre {
    border-top-left-radius: 0.5rem;
    border-top-right-radius: 0.5rem;
  }
  .code-block:where(:not(.ask, .build)) :where(.content) > pre {
    border-bottom-right-radius: 0.5rem;
    border-bottom-left-radius: 0.5rem;
  }
  @media (hover: hover) {
    .code-block[data-hover] :where(acme-copy-button.floating)::part(button) {
      opacity: 1;
    }
  }
  .code-block :where(acme-copy-button.floating)::part(button):focus {
    opacity: 1;
  }
  .code-block :where(acme-copy-button.floating)::part(button):disabled {
    background-color: var(--ds-gray-100);
  }
  .code-block :where(.strip) :where(acme-switch):has(:focus-visible) {
    overflow: visible;
  }
  .code-block :where(acme-copy-button.floating)[aria-disabled="true"]::part(button) {
    background-color: var(--ds-gray-100);
  }
  .code-block :where(acme-copy-button.floating)[data-hover]::part(button) {
    background-color: var(--ds-gray-100);
  }
  :where(:host([data-dark])) .code-block :where(acme-copy-button.floating)[data-hover]::part(button) {
    background-color: var(--ds-gray-200);
  }
  .code-block :where(acme-copy-button.floating)[data-hover]::part(button):disabled {
    background-color: var(--ds-gray-100);
  }
  .code-block :where(.content) :where(.pre) {
    --padding: 16px;
    padding: var(--padding) 0;
    scrollbar-width: thin;
    scrollbar-color: var(--ds-gray-600) transparent;
    background: var(--ds-background-100);
    counter-reset: line;
    --shiki-color-text: var(--ds-gray-1000);
    --shiki-color-background: transparent;
    --shiki-token-constant: var(--ds-blue-900);
    --shiki-token-string: var(--ds-green-900);
    --shiki-token-comment: var(--ds-gray-900);
    --shiki-token-keyword: var(--ds-pink-900);
    --shiki-token-parameter: var(--ds-amber-900);
    --shiki-token-function: var(--ds-purple-900);
    --shiki-token-string-expression: var(--ds-green-900);
    --shiki-token-punctuation: var(--ds-gray-1000);
    --shiki-token-link: var(--ds-green-900);
    margin: 0;
    overflow-x: auto;
  }
  .code-block :where(.content) :where(.pre) .token {
    display: inline;
    position: relative;
  }
  .code-block :where(.content) :where(.pre) .ln {
    all: unset;
    width: 16px;
    color: var(--ds-gray-600);
    font-size: 13px;
    font-family: var(--font-mono);
    text-align: right;
    padding-right: var(--padding);
    cursor: pointer;
    -webkit-user-select: none;
    user-select: none;
    flex-shrink: 0;
    transition: color 0.125s ease-out;
  }
  .code-block :where(.content) :where(.pre) [data-added="true"] {
    background: var(--ds-green-300);
    box-shadow: inset 2px 0 0 0 var(--ds-green-900);
  }
  .code-block :where(.content) :where(.pre) [data-removed="true"] {
    background: var(--ds-red-300);
    box-shadow: inset 2px 0 0 0 var(--ds-red-900);
  }
  @media (max-width: 600px) {
    .code-block :where(.content) :where(.pre) .ln {
      display: none;
    }
  }
  .code-block :where(.content) :where(.pre) .token.comment {
    color: var(--ds-gray-900) !important;
  }
  .code-block :where(.content) :where(.pre) .token.namespace {
    opacity: 0.7;
  }
  .code-block :where(.content) :where(.pre) .token.keyword {
    color: var(--ds-pink-900);
  }
  .code-block :where(.content) :where(.pre) .token.italic {
    font-style: italic;
  }
  .code-block :where(.content) :where(.pre) .token.deleted {
    color: var(--ds-red-900);
  }
  .code-block :where(.content) :where(.pre) .token.inserted {
    color: var(--ds-blue-900);
  }
  .code-block :where(.content) :where(.pre) .ln:focus-visible {
    outline: 2px solid var(--ds-focus-color);
  }
  .code-block :where(.content) :where(.pre) .ln:hover {
    color: var(--ds-gray-1000);
  }
  .code-block :where(.content) :where(.pre) .line[data-active="true"] {
    background: var(--ds-amber-300);
    box-shadow: inset 2px 0 0 0 var(--ds-amber-900);
  }
  .code-block :where(.content) :where(.pre) [data-added="true"]:after {
    content: "+";
    color: var(--ds-green-900);
    pointer-events: none;
    padding-left: 8px;
    font-weight: 500;
    position: absolute;
    inset: 0;
  }
  .code-block :where(.content) :where(.pre) [data-removed="true"]:after {
    content: "-";
    color: var(--ds-red-900);
    pointer-events: none;
    padding-left: 8px;
    font-weight: 500;
    position: absolute;
    inset: 0;
  }
  .code-block:where(.hide-numbers) :where(.content) :where(.pre) .ln {
    display: none;
  }
  .code-block :where(.content) :where(.pre) .language-json .token.boolean {
    color: var(--acme-success);
    font-weight: 600;
  }
  .code-block :where(.content) :where(.pre) .token.tag.attr-value {
    color: var(--ds-blue-900);
  }
  .code-block :where(.content) :where(.pre) .language-autohotkey .token.tag {
    color: #9a050f;
  }
  .code-block :where(.content) :where(.pre) .token.tag.script {
    color: var(--ds-gray-1000);
  }
  .code-block :where(.content) :where(.pre) .line {
    height: 20px;
    padding: 0 var(--padding);
    position: relative;
  }
  .code-block :where(.content) :where(.pre) .highlighted-line {
    height: 20px;
    padding: 0 var(--padding);
    position: relative;
    background: var(--ds-blue-300);
    box-shadow: inset 2px 0 0 0 var(--ds-blue-900);
  }
  .code-block :where(.content) :where(.pre) [data-highlighted="true"] {
    background: var(--ds-blue-300);
    box-shadow: inset 2px 0 0 0 var(--ds-blue-900);
  }
  .code-block :where(.content) :where(.pre) .line > div {
    display: inline-block;
  }
  .code-block :where(.content) :where(.pre) .highlighted-line > div {
    display: inline-block;
  }
  .code-block :where(.content) :where(.pre) .token.tag.script.string {
    color: var(--ds-blue-900);
  }
  .code-block :where(.content) :where(.pre) .token.directive.tag .tag {
    background: var(--ds-red-900);
    color: var(--ds-gray-900);
  }
  .code-block :where(.content) :where(.pre) .token.string {
    color: var(--ds-green-900);
  }
  .code-block :where(.content) :where(.pre) .token.attr-value {
    color: var(--ds-green-900);
  }
  .code-block :where(.content) :where(.pre) .token.important {
    font-weight: 700;
  }
  .code-block :where(.content) :where(.pre) .token.bold {
    font-weight: 700;
  }
  .code-block :where(.content) :where(.pre) .token.property {
    color: var(--ds-red-900);
  }
  .code-block :where(.content) :where(.pre) .token.entity {
    color: var(--ds-red-900);
  }
  .code-block :where(.content) :where(.pre) .token.punctuation {
    color: var(--ds-gray-1000);
  }
  .code-block :where(.content) :where(.pre) .token.operator {
    color: var(--ds-gray-1000);
  }
  .code-block :where(.content) :where(.pre) .token.selector {
    color: var(--ds-pink-900);
  }
  .code-block :where(.content) :where(.pre) .language-autohotkey .token.keyword {
    color: var(--ds-pink-900);
  }
  .code-block :where(.content) :where(.pre) .language-markdown .token.code {
    color: var(--ds-blue-900);
    font-weight: 400;
  }
  .code-block :where(.content) :where(.pre) .language-markdown-source .token.code {
    color: var(--ds-blue-900);
    font-weight: 400;
  }
  .code-block :where(.content) :where(.pre) .language-markdown .token.url {
    color: var(--ds-pink-900);
  }
  .code-block :where(.content) :where(.pre) .language-markdown-source .token.url {
    color: var(--ds-pink-900);
  }
  .code-block :where(.content) :where(.pre) .token.prolog {
    color: var(--accents-5);
  }
  .code-block :where(.content) :where(.pre) .token.doctype {
    color: var(--accents-5);
  }
  .code-block :where(.content) :where(.pre) .token.cdata {
    color: var(--accents-5);
  }
  .code-block :where(.content) :where(.pre) .token.function {
    color: var(--ds-purple-900);
  }
  .code-block :where(.content) :where(.pre) .token.attr-name {
    color: var(--ds-purple-900);
  }
  .code-block :where(.content) :where(.pre) .token.regex {
    color: var(--ds-purple-900);
  }
  .code-block :where(.content) :where(.pre) .token.tag {
    color: var(--ds-green-900);
  }
  .code-block :where(.content) :where(.pre) .token.class-name {
    color: var(--ds-green-900);
  }
  .code-block :where(.content) :where(.pre) .token.number {
    color: var(--ds-green-900);
  }
  .code-block :where(.content) :where(.pre) .language-json .token.property {
    color: var(--ds-gray-1000);
  }
  .code-block :where(.content) :where(.pre) .language-markdown .token.title {
    color: var(--ds-gray-1000);
  }
  .code-block :where(.content) :where(.pre) .language-markdown-source .token.title {
    color: var(--ds-gray-1000);
  }
  .code-block :where(.content) :where(.pre) .token.atrule {
    font-weight: 600;
  }
  .code-block :where(.content) :where(.pre) .language-autohotkey .token.selector {
    font-weight: 600;
  }
  .code-block :where(.content) :where(.pre) code[class*="language-css"] {
    font-weight: 600;
  }
  .code-block :where(.content) :where(.pre) .token.url {
    color: var(--ds-green-900);
  }
  .code-block :where(.content) :where(.pre) .token.symbol {
    color: var(--ds-green-900);
  }
  .code-block :where(.content) :where(.pre) .token.boolean {
    color: var(--ds-green-900);
  }
  .code-block :where(.content) :where(.pre) .token.variable {
    color: var(--ds-green-900);
  }
  .code-block :where(.content) :where(.pre) .token.constant {
    color: var(--ds-green-900);
  }
  .code-block :where(.content) :where(.pre) .language-markdown .token.list {
    color: var(--ds-gray-900);
  }
  .code-block :where(.content) :where(.pre) .language-markdown .token.hr {
    color: var(--ds-gray-900);
  }
  .code-block :where(.content) :where(.pre) .language-markdown-source .token.list {
    color: var(--ds-gray-900);
  }
  .code-block :where(.content) :where(.pre) .language-markdown-source .token.hr {
    color: var(--ds-gray-900);
  }
`;
