import assert from 'node:assert/strict';
const dir='/tmp/acme-m22/table',root='/Users/peterkloss/Dev/ACMElabs/design-system';
process.env.PLAYWRIGHT_BROWSERS_PATH='/Users/peterkloss/Library/Caches/acme-design-system/browser-checks/browsers';const pw=await import('/Users/peterkloss/Library/Caches/acme-design-system/browser-checks/node_modules/playwright/index.mjs');
const server=Bun.serve({port:0,fetch(req){const url=new URL(req.url);return url.pathname==='/consumer.js'?new Response(Bun.file(dir+'/consumer.js'),{headers:{'Content-Type':'text/javascript'}}):url.pathname==='/tokens.css'?new Response(Bun.file(root+'/src/generated/css/document/tokens.css'),{headers:{'Content-Type':'text/css'}}):new URL(req.url).pathname.endsWith('.js')?new Response(Bun.file(dir+new URL(req.url).pathname)):new Response('<!doctype html><link rel="stylesheet" href="/tokens.css"><script type="module" src="/consumer.js"></script>',{headers:{'Content-Type':'text/html'}})}});
const reports=[];
try{for(const engine of ['chromium','firefox','webkit']){const browser=await pw[engine].launch(engine==='chromium'?{executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true}:{headless:true});for(const framework of ['react']){const page=await browser.newPage({reducedMotion:'reduce'});page.setDefaultTimeout(6000);const errors=[],checks=[];page.on('pageerror',e=>{errors.push(String(e));console.log(engine,framework,'ERROR',String(e))});const check=async(name,run)=>{try{await page.goto(server.url.href+'?framework='+framework+'&case='+checks.length);await page.waitForFunction(()=>window.model&&document.querySelector('acme-table,delivery-table-lit'));await page.locator('[data-row="delivery-0"]').waitFor();await run();checks.push({name,pass:true});console.log(engine,framework,'PASS',name)}catch(error){checks.push({name,pass:false,error:String(error)});console.log(engine,framework,'FAIL',name,String(error))}};
await check('framework owns real rows and custom cell content',async()=>{await page.getByRole('textbox',{name:'Note delivery-0'}).fill('Retained');assert.equal(await page.locator('[data-row]').count(),10);await page.evaluate(()=>window.model.setColumnOrder(['select','region','name','amount','status','details']));assert.equal(await page.getByRole('textbox',{name:'Note delivery-0'}).inputValue(),'Retained');});
await check('ordering and visibility update grouped native headers and matching cells',async()=>{await page.evaluate(()=>{window.model.setColumnOrder(['select','region','name','amount','status','details']);window.model.getColumn('status').toggleVisibility(false)});await page.waitForTimeout(100);assert.equal(await page.locator('tbody [data-column="status"]').count(),0);assert.equal(await page.locator('thead [data-column="status"]').count(),0);assert.equal(await page.locator('thead th[colspan="2"]').count(),2);});
await check('row selection persists by identity through filtering and pagination',async()=>{await page.getByRole('checkbox',{name:'Select delivery-0',exact:true}).check();await page.evaluate(()=>window.model.getColumn('status').setFilterValue('Retry'));await page.waitForTimeout(100);assert.equal(await page.getByRole('checkbox',{name:'Select delivery-0',exact:true}).isChecked(),true);await page.getByRole('button',{name:'Next',exact:true}).click();await page.waitForTimeout(100);assert.equal(await page.evaluate(()=>window.model.atoms.pagination.get().pageIndex),1);assert.equal(await page.evaluate(()=>window.model.atoms.rowSelection.get()['delivery-0']),true);});
await check('column resizing and logical pinning keep header and cell geometry aligned in RTL',async()=>{await page.evaluate(()=>{document.documentElement.dir='rtl';window.model.getColumn('name').pin('start');window.model.getColumn('amount').pin('end');window.model.setColumnSizing({name:180,amount:120})});await page.waitForTimeout(100);const header=page.locator('thead [data-column="name"]'),cell=page.locator('tbody [data-column="name"]').first();assert.ok(Math.abs((await header.boundingBox()).width-(await cell.boundingBox()).width)<1);await page.getByRole('button',{name:'Resize name',exact:true}).focus();await page.keyboard.press('ArrowRight');await page.waitForFunction(()=>window.model.getColumn('name').getSize()===190);const before=await header.boundingBox();await page.locator('acme-table').evaluate(el=>el.getScrollElement().scrollLeft=-300);await page.waitForTimeout(100);const after=await header.boundingBox();assert.ok(Math.abs(before.x-after.x)<1);assert.ok(Math.abs((await header.boundingBox()).width-(await cell.boundingBox()).width)<1);});
await check('cell spans and row pinning omit covered cells and preserve native span meaning',async()=>{assert.equal(await page.locator('tbody [data-column="region"]').count(),1);assert.equal(await page.locator('tbody [data-column="region"]').getAttribute('rowspan'),'10');await page.evaluate(()=>window.model.getRow('delivery-0').pin('top'));await page.waitForTimeout(100);assert.equal(await page.locator('tbody [rowspan="0"]').count(),0);assert.equal(await page.locator('[data-row="delivery-2"] [data-column="status"]').getAttribute('colspan'),'2');assert.equal(await page.locator('tbody [data-row="delivery-0"]').count(),1);assert.equal(await page.locator('tbody [data-row="delivery-0"]').getAttribute('data-pinned'),'top');assert.equal(await page.locator('tbody [data-column="region"]').count(),2);});
await check('cell range selection follows logical identities through column ordering',async()=>{await page.evaluate(()=>window.model.selectCellRange({anchorRowId:'delivery-1',focusRowId:'delivery-3',anchorColumnId:'status',focusColumnId:'amount'}));await page.waitForTimeout(100);assert.equal(await page.evaluate(()=>window.model.getSelectedCellCount()),5);assert.equal(await page.locator('td[aria-selected="true"]').count(),5);await page.evaluate(()=>window.model.setColumnOrder(['select','name','region','amount','status','details']));await page.waitForTimeout(100);assert.equal(await page.evaluate(()=>window.model.getSelectedCellCount()),8);assert.equal(await page.locator('td[aria-selected="true"]').count(),8);});
await check('faceting aggregation and row grouping use the supplied Table models',async()=>{await page.evaluate(()=>{window.model.setGlobalFilter('Delivery 00');window.model.setGrouping(['status'])});await page.waitForTimeout(100);assert.equal(await page.evaluate(()=>window.model.getColumn('status').getFacetedUniqueValues().get('Retry')),4);assert.equal(await page.evaluate(()=>window.model.getRowModel().rows.length),2);assert.equal(await page.locator('tbody tr').count(),2);assert.equal(await page.locator('tfoot td').textContent(),String(await page.evaluate(()=>window.model.getColumn('amount').getAggregationValue({rows:window.model.getFilteredRowModel().rows}))));});
await check('custom plugin state remains independent of sorting and filtering',async()=>{await page.evaluate(()=>{window.model.markReviewed('delivery-0');window.model.setSorting([{id:'amount',desc:true}]);window.model.getColumn('status').setFilterValue('Retry')});await page.waitForTimeout(100);assert.deepEqual(await page.evaluate(()=>window.model.getReviewedIds()),['delivery-0']);assert.equal(await page.locator('tbody tr').first().getAttribute('data-row'),'delivery-198');});

await check('application grid keyboard navigation and native cell editors keep separate keys',async()=>{const status=page.locator('[data-row="delivery-0"]>[data-column="status"]');await status.focus();await page.keyboard.press('ArrowRight');await page.waitForTimeout(100);assert.equal(await page.evaluate(()=>window.model.getFocusedCell()?.column.id),'amount');await page.keyboard.press('ArrowDown');await page.waitForTimeout(100);assert.equal(await page.evaluate(()=>window.model.getFocusedCell()?.row.id),'delivery-1');await page.locator('[data-row="delivery-0"]>[data-column="name"]').focus();await page.keyboard.press('F2');await page.keyboard.type('Edited');assert.equal(await page.getByRole('textbox',{name:'Note delivery-0'}).inputValue(),'Edited');await page.keyboard.press('ArrowLeft');assert.equal(await page.getByRole('textbox',{name:'Note delivery-0'}).evaluate(el=>el===el.getRootNode().activeElement),true);await page.keyboard.press('Escape');assert.equal(await page.locator('[data-row="delivery-0"]>[data-column="name"]').evaluate(el=>el===el.getRootNode().activeElement),true);});
reports.push({engine,framework,checks,errors});await page.close();}await browser.close();}}finally{server.stop(true)}await Bun.write(dir+'/consumer-results.json',JSON.stringify(reports,null,2));if(reports.some(r=>r.errors.length||r.checks.some(c=>!c.pass)))process.exitCode=1;
