// Generated by scripts/split-css.ts from the audited house sheet. Do not edit.
import { css } from "lit";
export const linkCardCss = css`
.link-cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(200px,1fr));gap:16px}
.link-card{display:flex;flex-direction:column;justify-content:center;gap:2px;min-height:64px;padding:10px 8px 10px 16px;border-radius:var(--r-sm);background:var(--surface);box-shadow:var(--ds-shadow-border-small);color:var(--text);text-decoration:none;position:relative}
.link-card:hover{box-shadow:var(--ds-shadow-border-medium);text-decoration:none}
.link-card .title{font-size:14px;line-height:20px;letter-spacing:-.28px;font-weight:600}
.link-card .desc{font-size:13px;line-height:18px;color:var(--ds-gray-800)}
.link-card .badge{position:absolute;right:12px;top:12px}
.rec-card{display:block;padding:12px 16px;border-radius:var(--r-sm);background:var(--surface);box-shadow:var(--ds-shadow-border-small);color:var(--text);text-decoration:none}
.rec-card .title{font-size:14px;line-height:20px;font-weight:500}
.rec-card .desc{font-size:14px;line-height:20px;color:var(--text-2)}
`;
