// Generated by the style generator from the reference spec. Do not edit; edit the mapping and regenerate.
import { css } from "lit";
export const kbdCss = css`
  .kbd:where(.sm) {
    margin-left: 0.125rem;
    height: 1.25rem;
    min-height: 1.25rem;
    min-width: 1.25rem;
    padding-inline: 0.25rem;
    font-size: 0.75rem;
    line-height: 1.7em;
  }
  .kbd:where(:not(.sm)) {
    margin-left: 0.25rem;
    min-height: 1.5rem;
    min-width: var(--acme-gap);
    padding-inline: 0.375rem;
    font-size: 0.875rem;
    line-height: 1.7em;
  }
  .kbd {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    border-radius: 0.25rem;
    background-color: var(--ds-background-100);
    padding-block: 0;
    font-family: var(--acme-font-sans) !important;
    line-height: 1.7em !important;
    color: var(--ds-gray-1000);
    box-shadow: 0 0 0 1px var(--ds-gray-alpha-400);
  }
`;
