// Generated by the style generator from the reference spec. Do not edit; edit the mapping and regenerate.
import { css } from "lit";
export const tooltipKbdCss = css`
  :host([data-in-tooltip]) > kbd {
    height: 1.25rem !important;
    min-height: 0 !important;
    min-width: 1.25rem !important;
    border-radius: 0.25rem;
    background-color: var(--ds-gray-400) !important;
    font-size: 0.75rem;
    line-height: calc(1 / 0.75);
    box-shadow: none !important;
  }
`;
