// Generated by scripts/split-css.ts from the audited house sheet. Do not edit.
import { css } from "lit";
export const sliderCss = css`
.slider{-webkit-appearance:none;appearance:none;width:216px;max-width:100%;height:8px;border-radius:999px;margin:6px 0;
        background:linear-gradient(90deg,var(--accent) var(--pct,50%),var(--track) 0);cursor:pointer}
.slider::-webkit-slider-thumb{-webkit-appearance:none;width:6px;height:14px;border-radius:1px;background:var(--ds-background-100);box-shadow:0 0 0 1px var(--ds-gray-alpha-600)}
.slider::-moz-range-thumb{width:6px;height:14px;border:0;border-radius:1px;background:var(--ds-background-100);box-shadow:0 0 0 1px var(--ds-gray-alpha-600)}
.slider[disabled]{background:linear-gradient(90deg,var(--ds-gray-500) var(--pct,50%),var(--track) 0);cursor:not-allowed}
.slider:focus-visible{box-shadow:var(--ring);border-radius:999px}
`;
